// ===== PLAN DATA =====
// Tập kết: 墨田区向島5-35-11 (nhà anh Hà)
// Khách sạn: HOTEL R9 The Yard Kurobe (2 đêm)
// Day 1 & 2: kết thúc tại hotel | Day 3: hotel → Tokyo tối

const PLANS = {
  A: {
    name: '蓼科高原 & Alps Drive',
    color: '#2E4A6B',
    subtitle: 'ビーナスライン絶景 + 1泊Nagano + Alps縦断ドライブ + tulip + 称名滝 + ほたるいか + Trolley',
    route: '蓼科高原 → ビーナスライン → 白馬Alps → チューリップフェア → 称名滝 → ほたるいか → トロッコ',
    highlights: [
      { icon: '🏔️', text: 'ビーナスライン + 北八ヶ岳ロープウェイ — thiên nhiên không đám đông' },
      { icon: '🌷', text: 'となみチューリップフェア 350万本 — trên đường Day 2' },
      { icon: '💧', text: '称名滝+ハンノキ滝 — double waterfall V-shape tháng 5' },
    ],
    totalKm: 1330,
    routeGo: '中央道 → 諏訪IC → 蓼科 → ビーナスライン → 松本 → 大町 → 白馬 → 糸魚川 → 砺波 (450km · 2 ngày)',
    routeReturn: '北陸道 → 関越道 (430km · 5h) — an toàn lái đêm, ít cua',
    routeOptions: [
      '✅ 中央道→諏訪IC→蓼科→ビーナスライン→松本→大町→白馬→糸魚川→砺波→黒部 — Cung đường Alps đẹp nhất!',
      '上信越道→長野→松本→白馬→糸魚川→砺波→黒部 — Bỏ 蓼科, tiết kiệm 1 đêm.',
      '関越道→北陸道→砺波→黒部 — Nhanh nhất, bỏ Nagano hoàn toàn.',
    ],
    gallery: [
      { src: 'images/plan-a/takeshina-kogen.png', caption: '蓼科高原 — cao nguyên xanh mướt, không khí trong lành', spot: '蓼科高原' },
      { src: 'images/plan-a/takeshina-lake.jpg', caption: '蓼科湖 — mặt hồ phản chiếu núi tuyệt đẹp buổi sáng', spot: '蓼科湖' },
      { src: 'images/plan-a/kita-yatsugatake.jpg', caption: '北八ヶ岳ロープウェイ — gondola lên 2,237m ngắm 3 dãy Alps', spot: '北八ヶ岳ロープウェイ' },
      { src: 'images/plan-a/venus-line.jpg', caption: 'ビーナスライン — cung đường đẹp nhất Nagano, đồng cỏ bao la', spot: 'ビーナスライン' },
      { src: 'images/plan-a/shirakaba-lake.png', caption: '白樺湖 — hồ bạch dương thơ mộng trên ビーナスライン', spot: '白樺湖' },
      { src: 'images/plan-a/matsumoto-castle.jpg', caption: '松本城 — quốc bảo Nhật Bản, lâu đài đen "Karasu-jō" với núi Alps làm nền', spot: '松本城' },
      { src: 'images/plan-a/nagano-tualyp.png', caption: 'となみチューリップフェア — 350万本 hoa tulip rực rỡ', spot: 'となみチューリップフェア' },
      { src: 'images/plan-a/sho-myo.jpeg', caption: '称名滝 — thác cao nhất Nhật Bản 350m, nước đổ hùng vĩ', spot: '称名滝' },
      { src: 'images/plan-a/hanno-taki.png', caption: 'ハンノキ滝 — thác đôi V-shape chỉ có tháng 5, bên cạnh 称名滝', spot: 'ハンノキ滝' },
    ],
    days: [
      {
        dayNum: 1,
        title: 'Day 1 — Chủ Nhật 3/5',
        subtitle: '向島 → 蓼科高原 → ビーナスライン → 白樺湖 → Hotel 蓼科',
        specialties: [
          { emoji: '🥛', name: '牛乳ソフトクリーム', where: '牧場直売所', desc: 'Kem sữa tươi từ trang trại — ngậy mịn, đặc sản vùng cao nguyên' },
          { emoji: '🍜', name: '信州そば', where: '蓼科 or 茅野', desc: 'Soba kiều mạch Nagano — ăn trưa dọc đường ビーナスライン' },
          { emoji: '🥩', name: 'Shinshu beef / BBQ', where: 'Hotel 蓼科 tối', desc: 'Thịt bò Shinshu tối tại khách sạn — thưởng thức sau ngày cao nguyên' },
        ],
        segments: [
          { from: '向島', to: '花桃の里 (園原IC)', km: 280, time: '3h30', mode: 'car' },
          { from: '花桃の里', to: '諏訪IC (蓼科)', km: 60, time: '1h', mode: 'car' },
          { from: '蓼科湖', to: '北八ヶ岳ロープウェイ', km: 15, time: '20min', mode: 'car' },
          { from: 'ロープウェイ', to: 'ビーナスライン (白樺湖まで)', km: 40, time: '1h', mode: 'car' },
          { from: '白樺湖', to: 'Hotel 蓼科', km: 20, time: '30min', mode: 'car' },
        ],
        stops: [
          {
            id: 'a-d1-depart',
            name: 'Tập kết nhà anh Hà (向島)',
            lat: 35.7180, lng: 139.8130,
            arrivalTime: '06:00',
            duration: 0,
            type: 'minor',
            description: '3 xe tập kết tại 墨田区向島5-35-11. Đổ xăng → 首都高 → 中央道 hướng 諏訪. Plan A đi 中央道 — nhanh nhất đến 蓼科.',
            food: null,
            tips: '2 nhà đến trước 5:50. 中央道 GW sáng sớm vẫn chạy được — xuất phát 6:00 là ổn.',
            weather: '18-24°C · 🌤️ Tokyo ấm',
          },
          {
            id: 'a-hanamomo',
            name: '花桃の里 — 阿智村 月川温泉郷',
            lat: 35.4310, lng: 137.5870,
            arrivalTime: '09:30',
            duration: 45,
            type: 'major',
            description: '日本一の桃源郷！5,000本の赤・白・ピンク三色花桃が山肌4kmに咲き誇る。中央道 園原ICからすぐ — 蓼科への道中にほぼ寄り道なし。5月3日時点は見頃ピーク（4月下旬）を過ぎているため開花確認が必須。咲いていれば圧巻の桃源郷。',
            food: '花桃の苗・地元農産物販売あり · 山菜うどん',
            tips: '⚠️ 訪問前に必ず開花状況を確認: 開花情報専用ダイヤル 📞 0265-48-5750（24時間）。きれいに咲いていれば45分、散っていたら軽く車窓観賞して先へ。駐車場 普通車1,000円。',
            weather: '14-20°C · 🌸 山あいの春 — 花桃のグラデーション',
          },
          {
            id: 'a-tateshina-lake',
            name: '蓼科湖 + ビーナスライン入口',
            lat: 36.1003, lng: 138.2817,
            arrivalTime: '11:00',
            duration: 45,
            type: 'major',
            description: '蓼科湖: hồ nhân tạo tuyệt đẹp, bạch dương (白樺) và lá thông (カラマツ) bao quanh, phản chiếu núi 蓼科山 trên mặt nước. Đây là điểm bắt đầu ビーナスライン. Trẻ nghịch nước hồ, chụp ảnh, ăn kem sữa tươi từ quầy bên hồ.',
            food: '牛乳ソフトクリーム tại quầy ven hồ · 信州そば gần đây',
            tips: 'Đến trước 9h — còn vắng, ánh sáng đẹp. Hồ phản chiếu núi tuyệt nhất buổi sáng.',
            weather: '10-18°C · 🌿 Mát trong lành, cao nguyên 1,400m',
          },
          {
            id: 'a-ropeway',
            name: '北八ヶ岳ロープウェイ',
            lat: 36.1164, lng: 138.3167,
            arrivalTime: '11:30',
            duration: 90,
            type: 'major',
            description: '100 người/chuyến, lên 2,237m trong 7 phút. Từ đỉnh nhìn toàn bộ 3 dãy Alps Nhật Bản. Xuống bộ tham quan 坪庭自然園 — vườn cao nguyên với đá nham thạch và cây thấp lùn — đi bộ 30 phút nhẹ nhàng, trẻ em thích. Tháng 5 còn có thể thấy tuyết trên đỉnh.',
            food: 'Cafe tại đỉnh — コケモモジュース (nước việt quất núi) đặc sản',
            tips: 'Trên đỉnh lạnh hơn 10°C — mang áo gió. Chuyến sáng ít người. Vé khứ hồi ~¥1,900/người lớn, ¥950/trẻ.',
            weather: '2-10°C · 🏔️ Lạnh trên đỉnh, cần áo gió',
          },
          {
            id: 'a-venusline-drive',
            name: 'ビーナスライン ドライブ (白樺湖 → 霧ヶ峰)',
            lat: 36.0997, lng: 138.1853,
            arrivalTime: '13:30',
            duration: 90,
            type: 'major',
            description: 'Cung đường đẹp nhất Nagano! Từ 白樺湖 leo lên 霧ヶ峰 (1,925m) — đồng cỏ bao la, Alps phía xa, tuyết còn sót trên núi, chồi non xanh mới nhú. Tháng 5 là cảnh "xuân-hạ giao thoa" đặc biệt nhất trong năm. Dừng ở 車山肩 ngắm 360 độ.',
            food: 'Ăn trưa tại ころぼっくるひゅって (cafe nổi tiếng ビーナスライン) hoặc 旅の駅霧ヶ峰ビーナス',
            tips: 'Tháng 5 ít đông hơn hè nhiều. Dừng 車山肩 để chụp ảnh — không gian mở, trẻ chạy thoải mái.',
            weather: '8-15°C · 🌿 Cao nguyên, tuyết + chồi non đan xen',
          },
          {
            id: 'a-pension-tateshina',
            name: 'ペンション 風と旅のアトリエ',
            lat: 36.0880, lng: 138.1800,
            arrivalTime: '16:30',
            duration: 0,
            type: 'major',
            description: '宿泊: ペンション 風と旅のアトリエ（長野県立科町大門3518-2649）。白樺湖エリア・ビーナスライン沿いの高原ペンション。夜は満天の星空、翌朝は鳥のさえずりで目覚める — 3家族10人の特別な蓼科の夜。',
            food: '夕食: ペンション手料理コース (信州食材) · ワイン · 朝食: 焼きたてパン + 高原野菜サラダ',
            tips: 'チェックイン 15:00〜。白樺湖まで車で数分。夜は外で星空観察 — 蓼科高原は光害少なく満天の星。⚠️ 翌朝出発前に宿主に道路凍結状況を確認すること — 標高1,400mのため5月初旬でも早朝3〜7°Cになることがあり、ビーナスラインが朝方凍結する場合あり。9時以降の出発が安全。翌朝の朝食時間も事前に相談。',
            weather: '8-14°C · 🌙 高原の夜 — 満天の星、鳥のさえずり',
          },
        ],
      },
      {
        dayNum: 2,
        title: 'Day 2 — Thứ Hai 4/5',
        subtitle: '蓼科 → 松本城 → 白馬Alps → 糸魚川 → チューリップフェア → 称名滝 → ほたるいか → HOTEL R9',
        specialties: [
          { emoji: '🍡', name: 'Soba 信州', where: '松本城 area', desc: 'Mì kiều mạch Shinshu — đặc sản Nagano, ăn trưa gần 松本城' },
          { emoji: '🌷', name: 'チューリップソフト', where: '砺波 フェア', desc: 'Kem tulip màu hồng ngọt dịu — ăn giữa 350万本 hoa' },
          { emoji: '🍦', name: 'Kem sữa 立山', where: '称名滝 area', desc: 'Kem tươi vùng núi — bán tại レストハウス称名' },
          { emoji: '🦑', name: 'ほたるいか tempura', where: 'ほたるいかミュージアム', desc: 'Mực phát sáng chiên giòn — ăn tối tươi nhất có thể' },
        ],
        segments: [
          { from: 'Hotel 蓼科', to: '松本城', km: 50, time: '1h', mode: 'car' },
          { from: '松本城', to: '白馬 → 糸魚川 (R148)', km: 130, time: '2h30', mode: 'car' },
          { from: '糸魚川 → チューリップフェア (砺波)', km: 80, time: '1h', mode: 'car' },
          { from: 'チューリップフェア → 称名滝', km: 60, time: '50min', mode: 'car' },
          { from: '称名滝 → ほたるいかミュージアム', km: 50, time: '50min', mode: 'car' },
          { from: 'ほたるいかミュージアム → HOTEL R9', km: 30, time: '35min', mode: 'car' },
        ],
        stops: [
          {
            id: 'a-d2-depart',
            name: 'Xuất phát ペンション風と旅のアトリエ → 松本城',
            lat: 36.0880, lng: 138.1800,
            arrivalTime: '08:30',
            duration: 0,
            type: 'minor',
            description: 'Check-out sớm. Ăn sáng tại pension rồi xuất phát đi 松本城. Route: 蓼科 → R299 → 松本 (~1h). Đi sớm để kịp tham quan lâu đài trước khi đông.',
            food: 'Ăn sáng tại pension (hỏi trước giờ phục vụ)',
            tips: '⚠️ 凍結リスク: 5月初旬の早朝、ビーナスライン沿道（標高1,400m）が凍結する場合あり。スタッドレス不要だが、出発前に宿主に路面状況を確認すること。気温5°C以上・8時以降の出発が安全。',
            weather: '8-14°C · 🌤️ Sáng cao nguyên mát — kiểm tra nhiệt độ trước khi đi',
          },
          {
            id: 'a-matsumoto-castle',
            name: '松本城 (Matsumoto Castle)',
            lat: 36.2384, lng: 137.9690,
            arrivalTime: '09:30',
            duration: 90,
            type: 'major',
            description: 'Quốc bảo Nhật Bản — 1 trong 5 lâu đài gốc còn nguyên vẹn. Lâu đài đen "Karasu-jō" (Quạ thành) phản chiếu trên hào nước, núi Alps Bắc làm nền. Tháng 5 hoa anh đào muộn còn nở, cảnh tuyệt đẹp. Vào trong tham quan 6 tầng (cầu thang dốc — bỏ giày).',
            food: 'Cafe Matsumotojō gần lâu đài hoặc ăn nhẹ trước khi đi tiếp',
            tips: 'Đến 09:30 trước khi đông. Mua vé trước online. Trẻ em < 6 tuổi miễn phí. Mang vớ dày — sàn gỗ lạnh.',
            weather: '10-18°C · 🌸 Sáng mát, lâu đài + hoa anh đào muộn',
          },
          {
            id: 'a-hakuba-view',
            name: '白馬村 — Alps Drive (lái qua)',
            lat: 36.6984, lng: 137.8617,
            arrivalTime: '12:00',
            duration: 20,
            type: 'minor',
            description: 'Lái qua 白馬村 sau khi rời 松本城. Dừng nhanh 20 phút ngắm toàn cảnh dãy Alps Bắc phủ tuyết. Trẻ duỗi chân, chụp ảnh.',
            food: 'Mua bento/onigiri tại konbini Hakuba để ăn trên xe',
            tips: 'Không vào sâu — chỉ dừng quick photo. Mục tiêu là kịp tulip fair trước 14:00.',
            weather: '10-18°C · 🏔️ Núi tuyết, thung lũng xanh',
          },
          {
            id: 'a-tulip',
            name: 'となみチューリップフェア 2026',
            lat: 36.6477, lng: 136.9635,
            arrivalTime: '13:30',
            duration: 75,
            type: 'major',
            description: '300品種350万本のチューリップ！「花の大谷」高さ4m×30m花のトンネル、水上花壇、チューリップタワー展望台地上絵。5/5こどもの日は中学生以下無料！Ghé giữa ngày — đủ thời gian ăn trưa + chụp ảnh.',
            food: 'Ăn trưa tại フェア: チューリップソフト + 各所屋台',
            tips: '砺波ICから車で5分。Day 2 đến 11:30 ít đông hơn sáng sớm ngày cuối tuần. 5/5 trẻ em miễn phí!',
            weather: '14-20°C · 🌷 チューリップ満開',
          },
          {
            id: 'a-shomyo',
            name: '称名滝 + ハンノキ滝',
            lat: 36.5733, lng: 137.4867,
            arrivalTime: '15:30',
            duration: 90,
            type: 'major',
            description: '2 thác V-shape song song: 称名滝 (350m) + ハンノキ滝 (500m). Tháng 5 tuyết tan = nước cực mạnh, có thể nghe tiếng từ xa. Chiều vẫn đẹp — ánh sáng chiều chiếu vào đá đỏ vách núi. Đường paved 30 phút.',
            food: 'Kem sữa tươi tại レストハウス称名 (mở đến 17:00)',
            tips: 'Mang áo mưa mỏng — nước bắn ra rất nhiều. Đường paved hoàn toàn, đẩy được xe đẩy.',
            weather: '10-16°C · 🌤️ Mát, ánh chiều → vách đá đỏ rực',
          },
          {
            id: 'a-hotaruika',
            name: 'ほたるいかミュージアム',
            lat: 36.7632, lng: 137.3355,
            arrivalTime: '17:30',
            duration: 60,
            type: 'major',
            description: 'Phòng tối: hàng nghìn con mực nhỏ phát ánh sáng xanh lam. Chỉ có mùa 3-5月, chỉ có Toyama Bay. Touch pool cho trẻ. Ăn tối tại quán bên cạnh trước khi về hotel.',
            food: 'Ăn tối: ほたるいか tempura tươi nhất tại quán bên cạnh',
            tips: 'Live display phòng tối là highlight — trẻ mê nhất. Xem xong ăn ngay tại đây luôn.',
            weather: '15-20°C · 🌆 Chiều tối, ven biển',
          },
          {
            id: 'a-hotel-r9-d2',
            name: 'HOTEL R9 The Yard Kurobe',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '19:30',
            duration: 0,
            type: 'major',
            description: 'Check-in HOTEL R9. Ngày 2 dày nhất — nghỉ sớm, ngủ thẳng giấc.',
            food: 'Đã ăn tối tại ほたるいか — hoặc ghé konbini nếu cần thêm',
            tips: 'Đặt vé Trolley ngày mai trước khi ngủ!',
            weather: '14-20°C · 🌙 Mát mẻ',
          },
        ],
      },
      {
        dayNum: 3,
        title: 'Day 3 — Thứ Ba 5/5',
        subtitle: '宇奈月 → トロッコ 11:48 → ひみ番屋街ランチ → 雨晴海岸 Golden Hour → 富岩運河スタバ夜景 → Tokyo',
        specialties: [
          { emoji: '🍦', name: 'Kem onsen', where: '宇奈月', desc: 'Kem mềm mịn bán dọc phố onsen — trẻ em mê' },
          { emoji: '🍡', name: '温泉たまご', where: '宇奈月', desc: 'Trứng luộc suối nóng, lòng đào — ăn kèm muối' },
          { emoji: '🍣', name: 'ます寿し bento', where: 'SA đường về', desc: 'Sushi cá hồi ép truyền thống Toyama — mua mang đi trên xe' },
        ],
        segments: [
          { from: 'HOTEL R9 (checkout 10:00)', to: '宇奈月駅', km: 20, time: '20min', mode: 'car' },
          { from: '宇奈月 (11:48発)', to: '笹平 往復', km: 16, time: '2h10', mode: 'trolley' },
          { from: '宇奈月 (~14:00)', to: 'ひみ番屋街 (氷見)', km: 60, time: '1h', mode: 'car' },
          { from: 'ひみ番屋街', to: '雨晴海岸', km: 15, time: '15min', mode: 'car' },
          { from: '雨晴海岸', to: '富岩運河環水公園', km: 20, time: '30min', mode: 'car' },
          { from: '富岩運河', to: '向島 (Tokyo)', km: 400, time: '5h', mode: 'car' },
        ],
        stops: [
          {
            id: 'a-unazuki',
            name: '宇奈月温泉 散策',
            lat: 36.8173, lng: 137.5841,
            arrivalTime: '10:20',
            duration: 85,
            type: 'minor',
            description: 'Checkout hotel 10:00 → hành lý để trên xe → lái đến 宇奈月駅 (20 phút). Tản bộ phố onsen trước khi lên tàu. Ngâm chân ashiyu miễn phí. Mua snack ăn trên tàu.',
            food: 'Kem onsen · 温泉たまご · bánh mochi · onigiri cho lên tàu',
            tips: 'Checkout 10:00 → xe đến 宇奈月駅 10:20. Tàu Trolley lên 11:48 — đúng giờ ra ga, không trễ!',
            weather: '14-20°C · 🌸 Dễ chịu',
          },
          {
            id: 'a-trolley',
            name: '黒部峡谷トロッコ (宇奈月〜笹平)',
            lat: 36.8150, lng: 137.5860,
            arrivalTime: '11:48',
            duration: 130,
            type: 'major',
            description: 'Tàu trolley hẻm V-shape Kurobe — hẻm núi sâu nhất Nhật Bản. 2026: đến 笹平 (5/3~5/9). Khứ hồi ~2h10. Về đến 宇奈月 khoảng 14:00.',
            food: 'Mua snack tại 宇奈月駅 trước khi lên tàu',
            tips: '⚠️ Vé 11:48 — ĐÚNG GIỜ, không trễ! Đặt vé từ 1/4 tại torokko-yoyaku.com. Chọn toa mở (普通客車). Ngồi bên PHẢI chiều đi để ngắm sông tốt nhất.',
            weather: '14-20°C · 🌿 Hẻm núi mát mẻ, cảnh xanh',
          },
          {
            id: 'a-himi',
            name: 'ひみ番屋街 — 氷見漁港場外市場',
            lat: 36.8567, lng: 136.9870,
            arrivalTime: '15:00',
            duration: 90,
            type: 'major',
            description: '氷見漁港直送の海産物マーケット！白エビ天丼・氷見うどん・海鮮丼で遅めのランチ。子どもたちは広い港エリアを走り回れる。富山みやげの最終調達にも最適。雨晴海岸まで車で15分。',
            food: '🍜 氷見うどん · 🦐 白エビ天丼 · 🐟 海鮮丼 · Omiyage: 氷見牛・海産物',
            tips: '子連れに最高のスポット — 広い屋外エリアで自由に動ける。駐車場無料。トイレあり。雨晴海岸まで15分。',
            weather: '15-20°C · 🌊 港の海風',
          },
          {
            id: 'a-ameharashi',
            name: '雨晴海岸 (Ameharashi Coast)',
            lat: 36.7740, lng: 137.0240,
            arrivalTime: '17:00',
            duration: 100,
            type: 'major',
            description: '富山湾 + 立山連峰 + 赤いJR氷見線の聖地！日没18:41の1時間40分前に到着しゴールデンアワーをフルに楽しむ。17:00〜18:41まで山の色が刻々と変化する絶景タイム。3家族で記念撮影の絶好チャンス。',
            food: 'ひみ番屋街で買ったおやつ · 近くのカフェ',
            tips: '📸 17:00着でゴールデンアワーをフル確保。JR氷見線の時刻を事前確認 → 列車が来る瞬間にシャッター。北陸道 高岡ICへすぐ。駐車場無料。',
            weather: '14-18°C · 🌅 ゴールデンアワー → 日没18:41 → 山が黄金色に',
            images: [
              { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Ameharashi_Coast.jpg/640px-Ameharashi_Coast.jpg', alt: '雨晴海岸 富山湾 立山連峰' },
            ],
          },
          {
            id: 'a-kansui',
            name: '富岩運河環水公園 + 世界一美しいスタバ',
            lat: 36.6983, lng: 137.2113,
            arrivalTime: '19:30',
            duration: 75,
            type: 'major',
            description: '夜の富岩運河環水公園！天門橋のライトアップが水面に映り込む幻想的な夜景。「世界一美しいスタバ」で日没後の絶景を楽しむ。日没(18:41)から約50分後 — ライトアップが最高潮に。',
            food: 'スターバックス コーヒー 富山環水公園店 (22:30まで営業) · テラス席で夜風を感じながら',
            tips: '📸 撮影ベスト: スタバを横から写す構図 + 天門橋 + 水面リフレクション。ライトアップ22:00まで、天門橋展望塔21:00まで。駐車場無料。',
            weather: '14-18°C · 🌃 夜景 — ライトアップ22時まで',
          },
          {
            id: 'a-return',
            name: 'Xuất phát về Tokyo',
            lat: 35.7180, lng: 139.8130,
            arrivalTime: '21:00',
            duration: 0,
            type: 'major',
            description: '北陸道 → 関越道で帰路。~5h。向島到着 2:00~2:30 AM。スタバで夜景を楽しんだ後、子どもたちは車内で熟睡。GW Uターンラッシュのピーク後なので渋滞ほぼなし。',
            food: '出発前にコンビニで夜食・飲み物 · SAでます寿しbento',
            tips: '21時出発はUターンラッシュ後 — 渋滞なし。SA休憩1〜2回。運転交代を忘れずに。向島着は約2:30 AM。',
            weather: '14°C → 18°C · 🌙 夜の北陸道 — 空いていて走りやすい',
          },
        ]
      },
    ],
  },

  B: {
    name: '五箇山 UNESCO + Toyama 3 bom tấn',
    color: '#3D6B4F',
    subtitle: 'Tulip 350万本 → Làng mái tranh bí ẩn → đôi thác → mực phát sáng → Trolley',
    route: 'チューリップフェア → 五箇山 → 称名滝 → ほたるいか → トロッコ',
    highlights: [
      { icon: '🌷', text: 'となみチューリップフェア 350万本 — trên đường đến 五箇山' },
      { icon: '🏘️', text: '五箇山 相倉 UNESCO — yên tĩnh, ít đông hơn 白川郷' },
      { icon: '💧', text: '称名滝+ハンノキ滝 V-shape — chỉ có mùa tuyết tan' },
    ],
    totalKm: 1210,
    routeGo: '関越道 + 北陸道 via 長岡 → 砺波IC → 五箇山IC (400km · 5h30) — dễ lái nhất',
    routeReturn: '北陸道 → 関越道 (400km · 5h) — an toàn lái đêm',
    routeOptions: [
      '✅ 関越道→北陸道 via 長岡→砺波→五箇山 — Dễ lái nhất, ít cua. SA lớn. Tulip fair ON ROUTE! (400km · 5h30)',
      '上信越道→北陸道→砺波→五箇山 — Ngắn hơn 20km, cảnh núi→biển đẹp. (380km · 5h)',
      '中央道→長野道→上信越道→北陸道 — Phải vòng, không khuyên. (430km · 6h)',
    ],
    gallery: [
      // Thêm ảnh: { src: 'images/plan-b/ten-anh.jpg', caption: 'Mô tả', spot: 'Tên điểm đến' }
    ],
    days: [
      {
        dayNum: 1,
        title: 'Day 1 — Chủ Nhật 3/5',
        subtitle: '向島 → チューリップフェア → 五箇山 → HOTEL R9',
        specialties: [
          { emoji: '🌷', name: 'チューリップソフト', where: '砺波 フェア', desc: 'Kem tulip ngọt dịu — đặc sản hội chợ, chụp ảnh cực đẹp' },
          { emoji: '🧈', name: '五箇山豆腐', where: '五箇山', desc: 'Đậu hũ cứng nướng than, đậm đà — đặc sản UNESCO village' },
          { emoji: '🐟', name: '岩魚塩焼き', where: '五箇山', desc: 'Cá suối nướng muối thơm giòn — trẻ em thích' },
        ],
        segments: [
          { from: '向島', to: 'チューリップフェア (砺波)', km: 400, time: '5h30', mode: 'car' },
          { from: 'チューリップフェア', to: '五箇山', km: 30, time: '35min', mode: 'car' },
          { from: '五箇山', to: 'HOTEL R9', km: 110, time: '1h30', mode: 'car' },
        ],
        stops: [
          {
            id: 'b-d1-depart',
            name: 'Tập kết nhà anh Hà (向島)',
            lat: 35.7180, lng: 139.8130,
            arrivalTime: '06:00',
            duration: 0,
            type: 'minor',
            description: '3 xe tập kết tại 墨田区向島5-35-11. Đổ xăng → 向島入口 → 首都高 → 関越道 hướng Niigata/Toyama.',
            food: null,
            tips: '2 nhà đến trước 5:50. Plan B đi 関越道 — dễ lái nhất, trẻ ít say xe.',
            weather: '18-24°C · 🌤️ Tokyo ấm',
          },
          {
            id: 'b-tulip',
            name: 'となみチューリップフェア 2026',
            lat: 36.6477, lng: 136.9635,
            arrivalTime: '10:30',
            duration: 120,
            type: 'major',
            description: '国内最大級！300品種350万本。「花の大谷」(高さ4m×長さ30m)、水上花壇(チューリップが水面に浮かぶ)、タワー展望台から地上絵。5/5こどもの日は中学生以下入場無料！',
            food: 'チューリップソフトクリーム · ほたるいかソフト(挑戦!) · 軽食各所',
            tips: '砺波ICから車で5分。10:30前着推奨（GW混雑）。五箇山へは同じ方向！5/5中学生以下無料。',
            weather: '14-20°C · 🌷 チューリップ満開',
          },
          {
            id: 'b-gokayama',
            name: '五箇山 相倉集落',
            lat: 36.4260, lng: 136.9355,
            arrivalTime: '13:15',
            duration: 90,
            type: 'major',
            description: 'Làng mái tranh gassho UNESCO yên tĩnh nhất — ít đông hơn 白川郷 nhiều. Trẻ em thích khám phá nhà 3 tầng cổ. Không khí trong lành, chụp ảnh đẹp xuất thần.',
            food: '五箇山豆腐 nướng than · 岩魚塩焼き · amazake ngọt',
            tips: '砺波IC → 東海北陸道 → 五箇山IC. Ghé trên đường — không vòng!',
            weather: '13-18°C · 🌤️ Ấm, có thể mưa nhẹ',
          },
          {
            id: 'b-hotel-r9-d1',
            name: 'HOTEL R9 The Yard Kurobe',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '16:30',
            duration: 0,
            type: 'major',
            description: 'Check-in khách sạn. Nghỉ ngơi sau ngày đi nhiều.',
            food: 'Ăn tối: 富山ブラックラーメン hoặc hải sản Toyama',
            tips: 'Gần 黒部IC, tiện di chuyển ngày hôm sau.',
            weather: '14-20°C · 🌙 Mát mẻ buổi tối',
          },
        ],
      },
      {
        dayNum: 2,
        title: 'Day 2 — Thứ Hai 4/5',
        subtitle: '称名滝 → ほたるいかミュージアム → 魚津水族館',
        specialties: [
          { emoji: '🍦', name: 'Kem sữa 立山', where: '称名滝 area', desc: 'Kem tươi vùng núi — quầy gần bãi đỗ' },
          { emoji: '🦑', name: 'ほたるいか tempura', where: 'ほたるいかミュージアム', desc: 'Mực phát sáng chiên giòn — trải nghiệm ăn tươi nhất' },
          { emoji: '🦐', name: '白エビ天丼', where: '魚津', desc: 'Tôm trắng Toyama — đặc sản #1, ngọt tự nhiên' },
        ],
        segments: [
          { from: 'HOTEL R9', to: '称名滝', km: 45, time: '50min', mode: 'car' },
          { from: '称名滝', to: 'ほたるいかミュージアム', km: 50, time: '50min', mode: 'car' },
          { from: 'ほたるいか', to: '魚津水族館', km: 10, time: '10min', mode: 'car' },
          { from: '魚津', to: 'HOTEL R9', km: 20, time: '25min', mode: 'car' },
        ],
        stops: [
          {
            id: 'b-shomyo',
            name: '称名滝 + ハンノキ滝',
            lat: 36.5733, lng: 137.4867,
            arrivalTime: '08:00',
            duration: 120,
            type: 'major',
            description: 'Hai thác đổ V-shape: 称名滝 (350m) + ハンノキ滝 (500m). Chỉ có mùa tuyết tan tháng 4-5! Sáng sớm nắng chiếu = cầu vồng tự nhiên. Đường bộ 30 phút paved hoàn toàn, đẩy được xe đẩy.',
            food: 'Kem sữa tươi tại レストハウス称名',
            tips: 'Đến trước 9h = ánh sáng + nước mạnh nhất. Mang áo mưa mỏng — nước bắn ra nhiều mét!',
            weather: '10-16°C · 🌤️ Mát, nắng sáng → cầu vồng',
          },
          {
            id: 'b-hotaruika',
            name: 'ほたるいかミュージアム',
            lat: 36.7632, lng: 137.3355,
            arrivalTime: '11:00',
            duration: 60,
            type: 'major',
            description: 'Phòng tối xem mực phát sáng xanh lam — chỉ có mùa 3-5月 tại Toyama Bay. Touch pool cho trẻ. Ăn trưa ngay tại quán bên cạnh.',
            food: 'Ăn trưa: ほたるいか tempura tươi nhất có thể',
            tips: 'Live display là highlight. Trẻ em rất thích phòng tối xem mực sáng!',
            weather: '15-20°C · 🌤️ Ven biển, gió mát',
          },
          {
            id: 'b-uozu',
            name: '魚津水族館 + ミラージュランド',
            lat: 36.7984, lng: 137.3882,
            arrivalTime: '12:30',
            duration: 120,
            type: 'major',
            description: 'Thủy cung cổ nhất Nhật Bản — nhỏ ấm cúng. Bên cạnh ミラージュランド với rides nhẹ nhìn ra biển. Trẻ chơi thoải mái.',
            food: '白エビ天丼 tại quán ven biển',
            tips: 'Xem show cá (giờ cố định). Rides ~300-400¥/lượt.',
            weather: '15-22°C · 🌤️ Ấm, gió biển',
          },
          {
            id: 'b-hotel-r9-d2',
            name: 'HOTEL R9 The Yard Kurobe',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '16:00',
            duration: 0,
            type: 'minor',
            description: 'Về hotel sớm, nghỉ ngơi thoải mái.',
            food: 'Tối: ます寿し + 白エビ sashimi',
            tips: 'Về sớm — trẻ không mệt, người lớn thư giãn.',
            weather: '14-20°C · 🌙 Mát mẻ',
          },
        ],
      },
      {
        dayNum: 3,
        title: 'Day 3 — Thứ Ba 5/5',
        subtitle: '宇奈月 → トロッコ 11:48 → ひみ番屋街ランチ → 雨晴海岸 Golden Hour → 富岩運河スタバ夜景 → Tokyo',
        specialties: [
          { emoji: '🍦', name: 'Kem onsen', where: '宇奈月', desc: 'Kem mềm mịn bán dọc phố onsen' },
          { emoji: '🍡', name: '温泉たまご', where: '宇奈月', desc: 'Trứng luộc suối nóng, lòng đào mềm' },
          { emoji: '🍣', name: 'ます寿し bento', where: 'SA đường về', desc: 'Sushi cá hồi ép — bento hoàn hảo trên xe' },
        ],
        segments: [
          { from: 'HOTEL R9 (checkout 10:00)', to: '宇奈月駅', km: 20, time: '20min', mode: 'car' },
          { from: '宇奈月 (11:48発)', to: '笹平 往復', km: 16, time: '2h10', mode: 'trolley' },
          { from: '宇奈月 (~14:00)', to: 'ひみ番屋街 (氷見)', km: 60, time: '1h', mode: 'car' },
          { from: 'ひみ番屋街', to: '雨晴海岸', km: 15, time: '15min', mode: 'car' },
          { from: '雨晴海岸', to: '富岩運河環水公園', km: 20, time: '30min', mode: 'car' },
          { from: '富岩運河', to: '向島 (Tokyo)', km: 400, time: '5h', mode: 'car' },
        ],
        stops: [
          {
            id: 'b-unazuki',
            name: '宇奈月温泉 散策',
            lat: 36.8173, lng: 137.5841,
            arrivalTime: '10:20',
            duration: 85,
            type: 'minor',
            description: 'Checkout hotel 10:00 → hành lý để trên xe → lái đến 宇奈月駅 (20 phút). Tản bộ phố onsen trước khi lên tàu. Ngâm chân ashiyu miễn phí. Mua snack.',
            food: 'Kem onsen · 温泉たまご · bánh mochi · onigiri cho lên tàu',
            tips: 'Checkout 10:00 → xe đến 宇奈月駅 10:20. Tàu Trolley lên 11:48 — đúng giờ ra ga!',
            weather: '14-20°C · 🌸 Dễ chịu',
          },
          {
            id: 'b-trolley',
            name: '黒部峡谷トロッコ (宇奈月〜笹平)',
            lat: 36.8150, lng: 137.5860,
            arrivalTime: '11:48',
            duration: 130,
            type: 'major',
            description: 'Tàu trolley hẻm V-shape Kurobe — hẻm núi sâu nhất Nhật Bản. 2026: đến 笹平 (5/3~5/9). Khứ hồi ~2h10. Về đến 宇奈月 khoảng 14:00.',
            food: 'Mua snack tại 宇奈月駅 trước khi lên tàu',
            tips: '⚠️ Vé 11:48 — ĐÚNG GIỜ, không trễ! Đặt vé từ 1/4 tại torokko-yoyaku.com. Chọn toa mở (普通客車). Ngồi bên PHẢI chiều đi.',
            weather: '14-20°C · 🌿 Hẻm núi mát mẻ, cảnh xanh',
          },
          {
            id: 'b-himi',
            name: 'ひみ番屋街 — 氷見漁港場外市場',
            lat: 36.8567, lng: 136.9870,
            arrivalTime: '15:00',
            duration: 90,
            type: 'major',
            description: '氷見漁港直送の海産物マーケット！白エビ天丼・氷見うどん・海鮮丼で遅めのランチ。子どもたちは広い港エリアを走り回れる。雨晴海岸まで車で15分。',
            food: '🍜 氷見うどん · 🦐 白エビ天丼 · 🐟 海鮮丼 · Omiyage: 氷見牛・海産物',
            tips: '子連れに最高のスポット。駐車場無料。雨晴海岸まで15分。',
            weather: '15-20°C · 🌊 港の海風',
          },
          {
            id: 'b-ameharashi',
            name: '雨晴海岸 (Ameharashi Coast)',
            lat: 36.7740, lng: 137.0240,
            arrivalTime: '17:00',
            duration: 100,
            type: 'major',
            description: '富山湾 + 立山連峰 + 赤いJR氷見線の聖地！日没18:41の1時間40分前に到着しゴールデンアワーをフルに楽しむ。',
            food: 'ひみ番屋街で買ったおやつ · 近くのカフェ',
            tips: '📸 17:00着でゴールデンアワーをフル確保。JR氷見線の時刻を事前確認 → 列車が来る瞬間にシャッター。駐車場無料。',
            weather: '14-18°C · 🌅 ゴールデンアワー → 日没18:41',
            images: [
              { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Ameharashi_Coast.jpg/640px-Ameharashi_Coast.jpg', alt: '雨晴海岸 富山湾 立山連峰' },
            ],
          },
          {
            id: 'b-kansui',
            name: '富岩運河環水公園 + 世界一美しいスタバ',
            lat: 36.6983, lng: 137.2113,
            arrivalTime: '19:30',
            duration: 75,
            type: 'major',
            description: '夜の富岩運河環水公園！天門橋のライトアップが水面に映り込む幻想的な夜景。',
            food: 'スターバックス コーヒー 富山環水公園店 (22:30まで営業)',
            tips: '📸 撮影ベスト: スタバを横から写す構図 + 天門橋 + 水面リフレクション。ライトアップ22:00まで。駐車場無料。',
            weather: '14-18°C · 🌃 夜景 — ライトアップ22時まで',
          },
          {
            id: 'b-return',
            name: 'Xuất phát về Tokyo',
            lat: 35.7180, lng: 139.8130,
            arrivalTime: '21:00',
            duration: 0,
            type: 'major',
            description: '北陸道 → 関越道で帰路。~5h。向島到着 2:00~2:30 AM。スタバで夜景を楽しんだ後、子どもたちは車内で熟睡。',
            food: '出発前にコンビニで夜食・飲み物 · SAでます寿しbento',
            tips: '21時出発はUターンラッシュ後 — 渋滞なし。SA休憩1〜2回。運転交代を忘れずに。',
            weather: '14°C → 18°C · 🌙 夜の北陸道 — 空いていて走りやすい',
          },
        ]
      },
    ],
  },


  C: {
    name: '五箇山 & 称名滝',
    color: '#5B6ABF',
    subtitle: 'Thác cao nhất Nhật + UNESCO village + Trolley — không cần vé Alpine, tiết kiệm',
    route: '五箇山 → 称名滝 → 魚津水族館 → トロッコ',
    highlights: [
      { icon: '💧', text: '称名滝 — thác cao nhất Nhật Bản (350m)' },
      { icon: '🏘️', text: '五箇山 UNESCO — yên tĩnh, ít đông' },
      { icon: '💰', text: 'Không cần vé Alpine Route — tiết kiệm ~¥55,000' },
    ],
    totalKm: 1210,
    routeGo: '上信越道 + 北陸道 (380km · 5h30) — cảnh núi→biển đẹp',
    routeReturn: '北陸道 → 関越道 (430km · 5h) — an toàn lái đêm, ít cua',
    routeOptions: [
      '✅ 上信越道 + 北陸道 — Ngắn nhất đến 五箇山. Cảnh núi→biển đẹp. (380km · 5h30)',
      '関越道 + 北陸道 via 長岡 — Dễ lái nhất, ít cua. Trẻ ít say. (430km · 6h)',
      '上信越道 xuyên Nagano — Cảnh núi đẹp nhất nhưng cua nhiều, trẻ dễ say. (360km · 5h30)',
    ],
    gallery: [
      // Thêm ảnh: { src: 'images/plan-c/ten-anh.jpg', caption: 'Mô tả', spot: 'Tên điểm đến' }
    ],
    days: [
      {
        dayNum: 1,
        title: 'Day 1 — Chủ Nhật 3/5',
        subtitle: '向島 → 五箇山 → HOTEL R9',
        specialties: [
          { emoji: '🧈', name: '五箇山豆腐', where: '五箇山', desc: 'Đậu hũ cứng nướng than, đậm đà — đặc sản UNESCO village' },
          { emoji: '🐟', name: '岩魚塩焼き', where: '五箇山', desc: 'Cá suối nướng muối thơm giòn, trẻ em thích' },
          { emoji: '🍜', name: '富山ブラックラーメン', where: 'Kurobe', desc: 'Ramen đen xì dầu đậm đặc — ăn tối tại Kurobe' },
        ],
        segments: [
          { from: '向島', to: '五箇山', km: 380, time: '5h30', mode: 'car' },
          { from: '五箇山', to: 'HOTEL R9', km: 110, time: '1h30', mode: 'car' },
        ],
        stops: [
          {
            id: 'e-d1-depart',
            name: 'Tập kết nhà anh Hà (向島)',
            lat: 35.7180, lng: 139.8130,
            arrivalTime: '06:00',
            duration: 0,
            type: 'minor',
            description: '3 xe tập kết tại 墨田区向島5-35-11. Đổ xăng trên Meiji-dori → 向島入口 → 首都高6号 → 関越道.',
            food: null,
            tips: '2 nhà đến trước 5:50. Cùng xuất phát 6:00.',
            weather: '18-24°C · 🌤️ Tokyo ấm',
          },
          {
            id: 'e-gokayama',
            name: '五箇山 相倉集落',
            lat: 36.4260, lng: 136.9355,
            arrivalTime: '12:00',
            duration: 90,
            type: 'major',
            description: 'Làng mái tranh gassho UNESCO yên tĩnh nhất. Trẻ em thích khám phá nhà 3 tầng. Ít đông hơn 白川郷 nhiều.',
            food: '五箇山豆腐 · 岩魚塩焼き',
            tips: 'Exit 北陸道 tại 砺波IC → 東海北陸道 → 五箇山IC. Ghé trên đường, không vòng.',
            weather: '13-18°C · 🌤️ Ấm, có thể mưa nhẹ',
          },
          {
            id: 'e-hotel-r9-d1',
            name: 'HOTEL R9 The Yard Kurobe',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '15:30',
            duration: 0,
            type: 'major',
            description: 'Check-in khách sạn. Nghỉ ngơi sau chặng đường dài.',
            food: 'Ăn tối tại nhà hàng quanh Kurobe',
            tips: 'Gần Kurobe IC, tiện di chuyển ngày hôm sau',
            weather: '14-20°C · 🌸 Mát mẻ buổi tối',
          },
        ],
      },
      {
        dayNum: 2,
        title: 'Day 2 — Thứ Hai 4/5',
        subtitle: '称名滝 → ほたるいかミュージアム → 魚津水族館',
        specialties: [
          { emoji: '🦑', name: 'ほたるいか (Hotaruika)', where: 'ほたるいかミュージアム', desc: 'Mực phát sáng live — sashimi hoặc tempura, chỉ có mùa này' },
          { emoji: '🦐', name: '白エビ天丼', where: '魚津', desc: 'Tôm trắng Toyama chiên giòn — đặc sản #1' },
          { emoji: '🍦', name: 'Kem sữa 立山', where: '称名滝 area', desc: 'Kem sữa tươi vùng núi — bán tại quầy gần bãi đỗ' },
        ],
        segments: [
          { from: 'HOTEL R9', to: '称名滝', km: 45, time: '50min', mode: 'car' },
          { from: '称名滝', to: 'ほたるいかミュージアム', km: 50, time: '50min', mode: 'car' },
          { from: 'ほたるいか', to: '魚津水族館', km: 10, time: '10min', mode: 'car' },
          { from: '魚津', to: 'HOTEL R9', km: 20, time: '25min', mode: 'car' },
        ],
        stops: [
          {
            id: 'e-shomyo',
            name: '称名滝 (Shomyo Falls)',
            lat: 36.5733, lng: 137.4867,
            arrivalTime: '08:00',
            duration: 120,
            type: 'major',
            description: 'Thác cao nhất Nhật Bản (350m)! Tháng 5 tuyết tan → thác ハンノキ bên cạnh (500m) cũng chảy → double waterfall cực kỳ ấn tượng. Nắng sáng chiếu trực tiếp, có cầu vồng.',
            food: null,
            tips: 'Đi sáng sớm = đẹp nhất. Đi bộ 30 phút từ bãi đỗ, đường paved. Mang giày thoải mái.',
            weather: '10-16°C · 🌤️ Mát, nắng sáng đẹp',
          },
          {
            id: 'e-hotaruika',
            name: 'ほたるいかミュージアム',
            lat: 36.7632, lng: 137.3355,
            arrivalTime: '11:00',
            duration: 60,
            type: 'major',
            description: 'Bảo tàng mực phát sáng — xem live hotaruika phát sáng trong phòng tối. Chỉ có mùa 3-5 mới có live display! Touch pool cho trẻ.',
            food: 'Ăn trưa: hotaruika tempura tại quán bên cạnh',
            tips: 'Live display là highlight — đừng bỏ lỡ! Trẻ em rất thích phòng tối xem mực sáng.',
            weather: '15-20°C · 🌤️ Ven biển, gió mát',
          },
          {
            id: 'e-uozu',
            name: '魚津水族館 + ミラージュランド',
            lat: 36.7984, lng: 137.3882,
            arrivalTime: '12:30',
            duration: 120,
            type: 'major',
            description: 'Thủy cung cổ nhất Nhật Bản — nhỏ nhưng ấm cúng. Bên cạnh là ミラージュランド (đu quay, rides nhẹ cho trẻ, view biển).',
            food: '白エビ天丼 tại quán ven biển',
            tips: 'Xem show cá (giờ cố định). ミラージュランド rides ~300-400¥/lượt. Trẻ chơi thoải mái.',
            weather: '15-22°C · 🌤️ Ấm, ven biển gió mát',
          },
          {
            id: 'e-hotel-r9-d2',
            name: 'HOTEL R9 The Yard Kurobe',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '15:30',
            duration: 0,
            type: 'minor',
            description: 'Về hotel sớm, nghỉ ngơi thoải mái.',
            food: 'Ăn tối: hải sản tươi Toyama',
            tips: 'Về sớm — trẻ không mệt, người lớn thư giãn.',
            weather: '14-20°C · 🌙 Mát mẻ',
          },
        ],
      },
      {
        dayNum: 3,
        title: 'Day 3 — Thứ Ba 5/5',
        subtitle: '宇奈月 → トロッコ 11:48 → ひみ番屋街ランチ → 雨晴海岸 Golden Hour → 富岩運河スタバ夜景 → Tokyo',
        specialties: [
          { emoji: '🍦', name: 'Kem onsen', where: '宇奈月', desc: 'Kem mềm mịn bán dọc phố onsen — trẻ em mê' },
          { emoji: '🍡', name: '温泉たまご', where: '宇奈月', desc: 'Trứng luộc suối nóng, vỏ mềm lòng đào — ăn kèm muối' },
          { emoji: '🍣', name: 'ます寿し bento', where: 'SA đường về', desc: 'Sushi cá hồi ép truyền thống Toyama — mua mang đi ăn trên xe' },
        ],
        segments: [
          { from: 'HOTEL R9 (checkout 10:00)', to: '宇奈月駅', km: 20, time: '20min', mode: 'car' },
          { from: '宇奈月 (11:48発)', to: '笹平 往復', km: 16, time: '2h10', mode: 'trolley' },
          { from: '宇奈月 (~14:00)', to: 'ひみ番屋街 (氷見)', km: 60, time: '1h', mode: 'car' },
          { from: 'ひみ番屋街', to: '雨晴海岸', km: 15, time: '15min', mode: 'car' },
          { from: '雨晴海岸', to: '富岩運河環水公園', km: 20, time: '30min', mode: 'car' },
          { from: '富岩運河', to: '向島 (Tokyo)', km: 400, time: '5h', mode: 'car' },
        ],
        stops: [
          {
            id: 'e-unazuki',
            name: '宇奈月温泉 散策',
            lat: 36.8173, lng: 137.5841,
            arrivalTime: '10:20',
            duration: 85,
            type: 'minor',
            description: 'Checkout hotel 10:00 → hành lý để trên xe → lái đến 宇奈月駅 (20 phút). Tản bộ phố onsen trước khi lên tàu. Ngâm chân ashiyu miễn phí. Mua snack ăn trên tàu.',
            food: 'Kem onsen · 温泉たまご · bánh mochi · onigiri cho lên tàu',
            tips: 'Checkout 10:00 → xe đến 宇奈月駅 10:20. Tàu Trolley lên 11:48 — đúng giờ ra ga, không trễ!',
            weather: '14-20°C · 🌸 Dễ chịu',
          },
          {
            id: 'e-trolley',
            name: '黒部峡谷トロッコ (宇奈月〜笹平)',
            lat: 36.8150, lng: 137.5860,
            arrivalTime: '11:48',
            duration: 130,
            type: 'major',
            description: 'Tàu trolley hẻm V-shape Kurobe — hẻm núi sâu nhất Nhật Bản. 2026: đến 笹平 (5/3~5/9). Khứ hồi ~2h10. Về đến 宇奈月 khoảng 14:00.',
            food: 'Mua snack tại 宇奈月駅 trước khi lên tàu',
            tips: '⚠️ Vé 11:48 — ĐÚNG GIỜ, không trễ! Đặt vé từ 1/4 tại torokko-yoyaku.com. Chọn toa mở (普通客車). Ngồi bên PHẢI chiều đi để ngắm sông tốt nhất.',
            weather: '14-20°C · 🌿 Hẻm núi mát mẻ, cảnh xanh',
          },
          {
            id: 'e-himi',
            name: 'ひみ番屋街 — 氷見漁港場外市場',
            lat: 36.8567, lng: 136.9870,
            arrivalTime: '15:00',
            duration: 90,
            type: 'major',
            description: '氷見漁港直送の海産物マーケット！白エビ天丼・氷見うどん・海鮮丼で遅めのランチ。子どもたちは広い港エリアを走り回れる。富山みやげの最終調達にも最適。雨晴海岸まで車で15分。',
            food: '🍜 氷見うどん · 🦐 白エビ天丼 · 🐟 海鮮丼 · Omiyage: 氷見牛・海産物',
            tips: '子連れに最高のスポット — 広い屋外エリアで自由に動ける。駐車場無料。トイレあり。雨晴海岸まで15分。',
            weather: '15-20°C · 🌊 港の海風',
          },
          {
            id: 'e-ameharashi',
            name: '雨晴海岸 (Ameharashi Coast)',
            lat: 36.7740, lng: 137.0240,
            arrivalTime: '17:00',
            duration: 100,
            type: 'major',
            description: '富山湾 + 立山連峰 + 赤いJR氷見線の聖地！日没18:41の1時間40分前に到着しゴールデンアワーをフルに楽しむ。17:00〜18:41まで山の色が刻々と変化する絶景タイム。3家族で記念撮影の絶好チャンス。',
            food: 'ひみ番屋街で買ったおやつ · 近くのカフェ',
            tips: '📸 17:00着でゴールデンアワーをフル確保。JR氷見線の時刻を事前確認 → 列車が来る瞬間にシャッター。北陸道 高岡ICへすぐ。駐車場無料。',
            weather: '14-18°C · 🌅 ゴールデンアワー → 日没18:41 → 山が黄金色に',
            images: [
              { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Ameharashi_Coast.jpg/640px-Ameharashi_Coast.jpg', alt: '雨晴海岸 富山湾 立山連峰' },
            ],
          },
          {
            id: 'e-kansui',
            name: '富岩運河環水公園 + 世界一美しいスタバ',
            lat: 36.6983, lng: 137.2113,
            arrivalTime: '19:30',
            duration: 75,
            type: 'major',
            description: '夜の富岩運河環水公園！天門橋のライトアップが水面に映り込む幻想的な夜景。「世界一美しいスタバ」で日没後の絶景を楽しむ。日没(18:41)から約50分後 — ライトアップが最高潮に。',
            food: 'スターバックス コーヒー 富山環水公園店 (22:30まで営業) · テラス席で夜風を感じながら',
            tips: '📸 撮影ベスト: スタバを横から写す構図 + 天門橋 + 水面リフレクション。ライトアップ22:00まで、天門橋展望塔21:00まで。駐車場無料。',
            weather: '14-18°C · 🌃 夜景 — ライトアップ22時まで',
          },
          {
            id: 'e-return',
            name: 'Xuất phát về Tokyo',
            lat: 35.7180, lng: 139.8130,
            arrivalTime: '21:00',
            duration: 0,
            type: 'major',
            description: '北陸道 → 関越道で帰路。~5h。向島到着 2:00~2:30 AM。スタバで夜景を楽しんだ後、子どもたちは車内で熟睡。GW Uターンラッシュのピーク後なので渋滞ほぼなし。',
            food: '出発前にコンビニで夜食・飲み物 · SAでます寿しbento',
            tips: '21時出発はUターンラッシュ後 — 渋滞なし。SA休憩1〜2回。運転交代を忘れずに。向島着は約2:30 AM。',
            weather: '14°C → 18°C · 🌙 夜の北陸道 — 空いていて走りやすい',
          },
        ]
      },
    ],
  },

  D: {
    name: '白馬 Alps Gondola + Trolley',
    color: '#C0392B',
    subtitle: 'Tulip 350万本 → Gondola đỉnh Alps tuyết trắng → Trolley → ほたるいか → 称名滝',
    route: 'チューリップフェア → 白馬村 → ゴンドラ → トロッコ → 称名滝',
    highlights: [
      { icon: '🌷', text: 'となみチューリップフェア 350万本 — trên đường đến 白馬' },
      { icon: '🏔️', text: '白馬 八方尾根ゴンドラ — lên 1,830m, Alps tuyết trắng' },
      { icon: '🚂', text: 'Trolley hẻm V-shape Kurobe + ほたるいか + 称名滝' },
    ],
    totalKm: 1510,
    routeGo: '関越道 → 北陸道 → 砺波IC → 黒部IC → 大町 → 白馬 (430km · 6h)',
    routeReturn: '北陸道 → 関越道 (430km · 5h) — an toàn lái đêm',
    routeOptions: [
      '✅ 関越道→北陸道→砺波(tulip)→黒部→大町→白馬 — Ghé tulip ON ROUTE! (430km · 6h)',
      '中央道→長野道→白馬→砺波(tulip detour) — Đi trước 白馬 rồi vòng qua 砺波. (400km+50km detour)',
      '関越道→上信越道→長野→白馬→糸魚川→砺波 — Dài nhưng cảnh đẹp. (460km · 7h)',
    ],
    gallery: [
      // Thêm ảnh: { src: 'images/plan-d/ten-anh.jpg', caption: 'Mô tả', spot: 'Tên điểm đến' }
    ],
    days: [
      {
        dayNum: 1,
        title: 'Day 1 — Chủ Nhật 3/5',
        subtitle: '向島 → チューリップフェア → 白馬村 → HOTEL R9',
        specialties: [
          { emoji: '🌷', name: 'チューリップソフト', where: '砺波 フェア', desc: 'Kem tulip ngọt dịu — ăn giữa 350万本 hoa' },
          { emoji: '🍖', name: 'Shinshu beef / soba', where: '白馬 village', desc: 'Bò Shinshu mềm thơm & soba kiều mạch Nagano' },
          { emoji: '🍺', name: 'Hakuba Brewing beer', where: '白馬 village', desc: 'Bia craft địa phương Hakuba — uống tối tại village' },
        ],
        segments: [
          { from: '向島', to: 'チューリップフェア (砺波)', km: 400, time: '5h30', mode: 'car' },
          { from: 'チューリップフェア', to: '白馬 (via 黒部→大町)', km: 130, time: '2h', mode: 'car' },
          { from: '白馬村', to: 'HOTEL R9 (via R148→糸魚川)', km: 100, time: '2h', mode: 'car' },
        ],
        stops: [
          {
            id: 'd-d1-depart',
            name: 'Tập kết nhà anh Hà (向島)',
            lat: 35.7180, lng: 139.8130,
            arrivalTime: '06:00',
            duration: 0,
            type: 'minor',
            description: '3 xe tập kết tại 墨田区向島5-35-11. Đổ xăng → 首都高 → 関越道 hướng Toyama.',
            food: null,
            tips: '2 nhà đến trước 5:50. Plan D đi 関越道→北陸道 (cùng hướng Plan B nhưng khác điểm đến).',
            weather: '18-24°C · 🌤️ Tokyo ấm',
          },
          {
            id: 'd-tulip',
            name: 'となみチューリップフェア 2026',
            lat: 36.6477, lng: 136.9635,
            arrivalTime: '10:30',
            duration: 90,
            type: 'major',
            description: '300品種350万本のチューリップ！「花の大谷」高さ4m×30m、水上花壇、チューリップタワー。5/5こどもの日は中学生以下無料！',
            food: 'チューリップソフトクリーム · 軽食各所',
            tips: '砺波ICから車で5分。GW混雑 — 10:30前着推奨。5/5中学生以下無料！Ghé 1h30 rồi đi 白馬.',
            weather: '14-20°C · 🌷 チューリップ満開',
          },
          {
            id: 'd-hakuba-village',
            name: '白馬村 散策 (tối)',
            lat: 36.6984, lng: 137.8617,
            arrivalTime: '14:30',
            duration: 120,
            type: 'major',
            description: 'Tản bộ Hakuba Village — quán cafe, shop đồ outdoor, không khí resort Âu châu giữa Nhật Bản. Dãy Alps tuyết trắng phía sau. Nghỉ chân thoải mái sau ngày đường.',
            food: 'Shinshu soba · thịt bò Shinshu nướng · bia craft Hakuba Brewing',
            tips: 'Nhiều quán có terrace nhìn ra núi Alps. Bữa tối tại izakaya village rất ngon.',
            weather: '10-18°C · 🏔️ Thung lũng Alps, trong lành',
          },
          {
            id: 'd-hotel-r9-d1',
            name: 'HOTEL R9 The Yard Kurobe',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '18:30',
            duration: 0,
            type: 'major',
            description: 'Check-in. Ngày 1 di chuyển nhiều — nghỉ ngơi sớm.',
            food: 'Ăn tối đã có tại 白馬村 hoặc quán gần hotel',
            tips: 'Route 白馬→R148→糸魚川→北陸道→黒部IC. Đường R148 đẹp, trẻ ngủ trên xe.',
            weather: '14-20°C · 🌙 Mát mẻ',
          },
        ],
      },
      {
        dayNum: 2,
        title: 'Day 2 — Thứ Hai 4/5',
        subtitle: '白馬ゴンドラ → トロッコ → 宇奈月温泉 → ほたるいか',
        specialties: [
          { emoji: '🍱', name: 'Gondola top lunch', where: '白馬 山頂', desc: 'Ăn trưa nhà hàng trên đỉnh núi 1,830m — view Alps 360 độ' },
          { emoji: '🍦', name: 'Kem onsen', where: '宇奈月', desc: 'Kem mềm mịn sau Trolley — phần thưởng xứng đáng' },
          { emoji: '🦑', name: 'ほたるいか sashimi', where: 'ほたるいかミュージアム', desc: 'Mực phát sáng Toyama Bay tươi nhất' },
        ],
        segments: [
          { from: 'HOTEL R9', to: '白馬 八方尾根', km: 70, time: '1h30', mode: 'car' },
          { from: '白馬', to: '宇奈月 (via R148)', km: 100, time: '2h', mode: 'car' },
          { from: 'トロッコ往復', to: '笹平', km: 16, time: '2h', mode: 'trolley' },
          { from: '宇奈月', to: 'ほたるいかミュージアム', km: 35, time: '40min', mode: 'car' },
          { from: 'ほたるいか', to: 'HOTEL R9', km: 20, time: '25min', mode: 'car' },
        ],
        stops: [
          {
            id: 'd-gondola',
            name: '白馬 八方尾根ゴンドラ',
            lat: 36.6983, lng: 137.8320,
            arrivalTime: '08:00',
            duration: 120,
            type: 'major',
            description: 'Gondola lên 1,830m — toàn cảnh dãy Alps Bắc phủ tuyết trắng + thung lũng xanh bên dưới. Cảm giác ở giữa tuyết mà không cần leo núi! Trẻ em phấn khích.',
            food: 'Ăn sáng tại hotel trước. Có nhà hàng tại đỉnh gondola.',
            tips: 'Lên gondola sáng sớm — ít người + ánh sáng đẹp. Mang áo gió dày — trên đỉnh lạnh hơn 10°C.',
            weather: '5-15°C · 🏔️ Mát, cần áo gió dày trên đỉnh',
          },
          {
            id: 'd-trolley',
            name: '黒部峡谷トロッコ (宇奈月〜笹平)',
            lat: 36.8150, lng: 137.5860,
            arrivalTime: '13:00',
            duration: 150,
            type: 'major',
            description: 'Hẻm V-shape sâu nhất Nhật Bản — vách đá dựng đứng, sông xanh ngọc bích. 2026: vận hành đến 笹平. Khứ hồi ~2h.',
            food: 'Bento mua tại ga hoặc ăn nhẹ trên tàu',
            tips: '⚠️ Plan D trolley vào ngày 4/5 — cần đặt vé riêng (khác vé ngày 5/5). Chọn toa mở (普通客車). Ngồi bên PHẢI chiều đi.',
            weather: '14-20°C · 🌿 Hẻm núi mát mẻ',
          },
          {
            id: 'd-unazuki',
            name: '宇奈月温泉 散策',
            lat: 36.8173, lng: 137.5841,
            arrivalTime: '15:30',
            duration: 60,
            type: 'minor',
            description: 'Tản bộ phố onsen, ngâm chân ashiyu miễn phí. Mua omiyage.',
            food: 'Kem onsen · 温泉たまご',
            tips: 'Nhiều ashiyu dọc phố. Trẻ em rất thích!',
            weather: '14-20°C · 🌸 Dễ chịu',
          },
          {
            id: 'd-hotaruika',
            name: 'ほたるいかミュージアム',
            lat: 36.7632, lng: 137.3355,
            arrivalTime: '17:00',
            duration: 75,
            type: 'major',
            description: 'Phòng tối xem mực xanh phát sáng — độc nhất vô nhị. Touch pool cho trẻ.',
            food: 'ほたるいか sashimi / tempura tươi',
            tips: 'Live display phòng tối là highlight. Đặt trước nếu được.',
            weather: '15-20°C · 🌙 Mát tối',
          },
          {
            id: 'd-hotel-r9-d2',
            name: 'HOTEL R9 The Yard Kurobe',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '18:45',
            duration: 0,
            type: 'minor',
            description: 'Về hotel. Ngày 2 dày nhất — nghỉ sớm!',
            food: 'Ăn tối đã có tại ほたるいかミュージアム hoặc konbini',
            tips: null,
            weather: '14-20°C · 🌙 Mát mẻ',
          },
        ],
      },
      {
        dayNum: 3,
        title: 'Day 3 — Thứ Ba 5/5',
        subtitle: '称名滝 → 魚津水族館 → ひみ番屋街 → 雨晴海岸 Golden Hour → 富岩運河スタバ夜景 → Tokyo',
        specialties: [
          { emoji: '🍦', name: 'Kem sữa 立山', where: '称名滝 area', desc: 'Kem tươi vùng núi — quầy gần bãi đỗ' },
          { emoji: '🦐', name: '白エビ天丼', where: '魚津', desc: 'Tôm trắng Toyama — ăn trưa tươi ngon' },
          { emoji: '🍣', name: 'ます寿し bento', where: 'SA đường về', desc: 'Sushi cá hồi ép — mua mang trên xe' },
        ],
        segments: [
          { from: 'HOTEL R9', to: '称名滝', km: 45, time: '50min', mode: 'car' },
          { from: '称名滝', to: '魚津水族館', km: 55, time: '55min', mode: 'car' },
          { from: '魚津', to: 'HOTEL R9', km: 20, time: '25min', mode: 'car' },
          { from: 'HOTEL R9', to: '向島 (Tokyo)', km: 430, time: '5h', mode: 'car' },
        ],
        stops: [
          {
            id: 'd-shomyo',
            name: '称名滝 + ハンノキ滝',
            lat: 36.5733, lng: 137.4867,
            arrivalTime: '08:00',
            duration: 90,
            type: 'major',
            description: '2 thác V-shape: 称名滝 (350m) + ハンノキ滝 (500m). Chỉ có mùa tuyết tan! Sáng sớm = cầu vồng tự nhiên ngay trước mặt. Đường paved 30 phút từ bãi đỗ.',
            food: 'Kem sữa tươi tại レストハウス称名',
            tips: 'Đến sớm nhất — tháng 5 nước tuyết tan = thác cực mạnh. Mang áo mưa mỏng!',
            weather: '10-16°C · 🌤️ Mát, nắng sáng → cầu vồng',
          },
          {
            id: 'd-uozu',
            name: '魚津水族館 + ミラージュランド',
            lat: 36.7984, lng: 137.3882,
            arrivalTime: '10:30',
            duration: 90,
            type: 'major',
            description: 'Thủy cung cổ nhất Nhật Bản + rides nhẹ nhìn biển Toyama. Ngày cuối nhẹ nhàng cho trẻ.',
            food: '白エビ天丼 tại quán ven biển — ăn trưa',
            tips: 'Xem show cá (giờ cố định). Rides nhẹ cho bé.',
            weather: '15-22°C · 🌤️ Ấm, ven biển',
          },
          {
            id: 'd-himi',
            name: 'ひみ番屋街 — 氷見漁港場外市場',
            lat: 36.8567, lng: 136.9870,
            arrivalTime: '13:30',
            duration: 75,
            type: 'major',
            description: '氷見漁港直送の海産物マーケット！雰囲気のある漁港エリアで子どもたちが走り回れる。富山みやげの最終調達。雨晴海岸まで車で15分。',
            food: '🍜 氷見うどん · 🦐 白エビ天丼 · Omiyage: 氷見牛・海産物',
            tips: '子連れに最高のスポット。駐車場無料。雨晴海岸まで15分。',
            weather: '15-20°C · 🌊 港の海風',
          },
          {
            id: 'd-ameharashi',
            name: '雨晴海岸 (Ameharashi Coast)',
            lat: 36.7740, lng: 137.0240,
            arrivalTime: '17:00',
            duration: 100,
            type: 'major',
            description: '富山湾 + 立山連峰 + 赤いJR氷見線の聖地！日没18:41の1時間40分前に到着しゴールデンアワーをフルに楽しむ。',
            food: 'ひみ番屋街で買ったおやつ',
            tips: '📸 17:00着でゴールデンアワーをフル確保。JR氷見線の時刻を事前確認 → 列車が来る瞬間にシャッター。駐車場無料。',
            weather: '14-18°C · 🌅 ゴールデンアワー → 日没18:41',
            images: [
              { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Ameharashi_Coast.jpg/640px-Ameharashi_Coast.jpg', alt: '雨晴海岸 富山湾 立山連峰' },
            ],
          },
          {
            id: 'd-kansui',
            name: '富岩運河環水公園 + 世界一美しいスタバ',
            lat: 36.6983, lng: 137.2113,
            arrivalTime: '19:30',
            duration: 75,
            type: 'major',
            description: '夜の富岩運河環水公園！天門橋のライトアップが水面に映り込む幻想的な夜景。「世界一美しいスタバ」で日没後の絶景を楽しむ。',
            food: 'スターバックス コーヒー 富山環水公園店 (22:30まで営業)',
            tips: '📸 撮影ベスト: スタバを横から写す構図 + 天門橋 + 水面リフレクション。ライトアップ22:00まで。駐車場無料。',
            weather: '14-18°C · 🌃 夜景 — ライトアップ22時まで',
          },
          {
            id: 'd-return',
            name: 'Xuất phát về Tokyo',
            lat: 35.7180, lng: 139.8130,
            arrivalTime: '21:00',
            duration: 0,
            type: 'major',
            description: '北陸道 → 関越道で帰路。~5h。向島到着 2:00~2:30 AM。スタバで夜景を楽しんだ後、子どもたちは車内で熟睡。',
            food: '出発前にコンビニで夜食・飲み物 · SAでます寿しbento',
            tips: '21時出発はUターンラッシュ後 — 渋滞なし。SA休憩1〜2回。運転交代を忘れずに。',
            weather: '14°C → 18°C · 🌙 夜の北陸道 — 空いていて走りやすい',
          },
        ],
      },
    ],
  },

  C: {
    name: '五箇山 & 称名滝',
    color: '#5B6ABF',
    subtitle: 'Thác cao nhất Nhật + UNESCO village + Trolley — không cần vé Alpine, tiết kiệm',
    route: '五箇山 → 称名滝 → 魚津水族館 → トロッコ',
    highlights: [
      { icon: '💧', text: '称名滝 — thác cao nhất Nhật Bản (350m)' },
      { icon: '🏘️', text: '五箇山 UNESCO — yên tĩnh, ít đông' },
      { icon: '💰', text: 'Không cần vé Alpine Route — tiết kiệm ~¥55,000' },
    ],
    totalKm: 1210,
    routeGo: '上信越道 + 北陸道 (380km · 5h30) — cảnh núi→biển đẹp',
    routeReturn: '北陸道 → 関越道 (430km · 5h) — an toàn lái đêm, ít cua',
    routeOptions: [
      '✅ 上信越道 + 北陸道 — Ngắn nhất đến 五箇山. Cảnh núi→biển đẹp. (380km · 5h30)',
      '関越道 + 北陸道 via 長岡 — Dễ lái nhất, ít cua. Trẻ ít say. (430km · 6h)',
      '上信越道 xuyên Nagano — Cảnh núi đẹp nhất nhưng cua nhiều, trẻ dễ say. (360km · 5h30)',
    ],
    gallery: [
      // Thêm ảnh: { src: 'images/plan-c/ten-anh.jpg', caption: 'Mô tả', spot: 'Tên điểm đến' }
    ],
    days: [
      {
        dayNum: 1,
        title: 'Day 1 — Chủ Nhật 3/5',
        subtitle: '向島 → 五箇山 → HOTEL R9',
        specialties: [
          { emoji: '🧈', name: '五箇山豆腐', where: '五箇山', desc: 'Đậu hũ cứng nướng than, đậm đà — đặc sản UNESCO village' },
          { emoji: '🐟', name: '岩魚塩焼き', where: '五箇山', desc: 'Cá suối nướng muối thơm giòn, trẻ em thích' },
          { emoji: '🍜', name: '富山ブラックラーメン', where: 'Kurobe', desc: 'Ramen đen xì dầu đậm đặc — ăn tối tại Kurobe' },
        ],
        segments: [
          { from: '向島', to: '五箇山', km: 380, time: '5h30', mode: 'car' },
          { from: '五箇山', to: 'HOTEL R9', km: 110, time: '1h30', mode: 'car' },
        ],
        stops: [
          {
            id: 'e-d1-depart',
            name: 'Tập kết nhà anh Hà (向島)',
            lat: 35.7180, lng: 139.8130,
            arrivalTime: '06:00',
            duration: 0,
            type: 'minor',
            description: '3 xe tập kết tại 墨田区向島5-35-11. Đổ xăng trên Meiji-dori → 向島入口 → 首都高6号 → 関越道.',
            food: null,
            tips: '2 nhà đến trước 5:50. Cùng xuất phát 6:00.',
            weather: '18-24°C · 🌤️ Tokyo ấm',
          },
          {
            id: 'e-gokayama',
            name: '五箇山 相倉集落',
            lat: 36.4260, lng: 136.9355,
            arrivalTime: '12:00',
            duration: 90,
            type: 'major',
            description: 'Làng mái tranh gassho UNESCO yên tĩnh nhất. Trẻ em thích khám phá nhà 3 tầng. Ít đông hơn 白川郷 nhiều.',
            food: '五箇山豆腐 · 岩魚塩焼き',
            tips: 'Exit 北陸道 tại 砺波IC → 東海北陸道 → 五箇山IC. Ghé trên đường, không vòng.',
            weather: '13-18°C · 🌤️ Ấm, có thể mưa nhẹ',
          },
          {
            id: 'e-hotel-r9-d1',
            name: 'HOTEL R9 The Yard Kurobe',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '15:30',
            duration: 0,
            type: 'major',
            description: 'Check-in khách sạn. Nghỉ ngơi sau chặng đường dài.',
            food: 'Ăn tối tại nhà hàng quanh Kurobe',
            tips: 'Gần Kurobe IC, tiện di chuyển ngày hôm sau',
            weather: '14-20°C · 🌸 Mát mẻ buổi tối',
          },
        ],
      },
      {
        dayNum: 2,
        title: 'Day 2 — Thứ Hai 4/5',
        subtitle: '称名滝 → ほたるいかミュージアム → 魚津水族館',
        specialties: [
          { emoji: '🦑', name: 'ほたるいか (Hotaruika)', where: 'ほたるいかミュージアム', desc: 'Mực phát sáng live — sashimi hoặc tempura, chỉ có mùa này' },
          { emoji: '🦐', name: '白エビ天丼', where: '魚津', desc: 'Tôm trắng Toyama chiên giòn — đặc sản #1' },
          { emoji: '🍦', name: 'Kem sữa 立山', where: '称名滝 area', desc: 'Kem sữa tươi vùng núi — bán tại quầy gần bãi đỗ' },
        ],
        segments: [
          { from: 'HOTEL R9', to: '称名滝', km: 45, time: '50min', mode: 'car' },
          { from: '称名滝', to: 'ほたるいかミュージアム', km: 50, time: '50min', mode: 'car' },
          { from: 'ほたるいか', to: '魚津水族館', km: 10, time: '10min', mode: 'car' },
          { from: '魚津', to: 'HOTEL R9', km: 20, time: '25min', mode: 'car' },
        ],
        stops: [
          {
            id: 'e-shomyo',
            name: '称名滝 (Shomyo Falls)',
            lat: 36.5733, lng: 137.4867,
            arrivalTime: '08:00',
            duration: 120,
            type: 'major',
            description: 'Thác cao nhất Nhật Bản (350m)! Tháng 5 tuyết tan → thác ハンノキ bên cạnh (500m) cũng chảy → double waterfall cực kỳ ấn tượng. Nắng sáng chiếu trực tiếp, có cầu vồng.',
            food: null,
            tips: 'Đi sáng sớm = đẹp nhất. Đi bộ 30 phút từ bãi đỗ, đường paved. Mang giày thoải mái.',
            weather: '10-16°C · 🌤️ Mát, nắng sáng đẹp',
          },
          {
            id: 'e-hotaruika',
            name: 'ほたるいかミュージアム',
            lat: 36.7632, lng: 137.3355,
            arrivalTime: '11:00',
            duration: 60,
            type: 'major',
            description: 'Bảo tàng mực phát sáng — xem live hotaruika phát sáng trong phòng tối. Chỉ có mùa 3-5 mới có live display! Touch pool cho trẻ.',
            food: 'Ăn trưa: hotaruika tempura tại quán bên cạnh',
            tips: 'Live display là highlight — đừng bỏ lỡ! Trẻ em rất thích phòng tối xem mực sáng.',
            weather: '15-20°C · 🌤️ Ven biển, gió mát',
          },
          {
            id: 'e-uozu',
            name: '魚津水族館 + ミラージュランド',
            lat: 36.7984, lng: 137.3882,
            arrivalTime: '12:30',
            duration: 120,
            type: 'major',
            description: 'Thủy cung cổ nhất Nhật Bản — nhỏ nhưng ấm cúng. Bên cạnh là ミラージュランド (đu quay, rides nhẹ cho trẻ, view biển).',
            food: '白エビ天丼 tại quán ven biển',
            tips: 'Xem show cá (giờ cố định). ミラージュランド rides ~300-400¥/lượt. Trẻ chơi thoải mái.',
            weather: '15-22°C · 🌤️ Ấm, ven biển gió mát',
          },
          {
            id: 'e-hotel-r9-d2',
            name: 'HOTEL R9 The Yard Kurobe',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '15:30',
            duration: 0,
            type: 'minor',
            description: 'Về hotel sớm, nghỉ ngơi thoải mái.',
            food: 'Ăn tối: hải sản tươi Toyama',
            tips: 'Về sớm — trẻ không mệt, người lớn thư giãn.',
            weather: '14-20°C · 🌙 Mát mẻ',
          },
        ],
      },
      {
        dayNum: 3,
        title: 'Day 3 — Thứ Ba 5/5',
        subtitle: '宇奈月 → トロッコ 11:48 → ひみ番屋街ランチ → 雨晴海岸 Golden Hour → 富岩運河スタバ夜景 → Tokyo',
        specialties: [
          { emoji: '🍦', name: 'Kem onsen', where: '宇奈月', desc: 'Kem mềm mịn bán dọc phố onsen — trẻ em mê' },
          { emoji: '🍡', name: '温泉たまご', where: '宇奈月', desc: 'Trứng luộc suối nóng, vỏ mềm lòng đào — ăn kèm muối' },
          { emoji: '🍣', name: 'ます寿し bento', where: 'SA đường về', desc: 'Sushi cá hồi ép truyền thống Toyama — mua mang đi ăn trên xe' },
        ],
        segments: [
          { from: 'HOTEL R9 (checkout 10:00)', to: '宇奈月駅', km: 20, time: '20min', mode: 'car' },
          { from: '宇奈月 (11:48発)', to: '笹平 往復', km: 16, time: '2h10', mode: 'trolley' },
          { from: '宇奈月 (~14:00)', to: 'ひみ番屋街 (氷見)', km: 60, time: '1h', mode: 'car' },
          { from: 'ひみ番屋街', to: '雨晴海岸', km: 15, time: '15min', mode: 'car' },
          { from: '雨晴海岸', to: '富岩運河環水公園', km: 20, time: '30min', mode: 'car' },
          { from: '富岩運河', to: '向島 (Tokyo)', km: 400, time: '5h', mode: 'car' },
        ],
        stops: [
          {
            id: 'e-unazuki',
            name: '宇奈月温泉 散策',
            lat: 36.8173, lng: 137.5841,
            arrivalTime: '10:20',
            duration: 85,
            type: 'minor',
            description: 'Checkout hotel 10:00 → hành lý để trên xe → lái đến 宇奈月駅 (20 phút). Tản bộ phố onsen trước khi lên tàu. Ngâm chân ashiyu miễn phí. Mua snack ăn trên tàu.',
            food: 'Kem onsen · 温泉たまご · bánh mochi · onigiri cho lên tàu',
            tips: 'Checkout 10:00 → xe đến 宇奈月駅 10:20. Tàu Trolley lên 11:48 — đúng giờ ra ga, không trễ!',
            weather: '14-20°C · 🌸 Dễ chịu',
          },
          {
            id: 'e-trolley',
            name: '黒部峡谷トロッコ (宇奈月〜笹平)',
            lat: 36.8150, lng: 137.5860,
            arrivalTime: '11:48',
            duration: 130,
            type: 'major',
            description: 'Tàu trolley hẻm V-shape Kurobe — hẻm núi sâu nhất Nhật Bản. 2026: đến 笹平 (5/3~5/9). Khứ hồi ~2h10. Về đến 宇奈月 khoảng 14:00.',
            food: 'Mua snack tại 宇奈月駅 trước khi lên tàu',
            tips: '⚠️ Vé 11:48 — ĐÚNG GIỜ, không trễ! Đặt vé từ 1/4 tại torokko-yoyaku.com. Chọn toa mở (普通客車). Ngồi bên PHẢI chiều đi để ngắm sông tốt nhất.',
            weather: '14-20°C · 🌿 Hẻm núi mát mẻ, cảnh xanh',
          },
          {
            id: 'e-himi',
            name: 'ひみ番屋街 — 氷見漁港場外市場',
            lat: 36.8567, lng: 136.9870,
            arrivalTime: '15:00',
            duration: 90,
            type: 'major',
            description: '氷見漁港直送の海産物マーケット！白エビ天丼・氷見うどん・海鮮丼で遅めのランチ。子どもたちは広い港エリアを走り回れる。富山みやげの最終調達にも最適。雨晴海岸まで車で15分。',
            food: '🍜 氷見うどん · 🦐 白エビ天丼 · 🐟 海鮮丼 · Omiyage: 氷見牛・海産物',
            tips: '子連れに最高のスポット — 広い屋外エリアで自由に動ける。駐車場無料。トイレあり。雨晴海岸まで15分。',
            weather: '15-20°C · 🌊 港の海風',
          },
          {
            id: 'e-ameharashi',
            name: '雨晴海岸 (Ameharashi Coast)',
            lat: 36.7740, lng: 137.0240,
            arrivalTime: '17:00',
            duration: 100,
            type: 'major',
            description: '富山湾 + 立山連峰 + 赤いJR氷見線の聖地！日没18:41の1時間40分前に到着しゴールデンアワーをフルに楽しむ。17:00〜18:41まで山の色が刻々と変化する絶景タイム。3家族で記念撮影の絶好チャンス。',
            food: 'ひみ番屋街で買ったおやつ · 近くのカフェ',
            tips: '📸 17:00着でゴールデンアワーをフル確保。JR氷見線の時刻を事前確認 → 列車が来る瞬間にシャッター。北陸道 高岡ICへすぐ。駐車場無料。',
            weather: '14-18°C · 🌅 ゴールデンアワー → 日没18:41 → 山が黄金色に',
            images: [
              { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Ameharashi_Coast.jpg/640px-Ameharashi_Coast.jpg', alt: '雨晴海岸 富山湾 立山連峰' },
            ],
          },
          {
            id: 'e-kansui',
            name: '富岩運河環水公園 + 世界一美しいスタバ',
            lat: 36.6983, lng: 137.2113,
            arrivalTime: '19:30',
            duration: 75,
            type: 'major',
            description: '夜の富岩運河環水公園！天門橋のライトアップが水面に映り込む幻想的な夜景。「世界一美しいスタバ」で日没後の絶景を楽しむ。日没(18:41)から約50分後 — ライトアップが最高潮に。',
            food: 'スターバックス コーヒー 富山環水公園店 (22:30まで営業) · テラス席で夜風を感じながら',
            tips: '📸 撮影ベスト: スタバを横から写す構図 + 天門橋 + 水面リフレクション。ライトアップ22:00まで、天門橋展望塔21:00まで。駐車場無料。',
            weather: '14-18°C · 🌃 夜景 — ライトアップ22時まで',
          },
          {
            id: 'e-return',
            name: 'Xuất phát về Tokyo',
            lat: 35.7180, lng: 139.8130,
            arrivalTime: '21:00',
            duration: 0,
            type: 'major',
            description: '北陸道 → 関越道で帰路。~5h。向島到着 2:00~2:30 AM。スタバで夜景を楽しんだ後、子どもたちは車内で熟睡。GW Uターンラッシュのピーク後なので渋滞ほぼなし。',
            food: '出発前にコンビニで夜食・飲み物 · SAでます寿しbento',
            tips: '21時出発はUターンラッシュ後 — 渋滞なし。SA休憩1〜2回。運転交代を忘れずに。向島着は約2:30 AM。',
            weather: '14°C → 18°C · 🌙 夜の北陸道 — 空いていて走りやすい',
          },
        ]
      },
    ],
  },

  D: {
    name: '白馬 Alps Gondola + Trolley',
    color: '#C0392B',
    subtitle: 'Tulip 350万本 → Gondola đỉnh Alps tuyết trắng → Trolley → ほたるいか → 称名滝',
    route: 'チューリップフェア → 白馬村 → ゴンドラ → トロッコ → 称名滝',
    highlights: [
      { icon: '🌷', text: 'となみチューリップフェア 350万本 — trên đường đến 白馬' },
      { icon: '🏔️', text: '白馬 八方尾根ゴンドラ — lên 1,830m, Alps tuyết trắng' },
      { icon: '🚂', text: 'Trolley hẻm V-shape Kurobe + ほたるいか + 称名滝' },
    ],
    totalKm: 1510,
    routeGo: '関越道 → 北陸道 → 砺波IC → 黒部IC → 大町 → 白馬 (430km · 6h)',
    routeReturn: '北陸道 → 関越道 (430km · 5h) — an toàn lái đêm',
    routeOptions: [
      '✅ 関越道→北陸道→砺波(tulip)→黒部→大町→白馬 — Ghé tulip ON ROUTE! (430km · 6h)',
      '中央道→長野道→白馬→砺波(tulip detour) — Đi trước 白馬 rồi vòng qua 砺波. (400km+50km detour)',
      '関越道→上信越道→長野→白馬→糸魚川→砺波 — Dài nhưng cảnh đẹp. (460km · 7h)',
    ],
    gallery: [
      // Thêm ảnh: { src: 'images/plan-d/ten-anh.jpg', caption: 'Mô tả', spot: 'Tên điểm đến' }
    ],
    days: [
      {
        dayNum: 1,
        title: 'Day 1 — Chủ Nhật 3/5',
        subtitle: '向島 → チューリップフェア → 白馬村 → HOTEL R9',
        specialties: [
          { emoji: '🌷', name: 'チューリップソフト', where: '砺波 フェア', desc: 'Kem tulip ngọt dịu — ăn giữa 350万本 hoa' },
          { emoji: '🍖', name: 'Shinshu beef / soba', where: '白馬 village', desc: 'Bò Shinshu mềm thơm & soba kiều mạch Nagano' },
          { emoji: '🍺', name: 'Hakuba Brewing beer', where: '白馬 village', desc: 'Bia craft địa phương Hakuba — uống tối tại village' },
        ],
        segments: [
          { from: '向島', to: 'チューリップフェア (砺波)', km: 400, time: '5h30', mode: 'car' },
          { from: 'チューリップフェア', to: '白馬 (via 黒部→大町)', km: 130, time: '2h', mode: 'car' },
          { from: '白馬村', to: 'HOTEL R9 (via R148→糸魚川)', km: 100, time: '2h', mode: 'car' },
        ],
        stops: [
          {
            id: 'd-d1-depart',
            name: 'Tập kết nhà anh Hà (向島)',
            lat: 35.7180, lng: 139.8130,
            arrivalTime: '06:00',
            duration: 0,
            type: 'minor',
            description: '3 xe tập kết tại 墨田区向島5-35-11. Đổ xăng → 首都高 → 関越道 hướng Toyama.',
            food: null,
            tips: '2 nhà đến trước 5:50. Plan D đi 関越道→北陸道 (cùng hướng Plan B nhưng khác điểm đến).',
            weather: '18-24°C · 🌤️ Tokyo ấm',
          },
          {
            id: 'd-tulip',
            name: 'となみチューリップフェア 2026',
            lat: 36.6477, lng: 136.9635,
            arrivalTime: '10:30',
            duration: 90,
            type: 'major',
            description: '300品種350万本のチューリップ！「花の大谷」高さ4m×30m、水上花壇、チューリップタワー。5/5こどもの日は中学生以下無料！',
            food: 'チューリップソフトクリーム · 軽食各所',
            tips: '砺波ICから車で5分。GW混雑 — 10:30前着推奨。5/5中学生以下無料！Ghé 1h30 rồi đi 白馬.',
            weather: '14-20°C · 🌷 チューリップ満開',
          },
          {
            id: 'd-hakuba-village',
            name: '白馬村 散策 (tối)',
            lat: 36.6984, lng: 137.8617,
            arrivalTime: '14:30',
            duration: 120,
            type: 'major',
            description: 'Tản bộ Hakuba Village — quán cafe, shop đồ outdoor, không khí resort Âu châu giữa Nhật Bản. Dãy Alps tuyết trắng phía sau. Nghỉ chân thoải mái sau ngày đường.',
            food: 'Shinshu soba · thịt bò Shinshu nướng · bia craft Hakuba Brewing',
            tips: 'Nhiều quán có terrace nhìn ra núi Alps. Bữa tối tại izakaya village rất ngon.',
            weather: '10-18°C · 🏔️ Thung lũng Alps, trong lành',
          },
          {
            id: 'd-hotel-r9-d1',
            name: 'HOTEL R9 The Yard Kurobe',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '18:30',
            duration: 0,
            type: 'major',
            description: 'Check-in. Ngày 1 di chuyển nhiều — nghỉ ngơi sớm.',
            food: 'Ăn tối đã có tại 白馬村 hoặc quán gần hotel',
            tips: 'Route 白馬→R148→糸魚川→北陸道→黒部IC. Đường R148 đẹp, trẻ ngủ trên xe.',
            weather: '14-20°C · 🌙 Mát mẻ',
          },
        ],
      },
      {
        dayNum: 2,
        title: 'Day 2 — Thứ Hai 4/5',
        subtitle: '白馬ゴンドラ → トロッコ → 宇奈月温泉 → ほたるいか',
        specialties: [
          { emoji: '🍱', name: 'Gondola top lunch', where: '白馬 山頂', desc: 'Ăn trưa nhà hàng trên đỉnh núi 1,830m — view Alps 360 độ' },
          { emoji: '🍦', name: 'Kem onsen', where: '宇奈月', desc: 'Kem mềm mịn sau Trolley — phần thưởng xứng đáng' },
          { emoji: '🦑', name: 'ほたるいか sashimi', where: 'ほたるいかミュージアム', desc: 'Mực phát sáng Toyama Bay tươi nhất' },
        ],
        segments: [
          { from: 'HOTEL R9', to: '白馬 八方尾根', km: 70, time: '1h30', mode: 'car' },
          { from: '白馬', to: '宇奈月 (via R148)', km: 100, time: '2h', mode: 'car' },
          { from: 'トロッコ往復', to: '笹平', km: 16, time: '2h', mode: 'trolley' },
          { from: '宇奈月', to: 'ほたるいかミュージアム', km: 35, time: '40min', mode: 'car' },
          { from: 'ほたるいか', to: 'HOTEL R9', km: 20, time: '25min', mode: 'car' },
        ],
        stops: [
          {
            id: 'd-gondola',
            name: '白馬 八方尾根ゴンドラ',
            lat: 36.6983, lng: 137.8320,
            arrivalTime: '08:00',
            duration: 120,
            type: 'major',
            description: 'Gondola lên 1,830m — toàn cảnh dãy Alps Bắc phủ tuyết trắng + thung lũng xanh bên dưới. Cảm giác ở giữa tuyết mà không cần leo núi! Trẻ em phấn khích.',
            food: 'Ăn sáng tại hotel trước. Có nhà hàng tại đỉnh gondola.',
            tips: 'Lên gondola sáng sớm — ít người + ánh sáng đẹp. Mang áo gió dày — trên đỉnh lạnh hơn 10°C.',
            weather: '5-15°C · 🏔️ Mát, cần áo gió dày trên đỉnh',
          },
          {
            id: 'd-trolley',
            name: '黒部峡谷トロッコ (宇奈月〜笹平)',
            lat: 36.8150, lng: 137.5860,
            arrivalTime: '13:00',
            duration: 150,
            type: 'major',
            description: 'Hẻm V-shape sâu nhất Nhật Bản — vách đá dựng đứng, sông xanh ngọc bích. 2026: vận hành đến 笹平. Khứ hồi ~2h.',
            food: 'Bento mua tại ga hoặc ăn nhẹ trên tàu',
            tips: '⚠️ Plan D trolley vào ngày 4/5 — cần đặt vé riêng (khác vé ngày 5/5). Chọn toa mở (普通客車). Ngồi bên PHẢI chiều đi.',
            weather: '14-20°C · 🌿 Hẻm núi mát mẻ',
          },
          {
            id: 'd-unazuki',
            name: '宇奈月温泉 散策',
            lat: 36.8173, lng: 137.5841,
            arrivalTime: '15:30',
            duration: 60,
            type: 'minor',
            description: 'Tản bộ phố onsen, ngâm chân ashiyu miễn phí. Mua omiyage.',
            food: 'Kem onsen · 温泉たまご',
            tips: 'Nhiều ashiyu dọc phố. Trẻ em rất thích!',
            weather: '14-20°C · 🌸 Dễ chịu',
          },
          {
            id: 'd-hotaruika',
            name: 'ほたるいかミュージアム',
            lat: 36.7632, lng: 137.3355,
            arrivalTime: '17:00',
            duration: 75,
            type: 'major',
            description: 'Phòng tối xem mực xanh phát sáng — độc nhất vô nhị. Touch pool cho trẻ.',
            food: 'ほたるいか sashimi / tempura tươi',
            tips: 'Live display phòng tối là highlight. Đặt trước nếu được.',
            weather: '15-20°C · 🌙 Mát tối',
          },
          {
            id: 'd-hotel-r9-d2',
            name: 'HOTEL R9 The Yard Kurobe',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '18:45',
            duration: 0,
            type: 'minor',
            description: 'Về hotel. Ngày 2 dày nhất — nghỉ sớm!',
            food: 'Ăn tối đã có tại ほたるいかミュージアム hoặc konbini',
            tips: null,
            weather: '14-20°C · 🌙 Mát mẻ',
          },
        ],
      },
      {
        dayNum: 3,
        title: 'Day 3 — Thứ Ba 5/5',
        subtitle: '称名滝 → 魚津水族館 → ひみ番屋街 → 雨晴海岸 Golden Hour → 富岩運河スタバ夜景 → Tokyo',
        specialties: [
          { emoji: '🍦', name: 'Kem sữa 立山', where: '称名滝 area', desc: 'Kem tươi vùng núi — quầy gần bãi đỗ' },
          { emoji: '🦐', name: '白エビ天丼', where: '魚津', desc: 'Tôm trắng Toyama — ăn trưa tươi ngon' },
          { emoji: '🍣', name: 'ます寿し bento', where: 'SA đường về', desc: 'Sushi cá hồi ép — mua mang trên xe' },
        ],
        segments: [
          { from: 'HOTEL R9', to: '称名滝', km: 45, time: '50min', mode: 'car' },
          { from: '称名滝', to: '魚津水族館', km: 55, time: '55min', mode: 'car' },
          { from: '魚津', to: 'HOTEL R9', km: 20, time: '25min', mode: 'car' },
          { from: 'HOTEL R9', to: '向島 (Tokyo)', km: 430, time: '5h', mode: 'car' },
        ],
        stops: [
          {
            id: 'd-shomyo',
            name: '称名滝 + ハンノキ滝',
            lat: 36.5733, lng: 137.4867,
            arrivalTime: '08:00',
            duration: 90,
            type: 'major',
            description: '2 thác V-shape: 称名滝 (350m) + ハンノキ滝 (500m). Chỉ có mùa tuyết tan! Sáng sớm = cầu vồng tự nhiên ngay trước mặt. Đường paved 30 phút từ bãi đỗ.',
            food: 'Kem sữa tươi tại レストハウス称名',
            tips: 'Đến sớm nhất — tháng 5 nước tuyết tan = thác cực mạnh. Mang áo mưa mỏng!',
            weather: '10-16°C · 🌤️ Mát, nắng sáng → cầu vồng',
          },
          {
            id: 'd-uozu',
            name: '魚津水族館 + ミラージュランド',
            lat: 36.7984, lng: 137.3882,
            arrivalTime: '10:30',
            duration: 90,
            type: 'major',
            description: 'Thủy cung cổ nhất Nhật Bản + rides nhẹ nhìn biển Toyama. Ngày cuối nhẹ nhàng cho trẻ.',
            food: '白エビ天丼 tại quán ven biển — ăn trưa',
            tips: 'Xem show cá (giờ cố định). Rides nhẹ cho bé.',
            weather: '15-22°C · 🌤️ Ấm, ven biển',
          },
          {
            id: 'd-himi',
            name: 'ひみ番屋街 — 氷見漁港場外市場',
            lat: 36.8567, lng: 136.9870,
            arrivalTime: '13:30',
            duration: 75,
            type: 'major',
            description: '氷見漁港直送の海産物マーケット！雰囲気のある漁港エリアで子どもたちが走り回れる。富山みやげの最終調達。雨晴海岸まで車で15分。',
            food: '🍜 氷見うどん · 🦐 白エビ天丼 · Omiyage: 氷見牛・海産物',
            tips: '子連れに最高のスポット。駐車場無料。雨晴海岸まで15分。',
            weather: '15-20°C · 🌊 港の海風',
          },
          {
            id: 'd-ameharashi',
            name: '雨晴海岸 (Ameharashi Coast)',
            lat: 36.7740, lng: 137.0240,
            arrivalTime: '17:00',
            duration: 100,
            type: 'major',
            description: '富山湾 + 立山連峰 + 赤いJR氷見線の聖地！日没18:41の1時間40分前に到着しゴールデンアワーをフルに楽しむ。',
            food: 'ひみ番屋街で買ったおやつ',
            tips: '📸 17:00着でゴールデンアワーをフル確保。JR氷見線の時刻を事前確認 → 列車が来る瞬間にシャッター。駐車場無料。',
            weather: '14-18°C · 🌅 ゴールデンアワー → 日没18:41',
            images: [
              { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Ameharashi_Coast.jpg/640px-Ameharashi_Coast.jpg', alt: '雨晴海岸 富山湾 立山連峰' },
            ],
          },
          {
            id: 'd-kansui',
            name: '富岩運河環水公園 + 世界一美しいスタバ',
            lat: 36.6983, lng: 137.2113,
            arrivalTime: '19:30',
            duration: 75,
            type: 'major',
            description: '夜の富岩運河環水公園！天門橋のライトアップが水面に映り込む幻想的な夜景。「世界一美しいスタバ」で日没後の絶景を楽しむ。',
            food: 'スターバックス コーヒー 富山環水公園店 (22:30まで営業)',
            tips: '📸 撮影ベスト: スタバを横から写す構図 + 天門橋 + 水面リフレクション。ライトアップ22:00まで。駐車場無料。',
            weather: '14-18°C · 🌃 夜景 — ライトアップ22時まで',
          },
          {
            id: 'd-return',
            name: 'Xuất phát về Tokyo',
            lat: 35.7180, lng: 139.8130,
            arrivalTime: '21:00',
            duration: 0,
            type: 'major',
            description: '北陸道 → 関越道で帰路。~5h。向島到着 2:00~2:30 AM。スタバで夜景を楽しんだ後、子どもたちは車内で熟睡。',
            food: '出発前にコンビニで夜食・飲み物 · SAでます寿しbento',
            tips: '21時出発はUターンラッシュ後 — 渋滞なし。SA休憩1〜2回。運転交代を忘れずに。',
            weather: '14°C → 18°C · 🌙 夜の北陸道 — 空いていて走りやすい',
          },
        ],
      },
    ],
  },

};

// ===== COMPARISON DATA =====
const COMPARISON = [
  { label: 'Tulip 350万本', A: { text: 'Có', type: 'yes' }, B: { text: 'Có', type: 'yes' }, C: { text: 'Có', type: 'yes' }, D: { text: 'Không', type: 'no' } },
  { label: 'Trolley hẻm núi', A: { text: 'Có', type: 'yes' }, B: { text: 'Có', type: 'yes' }, C: { text: 'Có', type: 'yes' }, D: { text: 'Có', type: 'yes' } },
  { label: '称名滝 đôi thác', A: { text: 'Có', type: 'yes' }, B: { text: 'Có', type: 'yes' }, C: { text: 'Có', type: 'yes' }, D: { text: 'Có', type: 'yes' } },
  { label: 'ほたるいか mực sáng', A: { text: 'Có', type: 'yes' }, B: { text: 'Có', type: 'yes' }, C: { text: 'Có', type: 'yes' }, D: { text: 'Có', type: 'yes' } },
  { label: '蓼科高原+ビーナスライン', A: { text: 'Có', type: 'yes' }, B: { text: 'Không', type: 'no' }, C: { text: 'Không', type: 'no' }, D: { text: 'Không', type: 'no' } },
  { label: '白馬 Alps gondola', A: { text: 'Không', type: 'no' }, B: { text: 'Không', type: 'no' }, C: { text: 'Không', type: 'no' }, D: { text: 'Có', type: 'yes' } },
  { label: 'Cần vé Alpine', A: { text: 'Không', type: 'yes' }, B: { text: 'Không', type: 'yes' }, C: { text: 'Không', type: 'yes' }, D: { text: 'Không', type: 'yes' } },
  { label: 'Độ vất vả', A: { text: '🔥🔥', type: 'neutral' }, B: { text: '🔥🔥', type: 'neutral' }, C: { text: '🔥🔥', type: 'neutral' }, D: { text: '🔥🔥', type: 'neutral' } },
  { label: 'Bé < 4 tuổi', A: { text: 'Tốt', type: 'yes' }, B: { text: 'Tốt', type: 'yes' }, C: { text: 'Tốt', type: 'yes' }, D: { text: 'Tốt', type: 'yes' } },
  { label: 'Tổng km', A: { text: '~1,330km', type: 'neutral' }, B: { text: '~1,210km', type: 'neutral' }, C: { text: '~1,210km', type: 'neutral' }, D: { text: '~1,510km', type: 'neutral' } },
  { label: 'Điểm đặc biệt', A: { text: '蓼科+花桃+白馬Alps', type: 'neutral' }, B: { text: '五箇山+tulip', type: 'neutral' }, C: { text: '五箇山+称名滝', type: 'neutral' }, D: { text: '白馬 gondola+tulip', type: 'neutral' } },
];

// ===== CHECKLIST =====
const CHECKLIST = [
  { id: 'trolley-ticket', text: '🚂 Vé Trolley 11:48 ngày 5/5 — ĐẶT TRƯỚC từ 1/4 tại torokko-yoyaku.com! GW bán hết ngay!', critical: true },
  { id: 'hanamomo-check', text: '🌸 Plan A: Gọi xác nhận hoa 花桃の里 trước khi đi — 📞 0265-48-5750 (24h). 5/3 có thể đã qua đỉnh.', critical: false },
  { id: 'freezing-road', text: '⚠️ Plan A: Hỏi chủ pension về tình trạng đường sáng sớm — ビーナスライン 1,400m có thể đóng băng tháng 5. Xuất phát sau 9:00 khi nắng lên là an toàn nhất.', critical: true },
  { id: 'tulip-ticket', text: '🌷 チューリップフェア — Plan A, B (không cần vé trước). 5/5 trẻ em miễn phí!', critical: false },
  { id: 'himi-line', text: '📸 Xem trước giờ JR氷見線 tại 雨晴海岸 — bắt đúng khoảnh khắc tàu đỏ + núi tuyết = ảnh đỉnh!', critical: false },
  { id: 'windbreaker', text: '🧥 Áo gió dày: Plan A (ロープウェイ 2,237m lạnh hơn 10°C), Plan D (gondola 白馬 1,830m)', critical: true },
  { id: 'rain-gear', text: '🌧️ Áo mưa mỏng (nước bắn từ 称名滝) — Plan A, B, C, D', critical: false },
  { id: 'sunscreen', text: '☀️ Kem chống nắng (UV mạnh trên cao nguyên và ven biển)', critical: false },
  { id: 'snacks', text: '🍡 Đồ ăn nhẹ cho trẻ em — đặc biệt chặng xe dài Tokyo→Toyama', critical: false },
  { id: 'charger', text: '🔋 Sạc dự phòng điện thoại (chụp ảnh cả ngày hao pin nhanh)', critical: false },
  { id: 'cash', text: '💴 Tiền mặt — nhiều nơi không nhận card: 花桃の里 bãi đỗ, SA nông thôn, omiyage nhỏ', critical: true },
  { id: 'motion-sick', text: '💊 Thuốc say xe cho trẻ — ビーナスライン và đường núi R148 nhiều cua', critical: false },
  { id: 'layers', text: '👕 Quần áo nhiều lớp — chênh lệch nhiệt độ lớn: 蓼科 8°C → Toyama 22°C trong 1 ngày', critical: true },
  { id: 'blanket', text: '🛏️ Chăn mỏng cho trẻ ngủ xe (về đêm 21:00→2:30 AM)', critical: false },
];

// ===== ESSENTIALS: LINKS =====
const USEFUL_LINKS = [
  { icon: '🚂', name: 'Kurobe Trolley — Đặt vé', desc: 'Cá nhân đặt từ 1/4/2026!', url: 'https://www.torokko-yoyaku.com/' },
  { icon: '🌷', name: 'となみチューリップフェア', desc: '22/4~5/5. 5/5 trẻ em free!', url: 'https://fair.tulipfair.or.jp/' },
  { icon: '🏨', name: 'HOTEL R9 The Yard Kurobe', desc: 'Khách sạn đã chốt — 2 đêm', url: 'https://hotelr9.jp/' },
  { icon: '🌦️', name: 'Dự báo thời tiết Toyama', desc: 'Kiểm tra trước khi đi', url: 'https://weather.yahoo.co.jp/weather/jp/16/' },
  { icon: '📱', name: 'NAVITIME — Navigation', desc: 'App chỉ đường Nhật Bản', url: 'https://www.navitime.co.jp/' },
  { icon: '🚗', name: 'NEXCO — Tắc đường GW', desc: 'Check tắc đường real-time', url: 'https://www.drivetraffic.jp/' },
];

// ===== ESSENTIALS: FOOD GUIDE =====
const FOOD_GUIDE = [
  { emoji: '🦐', name: '白エビ (Shiro Ebi)', desc: 'Tôm trắng Toyama — đặc sản #1. Tempura hoặc sashimi.' },
  { emoji: '🍣', name: 'ます寿し (Masu Sushi)', desc: 'Sushi cá hồi ép truyền thống. Mua bento mang đi tuyệt vời.' },
  { emoji: '🌷', name: 'チューリップソフト', desc: 'Kem tulip ngọt dịu — đặc sản hội chợ となみ. Chụp ảnh cực đẹp!' },
  { emoji: '🍲', name: '五箇山豆腐', desc: 'Đậu hũ Gokayama cứng, nướng than — vị đậm đà.' },
  { emoji: '🐟', name: '岩魚塩焼き', desc: 'Cá suối nướng muối. Thơm, giòn, trẻ em thích.' },
  { emoji: '🍜', name: '富山ブラックラーメン', desc: 'Ramen đen Toyama — nước dùng xì dầu đậm đặc.' },
  { emoji: '🦑', name: 'ほたるいか (Hotaruika)', desc: 'Mực phát sáng Toyama Bay — mùa 3-5月. Sashimi hoặc boiled.' },
];

// ===== WEATHER DATA (static) =====
const WEATHER = [
  { location: '黒部峡谷', temp: '14 ~ 20°C', icon: '🌿', note: 'Hẻm núi mát mẻ' },
  { location: '富山 / 魚津', temp: '15 ~ 22°C', icon: '🌤️', note: 'Ấm, mưa nhẹ' },
  { location: '松本', temp: '10 ~ 20°C', icon: '🌤️', note: 'Mát buổi sáng' },
  { location: '五箇山', temp: '13 ~ 18°C', icon: '🌤️', note: 'Ấm, có thể mưa' },
  { location: '砺波 (チューリップフェア)', temp: '14 ~ 20°C', icon: '🌷', note: 'Ấm áp, thích hợp ngắm hoa' },
  { location: '白馬 Alps', temp: '8 ~ 20°C', icon: '🏔️', note: 'Thung lũng Alps, đêm lạnh' },
  { location: '蓼科高原 (1,400m)', temp: '8 ~ 18°C', icon: '🏔️', note: 'Mát trong lành, tháng 5 sáng sớm lạnh' },
];
