// ===== PLAN DATA =====
// Tập kết: 墨田区向島5-35-11 (nhà anh Hà)
// Khách sạn: HOTEL R9 The Yard Kurobe (2 đêm)
// Day 1 & 2: kết thúc tại hotel | Day 3: hotel → Tokyo tối

const PLANS = {
  A: {
    name: '蓼科高原 & Alps Drive',
    color: '#2E4A6B',
    subtitle: '北八ヶ岳ロープウェイ + 白樺湖 + 1泊Nagano + 松本城 + 大出公園 + tulip + 称名滝 + ほたるいか + Trolley',
    route: '北八ヶ岳 → 白樺湖 → 松本城 → 大出公園 → チューリップフェア → 称名滝 → ほたるいか → トロッコ',
    highlights: [
      { icon: '🏔️', text: '北八ヶ岳ロープウェイ — gondola 2,237m ngắm 3 dãy Alps' },
      { icon: '🏯', text: '松本城 quốc bảo + 大出公園 postcard view của Hakuba' },
      { icon: '💧', text: 'となみチューリップ 350万本 + 称名滝+ハンノキ滝 V-shape' },
    ],
    totalKm: 1310,
    routeGo: '中央道 → 諏訪南IC → 北八ヶ岳 → 白樺湖 → ペンション (Day 1) · 松本 → 大町 → 白馬 → 糸魚川 → 砺波 → 黒部 (Day 2)',
    routeReturn: '北陸道 → 関越道 (430km · 5h) — an toàn lái đêm, ít cua',
    routeOptions: [
      '✅ 中央道→諏訪南IC→北八ヶ岳→白樺湖→ペンション→松本→大町→白馬→糸魚川→砺波→黒部 — Cung đường Alps đẹp nhất!',
      '上信越道→長野→松本→白馬→糸魚川→砺波→黒部 — Bỏ 蓼科, tiết kiệm 1 đêm.',
      '関越道→北陸道→砺波→黒部 — Nhanh nhất, bỏ Nagano hoàn toàn.',
    ],
    gallery: [
      { src: 'images/plan-a/kita-yatsugatake.jpg', caption: '北八ヶ岳ロープウェイ — gondola lên 2,237m ngắm 3 dãy Alps', spot: '北八ヶ岳ロープウェイ' },
      { src: 'images/plan-a/shirakaba-lake.png', caption: '白樺湖 — hồ bạch dương thơ mộng, ăn trưa ven hồ', spot: '白樺湖' },
      { src: 'images/plan-a/matsumoto-castle.jpg', caption: '松本城 — quốc bảo Nhật Bản, lâu đài đen "Karasu-jō" với núi Alps làm nền', spot: '松本城' },
      { src: 'images/plan-a/oide-park.jpg', caption: '大出公園 — cầu treo gỗ + nhà cổ + sông + Alps tuyết, postcard view của Hakuba', spot: '大出公園' },
      { src: 'images/plan-a/nagano-tualyp.png', caption: 'となみチューリップフェア — 350万本 hoa tulip rực rỡ', spot: 'となみチューリップフェア' },
      { src: 'images/plan-a/sho-myo.jpeg', caption: '称名滝 — thác cao nhất Nhật Bản 350m, nước đổ hùng vĩ', spot: '称名滝' },
      { src: 'images/plan-a/hanno-taki.png', caption: 'ハンノキ滝 — thác đôi V-shape chỉ có tháng 5, bên cạnh 称名滝', spot: 'ハンノキ滝' },
    ],
    days: [
      {
        dayNum: 1,
        title: 'Day 1 — Chủ Nhật 3/5',
        subtitle: '向島 → 北八ヶ岳ロープウェイ → 白樺湖 (lunch) → ペンション → tản bộ + ăn tối',
        specialties: [
          { emoji: '🍜', name: '信州そば', where: '白樺湖 area', desc: 'Mì soba kiều mạch Nagano — ăn trưa quanh hồ Shirakaba' },
          { emoji: '🥛', name: '牛乳ソフトクリーム', where: '白樺湖 牧場', desc: 'Kem sữa tươi từ trang trại — đặc sản cao nguyên' },
          { emoji: '🍓', name: 'コケモモジュース', where: '北八ヶ岳 đỉnh', desc: 'Nước việt quất núi — đặc sản trên đỉnh ロープウェイ' },
          { emoji: '🥩', name: 'Shinshu beef / BBQ', where: 'ペンション tối', desc: 'Thịt bò Shinshu — bữa tối tại pension hoặc quán quanh đó' },
        ],
        segments: [
          { from: '向島', to: '北八ヶ岳ロープウェイ', km: 230, time: '3h30', mode: 'car' },
          { from: 'ロープウェイ', to: '白樺湖', km: 25, time: '35min', mode: 'car' },
          { from: '白樺湖', to: 'ペンション 風と旅のアトリエ', km: 20, time: '30min', mode: 'car' },
        ],
        stops: [
          {
            id: 'a-d1-depart',
            name: 'Tập kết nhà anh Hà (向島)',
            lat: 35.7180, lng: 139.8130,
            address: '東京都墨田区向島5-35-11',
            mapsUrl: 'https://maps.app.goo.gl/wgYs82VGcguTHPhd6',
            arrivalTime: '04:30',
            duration: 0,
            type: 'minor',
            description: '3 xe tập kết tại 墨田区向島5-35-11 lúc 4:30 sáng. Đổ xăng → 首都高 → 中央道 hướng 諏訪. Xuất phát siêu sớm để né GW rush — đường thoáng, đến 北八ヶ岳ロープウェイ trước 8:00.',
            food: null,
            tips: '2 nhà đến trước 4:20. Ngủ sớm tối hôm trước! Trẻ ngủ tiếp trên xe. Mang chăn mỏng cho trẻ. Dừng SA giữa đường để vệ sinh + ăn sáng nhẹ.',
            weather: '14-18°C · 🌌 Tokyo đêm khuya — mát',
          },
          {
            id: 'a-ropeway',
            name: '北八ヶ岳ロープウェイ',
            lat: 36.1164, lng: 138.3167,
            address: '長野県茅野市北山4035-2541 (Chino, Nagano 391-0301)',
            mapsUrl: 'https://maps.app.goo.gl/U3h7DGB6neBQH78g8',
            arrivalTime: '08:00',
            duration: 120,
            type: 'major',
            description: '100 người/chuyến, lên 2,237m trong 7 phút. Từ đỉnh nhìn toàn bộ 3 dãy Alps Nhật Bản. Xuống bộ tham quan 坪庭自然園 — vườn cao nguyên với đá nham thạch và cây thấp lùn — đi bộ 30-40 phút nhẹ nhàng, trẻ em thích. Tháng 5 còn có thể thấy tuyết trên đỉnh.',
            food: 'Cafe tại đỉnh — コケモモジュース (nước việt quất núi) · ăn snack',
            tips: 'Trên đỉnh lạnh hơn 10°C — mang áo gió. Chuyến sáng sớm ít người. Vé khứ hồi ~¥1,900/người lớn, ¥950/trẻ. Tham quan thoải mái 2 tiếng.',
            weather: '2-10°C · 🏔️ Lạnh trên đỉnh, cần áo gió',
          },
          {
            id: 'a-shirakaba-lunch',
            name: '白樺湖 — Ăn trưa & tản bộ ven hồ',
            lat: 36.0997, lng: 138.1853,
            address: '長野県茅野市北山白樺湖3419-3 (Kitayama, Chino, Nagano 391-0301)',
            mapsUrl: 'https://maps.app.goo.gl/VyaXTcKrQAYP87Zr5',
            arrivalTime: '10:45',
            duration: 180,
            type: 'major',
            description: 'Hồ bạch dương trên cao nguyên — phản chiếu núi 蓼科山 và bạch dương xung quanh. Quanh hồ có nhiều quán ăn và cafe. Ăn trưa thoải mái 信州そば hoặc Shinshu beef BBQ, sau đó tản bộ ven hồ chụp ảnh. Có thể chèo thuyền đạp vịt nếu trẻ thích.',
            food: '🍜 信州そば · 🥛 kem sữa tươi · 🥩 Shinshu beef BBQ · cafe ven hồ',
            tips: 'Tháng 5 ít đông, không cần đặt trước. Bãi đỗ miễn phí. Trẻ chạy nhảy thoải mái quanh hồ. 3h ăn trưa + thư giãn — không vội.',
            weather: '10-18°C · 🌿 Cao nguyên 1,400m, mát trong lành',
          },
          {
            id: 'a-pension-tateshina',
            name: 'ペンション 風と旅のアトリエ — Check-in',
            lat: 36.0880, lng: 138.1800,
            address: '長野県小県郡長和町大門3518-2649 (Daimon, Nagawa, Chiisagata, Nagano 386-0601)',
            mapsUrl: 'https://maps.app.goo.gl/xWTYJmQHk4S6Rfvz6',
            arrivalTime: '14:30',
            duration: 90,
            type: 'major',
            description: 'Check-in pension. Nhận phòng, để hành lý, nghỉ ngơi sau ngày dài lái xe + leo núi. Pension nằm trên cao nguyên ビーナスライン — yên tĩnh, không khí trong lành.',
            food: null,
            tips: 'チェックイン 15:00〜 (đến 14:30 nếu pension cho phép drop bags sớm). Trao đổi với chủ pension về giờ ăn tối + bữa sáng + tình trạng đường ngày mai.',
            weather: '8-14°C · 🌤️ Chiều cao nguyên',
          },
          {
            id: 'a-d1-walk-dinner',
            name: 'Tản bộ quanh pension + tìm quán ăn tối',
            lat: 36.0880, lng: 138.1800,
            address: '長野県小県郡長和町大門3518-2649 周辺',
            mapsUrl: 'https://maps.app.goo.gl/xWTYJmQHk4S6Rfvz6',
            arrivalTime: '16:00',
            duration: 180,
            type: 'major',
            description: 'Tản bộ quanh khu pension — hít thở không khí cao nguyên, ngắm hoàng hôn núi. Tìm quán ăn tối quanh đó (hoặc dùng bữa tối tại pension nếu đã đặt). Tối: ngắm sao trời — 蓼科高原 ánh sáng môi trường ít, sao đầy trời.',
            food: '🥩 Shinshu beef BBQ · ペンション手料理コース · izakaya địa phương',
            tips: '⚠️ Trao đổi với chủ pension trước về việc ăn tối: tự tìm quán hay đặt suất tại pension. Đêm ra ngoài ngắm sao — mặc ấm (5-10°C). ⚠️ Sáng mai 8:30 xuất phát đi 松本城 — hỏi tình trạng đường凍結 trước đêm ngủ.',
            weather: '8-14°C · 🌙 Hoàng hôn → đêm sao trời',
          },
        ],
      },
      {
        dayNum: 2,
        title: 'Day 2 — Thứ Hai 4/5',
        subtitle: '蓼科 → 松本城 → 大出公園 → 糸魚川 → チューリップフェア → 称名滝 → ほたるいか → HOTEL R9',
        specialties: [
          { emoji: '🍡', name: 'Soba 信州', where: '松本城 area', desc: 'Mì kiều mạch Shinshu — đặc sản Nagano, ăn trưa gần 松本城' },
          { emoji: '🌷', name: 'チューリップソフト', where: '砺波 フェア', desc: 'Kem tulip màu hồng ngọt dịu — ăn giữa 350万本 hoa' },
          { emoji: '🍦', name: 'Kem sữa 立山', where: '称名滝 area', desc: 'Kem tươi vùng núi — bán tại レストハウス称名' },
          { emoji: '🦑', name: 'ほたるいか tempura', where: 'ほたるいかミュージアム', desc: 'Mực phát sáng chiên giòn — ăn tối tươi nhất có thể' },
        ],
        segments: [
          { from: 'Hotel 蓼科', to: '松本城', km: 50, time: '1h', mode: 'car' },
          { from: '松本城', to: '白馬 → 糸魚川 (R148)', km: 130, time: '2h30', mode: 'car' },
          { from: '糸魚川 → チューリップフェア (砺波)', km: 80, time: '1h', mode: 'car' },
          { from: 'チューリップフェア → 称名滝', km: 60, time: '50min', mode: 'car' },
          { from: '称名滝 → ほたるいかミュージアム', km: 50, time: '50min', mode: 'car' },
          { from: 'ほたるいかミュージアム → HOTEL R9', km: 30, time: '35min', mode: 'car' },
        ],
        stops: [
          {
            id: 'a-d2-depart',
            name: 'Xuất phát ペンション風と旅のアトリエ → 松本城',
            lat: 36.0880, lng: 138.1800,
            address: '長野県小県郡長和町大門3518-2649 (Daimon, Nagawa, Chiisagata, Nagano 386-0601)',
            mapsUrl: 'https://maps.app.goo.gl/xWTYJmQHk4S6Rfvz6',
            arrivalTime: '08:30',
            duration: 0,
            type: 'minor',
            description: 'Check-out sớm. Ăn sáng tại pension rồi xuất phát đi 松本城. Route: 蓼科 → R299 → 松本 (~1h). Đi sớm để kịp tham quan lâu đài trước khi đông.',
            food: 'Ăn sáng tại pension (hỏi trước giờ phục vụ)',
            tips: '⚠️ 凍結リスク: 5月初旬の早朝、ビーナスライン沿道（標高1,400m）が凍結する場合あり。スタッドレス不要だが、出発前に宿主に路面状況を確認すること。気温5°C以上・8時以降の出発が安全。',
            weather: '8-14°C · 🌤️ Sáng cao nguyên mát — kiểm tra nhiệt độ trước khi đi',
          },
          {
            id: 'a-matsumoto-castle',
            name: '松本城 (Matsumoto Castle)',
            lat: 36.2384, lng: 137.9690,
            address: '長野県松本市丸の内4-1 (Marunouchi, Matsumoto, Nagano 390-0873)',
            mapsUrl: 'https://maps.app.goo.gl/vYEQ3oHQR8Spt5gx9',
            arrivalTime: '09:30',
            duration: 90,
            type: 'major',
            description: 'Quốc bảo Nhật Bản — 1 trong 5 lâu đài gốc còn nguyên vẹn. Lâu đài đen "Karasu-jō" (Quạ thành) phản chiếu trên hào nước, núi Alps Bắc làm nền. Tháng 5 hoa anh đào muộn còn nở, cảnh tuyệt đẹp. Vào trong tham quan 6 tầng (cầu thang dốc — bỏ giày).',
            food: 'Cafe Matsumotojō gần lâu đài hoặc ăn nhẹ trước khi đi tiếp',
            tips: 'Đến 09:30 trước khi đông. Mua vé trước online. Trẻ em < 6 tuổi miễn phí. Mang vớ dày — sàn gỗ lạnh.',
            weather: '10-18°C · 🌸 Sáng mát, lâu đài + hoa anh đào muộn',
          },
          {
            id: 'a-oide-park',
            name: '大出公園 (Ōide Park) — Hakuba postcard view',
            lat: 36.7234, lng: 137.8543,
            address: '長野県北安曇郡白馬村北城 (Hokujo, Hakuba, Kitaazumi, Nagano 399-9301)',
            mapsUrl: 'https://maps.app.goo.gl/SCRH5WVGzyZSYjzCA',
            arrivalTime: '12:00',
            duration: 30,
            type: 'major',
            description: 'Spot chụp ảnh đẹp nhất Hakuba — cầu treo gỗ + nhà cổ thatched-roof + sông + dãy Alps Bắc phủ tuyết phía sau. Cảnh trên poster du lịch Nagano. Tháng 5 hoa anh đào muộn còn nở. Bãi đỗ miễn phí, đi bộ 5 phút.',
            food: 'Mua bento/onigiri tại konbini Hakuba (trên đường) để ăn trên xe',
            tips: 'Stop chụp ảnh "1 photo say it all" cho gia đình. Đi bộ 5 phút từ bãi đỗ. Mục tiêu kịp tulip fair trước 14:00.',
            weather: '10-18°C · 🏔️ Núi tuyết + cầu treo + nhà cổ',
          },
          {
            id: 'a-tulip',
            name: 'となみチューリップフェア 2026 (砺波チューリップ公園)',
            lat: 36.6477, lng: 136.9635,
            address: '富山県砺波市花園町1-32 (Hanazonomachi, Tonami, Toyama 939-1382)',
            mapsUrl: 'https://maps.app.goo.gl/G3iR4x8tANPf5nua9',
            arrivalTime: '13:30',
            duration: 75,
            type: 'major',
            description: '300品種350万本のチューリップ！「花の大谷」高さ4m×30m花のトンネル、水上花壇、チューリップタワー展望台地上絵。5/5こどもの日は中学生以下無料！Ghé giữa ngày — đủ thời gian ăn trưa + chụp ảnh.',
            food: 'Ăn trưa tại フェア: チューリップソフト + 各所屋台',
            tips: '砺波ICから車で5分。Day 2 đến 11:30 ít đông hơn sáng sớm ngày cuối tuần. 5/5 trẻ em miễn phí!',
            weather: '14-20°C · 🌷 チューリップ満開',
          },
          {
            id: 'a-shomyo',
            name: '称名滝 + ハンノキ滝',
            lat: 36.5733, lng: 137.4867,
            address: '富山県中新川郡立山町芦峅寺称名川 (Ashikuraji, Tateyama, Nakaniikawa, Toyama 930-1406)',
            mapsUrl: 'https://maps.app.goo.gl/Xfi1uY5gwJpt9mGZ8',
            arrivalTime: '15:30',
            duration: 90,
            type: 'major',
            description: '2 thác V-shape song song: 称名滝 (350m) + ハンノキ滝 (500m). Tháng 5 tuyết tan = nước cực mạnh, có thể nghe tiếng từ xa. Chiều vẫn đẹp — ánh sáng chiều chiếu vào đá đỏ vách núi. Đường paved 30 phút.',
            food: 'Kem sữa tươi tại レストハウス称名 (mở đến 17:00)',
            tips: 'Mang áo mưa mỏng — nước bắn ra rất nhiều. Đường paved hoàn toàn, đẩy được xe đẩy.',
            weather: '10-16°C · 🌤️ Mát, ánh chiều → vách đá đỏ rực',
          },
          {
            id: 'a-hotaruika',
            name: 'ほたるいかミュージアム',
            lat: 36.7632, lng: 137.3355,
            address: '富山県滑川市中川原410 (Nakagawara, Namerikawa, Toyama 936-0021)',
            mapsUrl: 'https://maps.app.goo.gl/gqiS7wfxxkRqD9So7',
            arrivalTime: '17:30',
            duration: 60,
            type: 'major',
            description: 'Phòng tối: hàng nghìn con mực nhỏ phát ánh sáng xanh lam. Chỉ có mùa 3-5月, chỉ có Toyama Bay. Touch pool cho trẻ. Ăn tối tại quán bên cạnh trước khi về hotel.',
            food: 'Ăn tối: ほたるいか tempura tươi nhất tại quán bên cạnh',
            tips: 'Live display phòng tối là highlight — trẻ mê nhất. Xem xong ăn ngay tại đây luôn.',
            weather: '15-20°C · 🌆 Chiều tối, ven biển',
          },
          {
            id: 'a-hotel-r9-d2',
            name: 'HOTEL R9 The Yard Kurobe',
            lat: 36.8719, lng: 137.4479,
            address: '富山県黒部市堀切938-1 (Horikiri, Kurobe, Toyama 938-0041)',
            mapsUrl: 'https://maps.app.goo.gl/bCmpJb4iNDCrCoWF8',
            arrivalTime: '19:30',
            duration: 0,
            type: 'major',
            description: 'Check-in HOTEL R9. Ngày 2 dày nhất — nghỉ sớm, ngủ thẳng giấc.',
            food: 'Đã ăn tối tại ほたるいか — hoặc ghé konbini nếu cần thêm',
            tips: 'Đặt vé Trolley ngày mai trước khi ngủ!',
            weather: '14-20°C · 🌙 Mát mẻ',
          },
        ],
      },
      {
        dayNum: 3,
        title: 'Day 3 — Thứ Ba 5/5',
        subtitle: 'トロッコ 11:48 → ひみ番屋街ランチ → 雨晴海岸 Golden Hour → 富岩運河スタバ夜景 → Onsen tắm → Tokyo',
        specialties: [
          { emoji: '🍣', name: 'ます寿し bento', where: 'SA đường về', desc: 'Sushi cá hồi ép truyền thống Toyama — mua mang đi trên xe' },
          { emoji: '🍜', name: '氷見うどん', where: 'ひみ番屋街', desc: 'Mì udon Himi mịn dai, ăn trưa sau trolley' },
          { emoji: '🦐', name: '白エビ天丼', where: 'ひみ番屋街', desc: 'Tôm trắng Toyama — đặc sản #1, tempura giòn' },
        ],
        segments: [
          { from: 'HOTEL R9 (checkout 10:30)', to: '宇奈月駅', km: 20, time: '20min', mode: 'car' },
          { from: '宇奈月 (11:48発)', to: '笹平 往復', km: 16, time: '2h10', mode: 'trolley' },
          { from: '宇奈月 (~14:00)', to: 'ひみ番屋街 (氷見)', km: 60, time: '1h', mode: 'car' },
          { from: 'ひみ番屋街', to: '雨晴海岸', km: 15, time: '15min', mode: 'car' },
          { from: '雨晴海岸', to: '富岩運河環水公園', km: 20, time: '30min', mode: 'car' },
          { from: '富岩運河', to: 'スパ・アルプス (Toyama)', km: 5, time: '10min', mode: 'car' },
          { from: 'スパ・アルプス', to: '向島 (Tokyo)', km: 400, time: '5h', mode: 'car' },
        ],
        stops: [
          {
            id: 'a-d3-checkout',
            name: 'Checkout HOTEL R9 → 宇奈月駅',
            lat: 36.8719, lng: 137.4479,
            address: '富山県黒部市堀切938-1 (Horikiri, Kurobe, Toyama 938-0041)',
            mapsUrl: 'https://maps.app.goo.gl/bCmpJb4iNDCrCoWF8',
            arrivalTime: '10:30',
            duration: 0,
            type: 'minor',
            description: 'Ngủ thêm sáng cho con. Checkout 10:30, lái thẳng đến 宇奈月駅 (~20 phút). Mua snack/nước tại konbini gần ga để ăn trên tàu.',
            food: 'Konbini gần ga: onigiri · nước · snack cho trẻ',
            tips: 'Bỏ tản bộ buổi sáng — dồn thời gian nghỉ vào tối. Đến ga 10:50, vé 11:48 dư thời gian.',
            weather: '14-20°C · 🌸 Mát buổi sáng',
          },
          {
            id: 'a-trolley',
            name: '黒部峡谷トロッコ (宇奈月駅 — gửi xe & lên tàu)',
            lat: 36.8150, lng: 137.5860,
            address: '富山県黒部市黒部峡谷口 (Kurobekyokokuguchi, Kurobe, Toyama 938-0283)',
            mapsUrl: 'https://maps.app.goo.gl/78Mbufo23qiq34U67',
            arrivalTime: '11:48',
            duration: 130,
            type: 'major',
            description: 'Tàu trolley hẻm V-shape Kurobe — hẻm núi sâu nhất Nhật Bản. 2026: đến 笹平 (5/3~5/9). Khứ hồi ~2h10. Về đến 宇奈月 khoảng 14:00.',
            food: 'Mua snack tại 宇奈月駅 trước khi lên tàu',
            tips: '⚠️ Vé 11:48 — ĐÚNG GIỜ, không trễ! Đặt vé từ 1/4 tại torokko-yoyaku.com. Chọn toa mở (普通客車). Ngồi bên PHẢI chiều đi để ngắm sông tốt nhất.',
            weather: '14-20°C · 🌿 Hẻm núi mát mẻ, cảnh xanh',
          },
          {
            id: 'a-himi',
            name: 'ひみ番屋街 — 氷見漁港場外市場',
            lat: 36.8567, lng: 136.9870,
            address: '富山県氷見市北大町25-5 (Kitaomachi, Himi, Toyama 935-0004)',
            mapsUrl: 'https://maps.app.goo.gl/ATXM57N9ueYQtJABA',
            arrivalTime: '15:00',
            duration: 90,
            type: 'major',
            description: '氷見漁港直送の海産物マーケット！白エビ天丼・氷見うどん・海鮮丼で遅めのランチ。子どもたちは広い港エリアを走り回れる。富山みやげの最終調達にも最適。雨晴海岸まで車で15分。',
            food: '🍜 氷見うどん · 🦐 白エビ天丼 · 🐟 海鮮丼 · Omiyage: 氷見牛・海産物',
            tips: '子連れに最高のスポット — 広い屋外エリアで自由に動ける。駐車場無料。トイレあり。雨晴海岸まで15分。',
            weather: '15-20°C · 🌊 港の海風',
          },
          {
            id: 'a-ameharashi',
            name: '雨晴海岸 (Ameharashi Coast)',
            lat: 36.7740, lng: 137.0240,
            address: '富山県高岡市太田24-74 (Ota, Takaoka, Toyama 933-0133)',
            mapsUrl: 'https://maps.app.goo.gl/xhJXXws7cLQcPGPU7',
            arrivalTime: '17:00',
            duration: 100,
            type: 'major',
            description: '富山湾 + 立山連峰 + 赤いJR氷見線の聖地！日没18:41の1時間40分前に到着しゴールデンアワーをフルに楽しむ。17:00〜18:41まで山の色が刻々と変化する絶景タイム。3家族で記念撮影の絶好チャンス。',
            food: 'ひみ番屋街で買ったおやつ · 近くのカフェ',
            tips: '📸 17:00着でゴールデンアワーをフル確保。JR氷見線の時刻を事前確認 → 列車が来る瞬間にシャッター。北陸道 高岡ICへすぐ。駐車場無料。',
            weather: '14-18°C · 🌅 ゴールデンアワー → 日没18:41 → 山が黄金色に',
            images: [
              { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Ameharashi_Coast.jpg/640px-Ameharashi_Coast.jpg', alt: '雨晴海岸 富山湾 立山連峰' },
            ],
          },
          {
            id: 'a-kansui',
            name: '富岩運河環水公園 + 世界一美しいスタバ',
            lat: 36.6983, lng: 137.2113,
            address: '富山県富山市湊入船町5 富岩運河環水公園 (Minatoirifunecho 5, Toyama 930-0805)',
            mapsUrl: 'https://maps.app.goo.gl/oe6T8pde8fDFtZLE7',
            arrivalTime: '19:30',
            duration: 75,
            type: 'major',
            description: '夜の富岩運河環水公園！天門橋のライトアップが水面に映り込む幻想的な夜景。「世界一美しいスタバ」で日没後の絶景を楽しむ。日没(18:41)から約50分後 — ライトアップが最高潮に。',
            food: 'スターバックス コーヒー 富山環水公園店 (22:30まで営業) · テラス席で夜風を感じながら',
            tips: '📸 撮影ベスト: スタバを横から写す構図 + 天門橋 + 水面リフレクション。ライトアップ22:00まで、天門橋展望塔21:00まで。駐車場無料。',
            weather: '14-18°C · 🌃 夜景 — ライトアップ22時まで',
          },
          {
            id: 'a-onsen-rest',
            name: 'スパ・アルプス (Toyama) — Onsen tắm rửa & nghỉ ngơi',
            lat: 36.6928, lng: 137.2354,
            arrivalTime: '21:00',
            duration: 90,
            type: 'major',
            description: 'Super-sento 24/7 gần Toyama IC — onsen tự nhiên, sauna, phòng nghỉ. Tắm rửa sạch sẽ, thư giãn cơ bắp trước khi lái xe đêm 5h về Tokyo. Trẻ em được tắm + ngủ thêm trong phòng nghỉ. Người lớn tỉnh táo hơn nhiều khi lái.',
            food: 'Nhà hàng trong onsen mở khuya — ăn nhẹ trước khi lái',
            tips: '🔑 LÝ DO: tắm rửa + thư giãn = lái đêm an toàn hơn. Vào lúc 21:00 (sau khi xem スタバ), ra 22:30. Phí ~¥1,400/người lớn, trẻ em rẻ hơn. Có khu trẻ em.',
            weather: '15-18°C · ♨️ Onsen ấm áp',
          },
          {
            id: 'a-return',
            name: 'Xuất phát về Tokyo (向島)',
            lat: 35.7180, lng: 139.8130,
            address: '東京都墨田区向島5-35-11',
            mapsUrl: 'https://maps.app.goo.gl/wgYs82VGcguTHPhd6',
            arrivalTime: '22:30',
            duration: 0,
            type: 'major',
            description: '北陸道 → 関越道で帰路。~5h。向島到着 3:30~4:00 AM。Sau khi tắm onsen ai cũng tỉnh táo và sạch sẽ — trẻ ngủ ngay khi lên xe. GW Uターンラッシュのピーク後 — 渋滞ほぼなし。',
            food: 'Ăn nhẹ tại onsen trước khi đi · SA ます寿しbento giữa đường',
            tips: '22:30 出発 — Uターンラッシュ後 hoàn toàn, đường rất thoáng. SA休憩 1-2 lần. Đổi ca lái. Đến 向島 ~4:00 AM.',
            weather: '14°C → 18°C · 🌙 夜の北陸道 — 空いていて走りやすい',
          },
        ]
      },
    ],
  },

  B: {
    name: '雨でも感動プラン ☔',
    color: '#3D6B8A',
    subtitle: '雨天特化 — 奈良井宿+松本城+五箇山+能作体験+Trolley+ガラス美術館',
    route: '奈良井宿 → 松本城 → 蓼科 → 五箇山 → 能作体験 → 富岩運河夜景 → Trolley → ガラス美術館',
    highlights: [
      { icon: '🏘️', text: '奈良井宿+松本城 — 雨で情緒MAX、屋根付き・室内完結' },
      { icon: '🏡', text: '五箇山 合掌造り UNESCO — 霧雨+茅葺き屋根=非日常の世界' },
      { icon: '🚂', text: 'Trolley 黒部峡谷 — 雨=水墨画の峡谷、晴れより幻想的' },
    ],
    totalKm: 1100,
    routeGo: '中央道 → 塩尻IC → 奈良井宿 → 松本城 → 白樺湖 → 糸魚川 → 五箇山 → 黒部',
    routeReturn: '北陸道 → 関越道 (420km · 5h) — 19:00出発 → 深夜着',
    routeOptions: [
      '✅ 中央道→奈良井宿→松本→白樺湖→糸魚川→五箇山→高岡→黒部 — 雨天完全対応ルート',
      '関越道→北陸道→砺波→黒部 — 早く着きたい場合、Naganoスキップ',
    ],
    days: [
      {
        dayNum: 1,
        title: 'Day 1 — Chủ Nhật 3/5',
        subtitle: '向島 → 奈良井宿 → 松本城 → Pension 蓼科 → テディベア美術館 → Switchback dinner',
        specialties: [
          { emoji: '🍡', name: 'Oyaki nóng', where: '奈良井宿', desc: 'Bánh nhân rau củ nướng than — đặc sản Edo, ăn dưới mái hiên mưa' },
          { emoji: '🍜', name: '信州そば', where: '松本市内', desc: 'Soba buckwheat Nagano — ăn trưa cạnh quốc bảo 400 năm tuổi' },
          { emoji: '🥩', name: 'Shinshu beef', where: 'Switchback TATESHiNA', desc: 'Bít tết bò địa phương nướng lò pizza — bữa tối đáng nhớ nhất trip' },
        ],
        segments: [
          { from: '向島', to: '奈良井宿 (塩尻IC)', km: 230, time: '3h', mode: 'car' },
          { from: '奈良井宿', to: '松本城', km: 20, time: '25min', mode: 'car' },
          { from: '松本城', to: 'Pension 白樺湖', km: 55, time: '1h', mode: 'car' },
          { from: 'Pension', to: '蓼科テディベア美術館', km: 5, time: '10min', mode: 'car' },
          { from: 'テディベア', to: 'Switchback TATESHiNA', km: 20, time: '25min', mode: 'car' },
        ],
        stops: [
          {
            id: 'b-d1-depart',
            name: 'Tập kết nhà anh Hà (向島)',
            lat: 35.7180, lng: 139.8130,
            arrivalTime: '06:00',
            duration: 0,
            type: 'minor',
            description: '3 xe tập kết. 雨天プラン: 中央道 → 塩尻IC → 奈良井宿 → 松本城 → 白樺湖。ビーナスラインはスキップ — 霧で何も見えない。',
            food: null,
            tips: '⛈️ 雨天確定プラン。全点室内または屋根付き。',
            weather: '15-20°C · 🌧️ 雨',
          },
          {
            id: 'b-naraijuku',
            name: '奈良井宿 — 中山道最長の宿場町',
            lat: 35.9216, lng: 137.8697,
            arrivalTime: '09:00',
            duration: 90,
            type: 'major',
            description: '1km続く江戸の宿場町。千本格子の軒先が連続し、雨で濡れた木の街並みが墨絵のよう。軒下を伝って歩けるので傘なしでも多くのエリアを歩ける。おやき・漆器・信州そばが揃う。塩尻ICから30分。',
            food: '🍡 焼きたておやき · 信州そば · 木曽漆器ショッピング',
            tips: '⛈️ 雨が木の格子をしっとり濡らして情緒UP。軒下伝い歩きOK。駐車場無料。所要1〜1.5h。',
            weather: '12-16°C · 🌧️ 雨でも絵になる宿場町',
            images: [
              { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Naraijuku_Nagano_pref_Japan01s3.jpg/640px-Naraijuku_Nagano_pref_Japan01s3.jpg', alt: '奈良井宿' },
            ],
          },
          {
            id: 'b-matsumoto',
            name: '松本城 — 国宝天守 (Quick Stop)',
            lat: 36.2381, lng: 137.9719,
            arrivalTime: '11:00',
            duration: 60,
            type: 'major',
            description: '5重6階の国宝天守。雨が外堀の水面に波紋を描き、黒い城の逆さ像が幻想的。GW混雑時は外から撮影のみでも絵になる。松本で信州そばランチ。',
            food: '松本市内 信州そばランチ (城周辺に名店多数)',
            tips: '混雑時は外観撮影のみでOK — 雨の日の濡れた石垣+黒天守は絵になる。入場すると1〜1.5h。',
            weather: '14-18°C · 🌧️ 雨の城 — 水面の逆さ松本城',
            images: [
              { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Matsumoto_Castle_in_Matsumoto_City.jpg/640px-Matsumoto_Castle_in_Matsumoto_City.jpg', alt: '松本城' },
            ],
          },
          {
            id: 'b-pension-d1',
            name: 'ペンション 風と旅のアトリエ — Check-in',
            lat: 36.0880, lng: 138.1800,
            arrivalTime: '14:00',
            duration: 60,
            type: 'minor',
            description: '長野県立科町大門3518-2649。松本から約1時間。雨の日は早めにcheck-in、荷物を置いてから蓼科テディベア美術館へ。',
            food: '荷物置いてすぐ出発',
            tips: 'Check-in 15:00〜。事前に早めチェックイン可否を確認。',
            weather: '10-14°C · 🌧️ 高原の雨',
          },
          {
            id: 'b-teddy',
            name: '蓼科テディベア美術館',
            lat: 36.0850, lng: 138.2750,
            arrivalTime: '15:00',
            duration: 90,
            type: 'major',
            description: '世界最大規模3,300m²。18ゾーンにテディベアが勢揃い。ギネス認定0.8mmの世界最小ベアも。子どもから大人まで楽しめる完全室内施設。雨の日の鉄板スポット。',
            food: 'ミュージアムカフェ · ベアモチーフのスイーツ',
            tips: '完全室内。所要1.5h。',
            weather: '10-14°C · ☔ 完全室内',
          },
          {
            id: 'b-dinner-d1',
            name: 'the Switchback TATESHiNA — 夕食',
            lat: 36.0539, lng: 138.2728,
            arrivalTime: '18:30',
            duration: 90,
            type: 'major',
            description: '評価4.4⭐ 蓼科ベストディナー。信州牛ピザ窯焼きステーキ。3家族揃ってGW初日の夜を祝う特別ディナー。',
            food: '🥩 信州牛ピザ窯ステーキ · ピザ · パスタ · こどもメニューあり',
            tips: '⚠️ 事前予約必須 (10名): 📞 0266-67-5550。Pensionから車で20分。',
            weather: '8-12°C · 🌧️ 暖かい店内でディナー',
          },
        ],
      },
      {
        dayNum: 2,
        title: 'Day 2 — Thứ Hai 4/5',
        subtitle: '蓼科 → 五箇山 合掌造り → 道の駅休憩 → 能作錫体験 → 富岩運河スタバ夜景 → HOTEL R9',
        specialties: [
          { emoji: '🏡', name: '合掌造りランチ', where: '五箇山', desc: '茅葺き屋根の中で食べる山菜そば — 非日常体験' },
          { emoji: '🥈', name: '錫鋳造体験', where: '能作 高岡', desc: '世界で1つ、自分だけの錫製品を手作り' },
          { emoji: '☕', name: 'スタバ夜景', where: '富岩運河環水公園', desc: '天門橋ライトアップ+水面リフレクション — trip最高の1枚' },
        ],
        segments: [
          { from: 'Pension (checkout 09:00)', to: '五箇山 相倉集落', km: 140, time: '2h', mode: 'car' },
          { from: '五箇山', to: '道の駅 上平', km: 5, time: '10min', mode: 'car' },
          { from: '道の駅', to: '能作 (高岡市)', km: 70, time: '1h', mode: 'car' },
          { from: '能作', to: '富岩運河環水公園', km: 15, time: '20min', mode: 'car' },
          { from: '富岩運河', to: 'HOTEL R9', km: 40, time: '45min', mode: 'car' },
        ],
        stops: [
          {
            id: 'b-d2-depart',
            name: 'Pension checkout → 五箇山へ',
            lat: 36.0880, lng: 138.1800,
            arrivalTime: '09:00',
            duration: 0,
            type: 'minor',
            description: 'Checkout 09:00。白馬エリアは通過のみ — 雨で景色見えない。五箇山に時間を集中。',
            food: 'Pension朝食 (要事前確認)',
            tips: '白馬の大出公園はスキップ。五箇山に時間を使う。',
            weather: '10-15°C · 🌧️ 雨',
          },
          {
            id: 'b-gokayama',
            name: '五箇山 相倉集落 — UNESCO合掌造り',
            lat: 36.4139, lng: 136.9003,
            arrivalTime: '11:00',
            duration: 120,
            type: 'major',
            description: '300年以上の合掌造り集落、UNESCO世界遺産。霧雨の中、茅葺き屋根の大きな家が山あいにひっそりと立つ姿は別世界。子どもたちが茅葺き屋根の高さ(15m超)に驚く瞬間は本物のリアクション。集落内の民家でランチも可能。雨の日こそ情緒が増す場所。',
            food: '合掌造り民家の山菜そば · いろり端の郷土料理 · 五箇山豆腐',
            tips: '⛈️ 雨の五箇山は晴れより美しい — 霧と茅葺きの組み合わせが唯一無二。集落内は舗装道。傘必須。所要1.5〜2h。',
            weather: '12-16°C · 🌧️ 霧雨+合掌造り = 非日常の世界',
            images: [
              { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Gokayama_Ainokura.jpg/640px-Gokayama_Ainokura.jpg', alt: '五箇山 相倉集落' },
            ],
          },
          {
            id: 'b-michinoeki',
            name: '道の駅 上平 ささら館 — 休憩',
            lat: 36.4108, lng: 136.8892,
            arrivalTime: '13:00',
            duration: 30,
            type: 'minor',
            description: '五箇山のすぐそば。地元の特産品・お土産を買いながら休憩。子どもを外に出して少し走らせる。能作への移動前の英気を養う。',
            food: '五箇山豆腐 · 地元野菜 · 軽食',
            tips: '五箇山のomiyage最終調達に最適。子どもを少し遊ばせてリセット。',
            weather: '13-17°C · 🌧️ 屋根あり',
          },
          {
            id: 'b-nousaku',
            name: '能作 工場見学 + 錫鋳造体験',
            lat: 36.5389, lng: 136.9764,
            arrivalTime: '14:30',
            duration: 90,
            type: 'major',
            description: '創業100年以上の高岡伝統錫メーカー。職人の技を間近で見学後、自分で錫製品を手作り。世界でひとつの錫のぐい呑みや小皿が完成。完全室内。',
            food: '能作カフェ — 錫の器で提供される地元食材',
            tips: '⚠️ 体験は事前予約推奨。¥2,200〜/人。5歳以下は鋳造体験が難しい場合あり。完全室内。',
            weather: '14-18°C · ☔ 完全室内 — 伝統工芸体験',
          },
          {
            id: 'b-kansui',
            name: '富岩運河環水公園 + 世界一美しいスタバ',
            lat: 36.6983, lng: 137.2113,
            arrivalTime: '18:00',
            duration: 90,
            type: 'major',
            description: '夜の富岩運河環水公園。天門橋のライトアップが水面に映り込む幻想的な夜景。「世界一美しいスタバ」でコーヒー片手に撮影。雨の夜は水面のリフレクションがさらに幻想的に。',
            food: 'スターバックス コーヒー 富山環水公園店 (22:30まで営業)',
            tips: '📸 撮影ベスト: スタバを横から写す構図 + 天門橋 + 水面リフレクション。ライトアップ22:00まで。駐車場無料。',
            weather: '14-18°C · 🌃 雨夜景 — 水面リフレクションが最高',
          },
          {
            id: 'b-hotel-r9-d2',
            name: 'HOTEL R9 The Yard Kurobe',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '20:00',
            duration: 0,
            type: 'minor',
            description: 'Check-in。明日はTrolley 11:48 — checkout 10:00を忘れずに。',
            food: 'スタバで軽食済み → コンビニで補充',
            tips: '明日のトロッコ切符を再確認！11:48出発、checkout 10:00。',
            weather: '12-16°C · 🌧️ 雨の黒部',
          },
        ],
      },
      {
        dayNum: 3,
        title: 'Day 3 — Thứ Ba 5/5',
        subtitle: '宇奈月 → トロッコ 11:48 (雨=水墨画) → ひみ番屋街ランチ → ガラス美術館 → Tokyo 19:00',
        specialties: [
          { emoji: '🚂', name: 'トロッコ体験', where: '黒部峡谷', desc: '雨で水墨画の峡谷 — trip最大のWOW' },
          { emoji: '🐟', name: '海鮮ランチ', where: 'ひみ番屋街', desc: '氷見漁港直送 — 白エビ天丼・氷見うどん' },
          { emoji: '🎨', name: 'ガラス美術館', where: '富山市', desc: '隈研吾設計の6層空間 — 室内WOW締め' },
        ],
        segments: [
          { from: 'HOTEL R9 (checkout 10:00)', to: '宇奈月駅', km: 20, time: '20min', mode: 'car' },
          { from: '宇奈月 (11:48発)', to: '笹平 往復', km: 16, time: '2h10', mode: 'trolley' },
          { from: '宇奈月 (~14:00)', to: 'ひみ番屋街 (氷見)', km: 60, time: '1h', mode: 'car' },
          { from: 'ひみ番屋街', to: '富山市ガラス美術館', km: 25, time: '30min', mode: 'car' },
          { from: 'ガラス美術館', to: '向島 (Tokyo)', km: 420, time: '5h', mode: 'car' },
        ],
        stops: [
          {
            id: 'b-unazuki',
            name: '宇奈月温泉 散策',
            lat: 36.8173, lng: 137.5841,
            arrivalTime: '10:20',
            duration: 85,
            type: 'minor',
            description: 'Checkout 10:00 → hành lý lên xe → lái đến 宇奈月駅 (20 phút). Tản bộ phố onsen, mua snack cho lên tàu.',
            food: 'Kem onsen · 温泉たまご · onigiri cho lên tàu',
            tips: 'Checkout 10:00 → 宇奈月駅 10:20. Trolley 11:48 — không trễ!',
            weather: '12-16°C · 🌧️',
          },
          {
            id: 'b-trolley',
            name: '黒部峡谷トロッコ (宇奈月〜笹平) — 雨の日こそ絶景',
            lat: 36.8150, lng: 137.5860,
            arrivalTime: '11:48',
            duration: 130,
            type: 'major',
            description: '雨の日のトロッコは別格。光の反射が消えるため木々の緑が鮮明に浮かび上がり、霧に包まれたうなづき湖が水墨画のよう。雨だけに現れる幻の滝も出現。2026年：宇奈月〜笹平運行。約13:04頃宇奈月着。',
            food: '宇奈月駅で購入したおやつを車内で',
            tips: '⚠️ 11:48 ĐÚNG GIỜ! Đặt vé từ 1/4 tại torokko-yoyaku.com. Chọn toa mở (普通客車). Ngồi bên PHẢI chiều đi.',
            weather: '12-16°C · 🌧️ 雨のトロッコ — 水墨画の峡谷',
            images: [
              { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Kurobe_Gorge_Railway_01.jpg/640px-Kurobe_Gorge_Railway_01.jpg', alt: '黒部峡谷トロッコ' },
            ],
          },
          {
            id: 'b-himi',
            name: 'ひみ番屋街 — 氷見漁港場外市場',
            lat: 36.8567, lng: 136.9870,
            arrivalTime: '15:00',
            duration: 75,
            type: 'major',
            description: '氷見漁港直送の海産物マーケットで遅めのランチ。屋根付きエリアあり。子どもが走り回れる広いスペース。富山みやげ最終調達。',
            food: '🍜 氷見うどん · 🦐 白エビ天丼 · 🐟 海鮮丼 · Omiyage',
            tips: '屋根付きエリアあり。駐車場無料。',
            weather: '14-18°C · 🌧️ 屋根あり',
          },
          {
            id: 'b-glass-museum',
            name: '富山市ガラス美術館 — 隈研吾設計',
            lat: 36.6972, lng: 137.2128,
            arrivalTime: '16:30',
            duration: 60,
            type: 'major',
            description: '世界的建築家・隈研吾設計。6層吹き抜けのガラスと木のアート空間。世界的ガラス作家Dale Chihuly作品など圧巻のスケール。完全室内。旅の最後を締めくくる知的な空間。',
            food: '館内カフェ',
            tips: '開館9:30〜18:00。入館料¥200(常設展)。5/5(火)は開館OK。完全室内。',
            weather: '14-18°C · ☔ 完全室内 — 隈研吾の建築アート',
          },
          {
            id: 'b-return',
            name: 'Xuất phát về Tokyo — 19:00',
            lat: 35.7180, lng: 139.8130,
            arrivalTime: '19:00',
            duration: 0,
            type: 'major',
            description: '北陸道 → 関越道で帰路。~5h。向島到着 約24:00。GW Uターンラッシュのピーク(17〜18時)後の出発で渋滞ほぼなし。',
            food: 'SA/PAで夕食 · コンビニ買い込み',
            tips: '19時出発でUターンラッシュ回避。SA休憩1〜2回。向島着約24:00。',
            weather: '14°C → 18°C · 🌙 夜の北陸道',
          },
        ],
      },
    ],
  },


  C: {
    name: '五箇山 & 称名滝',
    color: '#5B6ABF',
    subtitle: 'Thác cao nhất Nhật + UNESCO village + Trolley — không cần vé Alpine, tiết kiệm',
    route: '五箇山 → 称名滝 → 魚津水族館 → トロッコ',
    highlights: [
      { icon: '💧', text: '称名滝 — thác cao nhất Nhật Bản (350m)' },
      { icon: '🏘️', text: '五箇山 UNESCO — yên tĩnh, ít đông' },
      { icon: '💰', text: 'Không cần vé Alpine Route — tiết kiệm ~¥55,000' },
    ],
    totalKm: 1210,
    routeGo: '上信越道 + 北陸道 (380km · 5h30) — cảnh núi→biển đẹp',
    routeReturn: '北陸道 → 関越道 (430km · 5h) — an toàn lái đêm, ít cua',
    routeOptions: [
      '✅ 上信越道 + 北陸道 — Ngắn nhất đến 五箇山. Cảnh núi→biển đẹp. (380km · 5h30)',
      '関越道 + 北陸道 via 長岡 — Dễ lái nhất, ít cua. Trẻ ít say. (430km · 6h)',
      '上信越道 xuyên Nagano — Cảnh núi đẹp nhất nhưng cua nhiều, trẻ dễ say. (360km · 5h30)',
    ],
    gallery: [
      // Thêm ảnh: { src: 'images/plan-c/ten-anh.jpg', caption: 'Mô tả', spot: 'Tên điểm đến' }
    ],
    days: [
      {
        dayNum: 1,
        title: 'Day 1 — Chủ Nhật 3/5',
        subtitle: '向島 → 五箇山 → HOTEL R9',
        specialties: [
          { emoji: '🧈', name: '五箇山豆腐', where: '五箇山', desc: 'Đậu hũ cứng nướng than, đậm đà — đặc sản UNESCO village' },
          { emoji: '🐟', name: '岩魚塩焼き', where: '五箇山', desc: 'Cá suối nướng muối thơm giòn, trẻ em thích' },
          { emoji: '🍜', name: '富山ブラックラーメン', where: 'Kurobe', desc: 'Ramen đen xì dầu đậm đặc — ăn tối tại Kurobe' },
        ],
        segments: [
          { from: '向島', to: '五箇山', km: 380, time: '5h30', mode: 'car' },
          { from: '五箇山', to: 'HOTEL R9', km: 110, time: '1h30', mode: 'car' },
        ],
        stops: [
          {
            id: 'e-d1-depart',
            name: 'Tập kết nhà anh Hà (向島)',
            lat: 35.7180, lng: 139.8130,
            arrivalTime: '06:00',
            duration: 0,
            type: 'minor',
            description: '3 xe tập kết tại 墨田区向島5-35-11. Đổ xăng trên Meiji-dori → 向島入口 → 首都高6号 → 関越道.',
            food: null,
            tips: '2 nhà đến trước 5:50. Cùng xuất phát 6:00.',
            weather: '18-24°C · 🌤️ Tokyo ấm',
          },
          {
            id: 'e-gokayama',
            name: '五箇山 相倉集落',
            lat: 36.4260, lng: 136.9355,
            arrivalTime: '12:00',
            duration: 90,
            type: 'major',
            description: 'Làng mái tranh gassho UNESCO yên tĩnh nhất. Trẻ em thích khám phá nhà 3 tầng. Ít đông hơn 白川郷 nhiều.',
            food: '五箇山豆腐 · 岩魚塩焼き',
            tips: 'Exit 北陸道 tại 砺波IC → 東海北陸道 → 五箇山IC. Ghé trên đường, không vòng.',
            weather: '13-18°C · 🌤️ Ấm, có thể mưa nhẹ',
          },
          {
            id: 'e-hotel-r9-d1',
            name: 'HOTEL R9 The Yard Kurobe',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '15:30',
            duration: 0,
            type: 'major',
            description: 'Check-in khách sạn. Nghỉ ngơi sau chặng đường dài.',
            food: 'Ăn tối tại nhà hàng quanh Kurobe',
            tips: 'Gần Kurobe IC, tiện di chuyển ngày hôm sau',
            weather: '14-20°C · 🌸 Mát mẻ buổi tối',
          },
        ],
      },
      {
        dayNum: 2,
        title: 'Day 2 — Thứ Hai 4/5',
        subtitle: '称名滝 → ほたるいかミュージアム → 魚津水族館',
        specialties: [
          { emoji: '🦑', name: 'ほたるいか (Hotaruika)', where: 'ほたるいかミュージアム', desc: 'Mực phát sáng live — sashimi hoặc tempura, chỉ có mùa này' },
          { emoji: '🦐', name: '白エビ天丼', where: '魚津', desc: 'Tôm trắng Toyama chiên giòn — đặc sản #1' },
          { emoji: '🍦', name: 'Kem sữa 立山', where: '称名滝 area', desc: 'Kem sữa tươi vùng núi — bán tại quầy gần bãi đỗ' },
        ],
        segments: [
          { from: 'HOTEL R9', to: '称名滝', km: 45, time: '50min', mode: 'car' },
          { from: '称名滝', to: 'ほたるいかミュージアム', km: 50, time: '50min', mode: 'car' },
          { from: 'ほたるいか', to: '魚津水族館', km: 10, time: '10min', mode: 'car' },
          { from: '魚津', to: 'HOTEL R9', km: 20, time: '25min', mode: 'car' },
        ],
        stops: [
          {
            id: 'e-shomyo',
            name: '称名滝 (Shomyo Falls)',
            lat: 36.5733, lng: 137.4867,
            arrivalTime: '08:00',
            duration: 120,
            type: 'major',
            description: 'Thác cao nhất Nhật Bản (350m)! Tháng 5 tuyết tan → thác ハンノキ bên cạnh (500m) cũng chảy → double waterfall cực kỳ ấn tượng. Nắng sáng chiếu trực tiếp, có cầu vồng.',
            food: null,
            tips: 'Đi sáng sớm = đẹp nhất. Đi bộ 30 phút từ bãi đỗ, đường paved. Mang giày thoải mái.',
            weather: '10-16°C · 🌤️ Mát, nắng sáng đẹp',
          },
          {
            id: 'e-hotaruika',
            name: 'ほたるいかミュージアム',
            lat: 36.7632, lng: 137.3355,
            arrivalTime: '11:00',
            duration: 60,
            type: 'major',
            description: 'Bảo tàng mực phát sáng — xem live hotaruika phát sáng trong phòng tối. Chỉ có mùa 3-5 mới có live display! Touch pool cho trẻ.',
            food: 'Ăn trưa: hotaruika tempura tại quán bên cạnh',
            tips: 'Live display là highlight — đừng bỏ lỡ! Trẻ em rất thích phòng tối xem mực sáng.',
            weather: '15-20°C · 🌤️ Ven biển, gió mát',
          },
          {
            id: 'e-uozu',
            name: '魚津水族館 + ミラージュランド',
            lat: 36.7984, lng: 137.3882,
            arrivalTime: '12:30',
            duration: 120,
            type: 'major',
            description: 'Thủy cung cổ nhất Nhật Bản — nhỏ nhưng ấm cúng. Bên cạnh là ミラージュランド (đu quay, rides nhẹ cho trẻ, view biển).',
            food: '白エビ天丼 tại quán ven biển',
            tips: 'Xem show cá (giờ cố định). ミラージュランド rides ~300-400¥/lượt. Trẻ chơi thoải mái.',
            weather: '15-22°C · 🌤️ Ấm, ven biển gió mát',
          },
          {
            id: 'e-hotel-r9-d2',
            name: 'HOTEL R9 The Yard Kurobe',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '15:30',
            duration: 0,
            type: 'minor',
            description: 'Về hotel sớm, nghỉ ngơi thoải mái.',
            food: 'Ăn tối: hải sản tươi Toyama',
            tips: 'Về sớm — trẻ không mệt, người lớn thư giãn.',
            weather: '14-20°C · 🌙 Mát mẻ',
          },
        ],
      },
      {
        dayNum: 3,
        title: 'Day 3 — Thứ Ba 5/5',
        subtitle: '宇奈月 → トロッコ 11:48 → ひみ番屋街ランチ → 雨晴海岸 Golden Hour → 富岩運河スタバ夜景 → Tokyo',
        specialties: [
          { emoji: '🍦', name: 'Kem onsen', where: '宇奈月', desc: 'Kem mềm mịn bán dọc phố onsen — trẻ em mê' },
          { emoji: '🍡', name: '温泉たまご', where: '宇奈月', desc: 'Trứng luộc suối nóng, vỏ mềm lòng đào — ăn kèm muối' },
          { emoji: '🍣', name: 'ます寿し bento', where: 'SA đường về', desc: 'Sushi cá hồi ép truyền thống Toyama — mua mang đi ăn trên xe' },
        ],
        segments: [
          { from: 'HOTEL R9 (checkout 10:00)', to: '宇奈月駅', km: 20, time: '20min', mode: 'car' },
          { from: '宇奈月 (11:48発)', to: '笹平 往復', km: 16, time: '2h10', mode: 'trolley' },
          { from: '宇奈月 (~14:00)', to: 'ひみ番屋街 (氷見)', km: 60, time: '1h', mode: 'car' },
          { from: 'ひみ番屋街', to: '雨晴海岸', km: 15, time: '15min', mode: 'car' },
          { from: '雨晴海岸', to: '富岩運河環水公園', km: 20, time: '30min', mode: 'car' },
          { from: '富岩運河', to: '向島 (Tokyo)', km: 400, time: '5h', mode: 'car' },
        ],
        stops: [
          {
            id: 'e-unazuki',
            name: '宇奈月温泉 散策',
            lat: 36.8173, lng: 137.5841,
            arrivalTime: '10:20',
            duration: 85,
            type: 'minor',
            description: 'Checkout hotel 10:00 → hành lý để trên xe → lái đến 宇奈月駅 (20 phút). Tản bộ phố onsen trước khi lên tàu. Ngâm chân ashiyu miễn phí. Mua snack ăn trên tàu.',
            food: 'Kem onsen · 温泉たまご · bánh mochi · onigiri cho lên tàu',
            tips: 'Checkout 10:00 → xe đến 宇奈月駅 10:20. Tàu Trolley lên 11:48 — đúng giờ ra ga, không trễ!',
            weather: '14-20°C · 🌸 Dễ chịu',
          },
          {
            id: 'e-trolley',
            name: '黒部峡谷トロッコ (宇奈月〜笹平)',
            lat: 36.8150, lng: 137.5860,
            arrivalTime: '11:48',
            duration: 130,
            type: 'major',
            description: 'Tàu trolley hẻm V-shape Kurobe — hẻm núi sâu nhất Nhật Bản. 2026: đến 笹平 (5/3~5/9). Khứ hồi ~2h10. Về đến 宇奈月 khoảng 14:00.',
            food: 'Mua snack tại 宇奈月駅 trước khi lên tàu',
            tips: '⚠️ Vé 11:48 — ĐÚNG GIỜ, không trễ! Đặt vé từ 1/4 tại torokko-yoyaku.com. Chọn toa mở (普通客車). Ngồi bên PHẢI chiều đi để ngắm sông tốt nhất.',
            weather: '14-20°C · 🌿 Hẻm núi mát mẻ, cảnh xanh',
          },
          {
            id: 'e-himi',
            name: 'ひみ番屋街 — 氷見漁港場外市場',
            lat: 36.8567, lng: 136.9870,
            arrivalTime: '15:00',
            duration: 90,
            type: 'major',
            description: '氷見漁港直送の海産物マーケット！白エビ天丼・氷見うどん・海鮮丼で遅めのランチ。子どもたちは広い港エリアを走り回れる。富山みやげの最終調達にも最適。雨晴海岸まで車で15分。',
            food: '🍜 氷見うどん · 🦐 白エビ天丼 · 🐟 海鮮丼 · Omiyage: 氷見牛・海産物',
            tips: '子連れに最高のスポット — 広い屋外エリアで自由に動ける。駐車場無料。トイレあり。雨晴海岸まで15分。',
            weather: '15-20°C · 🌊 港の海風',
          },
          {
            id: 'e-ameharashi',
            name: '雨晴海岸 (Ameharashi Coast)',
            lat: 36.7740, lng: 137.0240,
            arrivalTime: '17:00',
            duration: 100,
            type: 'major',
            description: '富山湾 + 立山連峰 + 赤いJR氷見線の聖地！日没18:41の1時間40分前に到着しゴールデンアワーをフルに楽しむ。17:00〜18:41まで山の色が刻々と変化する絶景タイム。3家族で記念撮影の絶好チャンス。',
            food: 'ひみ番屋街で買ったおやつ · 近くのカフェ',
            tips: '📸 17:00着でゴールデンアワーをフル確保。JR氷見線の時刻を事前確認 → 列車が来る瞬間にシャッター。北陸道 高岡ICへすぐ。駐車場無料。',
            weather: '14-18°C · 🌅 ゴールデンアワー → 日没18:41 → 山が黄金色に',
            images: [
              { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Ameharashi_Coast.jpg/640px-Ameharashi_Coast.jpg', alt: '雨晴海岸 富山湾 立山連峰' },
            ],
          },
          {
            id: 'e-kansui',
            name: '富岩運河環水公園 + 世界一美しいスタバ',
            lat: 36.6983, lng: 137.2113,
            arrivalTime: '19:30',
            duration: 75,
            type: 'major',
            description: '夜の富岩運河環水公園！天門橋のライトアップが水面に映り込む幻想的な夜景。「世界一美しいスタバ」で日没後の絶景を楽しむ。日没(18:41)から約50分後 — ライトアップが最高潮に。',
            food: 'スターバックス コーヒー 富山環水公園店 (22:30まで営業) · テラス席で夜風を感じながら',
            tips: '📸 撮影ベスト: スタバを横から写す構図 + 天門橋 + 水面リフレクション。ライトアップ22:00まで、天門橋展望塔21:00まで。駐車場無料。',
            weather: '14-18°C · 🌃 夜景 — ライトアップ22時まで',
          },
          {
            id: 'e-return',
            name: 'Xuất phát về Tokyo',
            lat: 35.7180, lng: 139.8130,
            arrivalTime: '21:00',
            duration: 0,
            type: 'major',
            description: '北陸道 → 関越道で帰路。~5h。向島到着 2:00~2:30 AM。スタバで夜景を楽しんだ後、子どもたちは車内で熟睡。GW Uターンラッシュのピーク後なので渋滞ほぼなし。',
            food: '出発前にコンビニで夜食・飲み物 · SAでます寿しbento',
            tips: '21時出発はUターンラッシュ後 — 渋滞なし。SA休憩1〜2回。運転交代を忘れずに。向島着は約2:30 AM。',
            weather: '14°C → 18°C · 🌙 夜の北陸道 — 空いていて走りやすい',
          },
        ]
      },
    ],
  },

  D: {
    name: '白馬 Alps Gondola + Trolley',
    color: '#C0392B',
    subtitle: 'Tulip 350万本 → Gondola đỉnh Alps tuyết trắng → Trolley → ほたるいか → 称名滝',
    route: 'チューリップフェア → 白馬村 → ゴンドラ → トロッコ → 称名滝',
    highlights: [
      { icon: '🌷', text: 'となみチューリップフェア 350万本 — trên đường đến 白馬' },
      { icon: '🏔️', text: '白馬 八方尾根ゴンドラ — lên 1,830m, Alps tuyết trắng' },
      { icon: '🚂', text: 'Trolley hẻm V-shape Kurobe + ほたるいか + 称名滝' },
    ],
    totalKm: 1510,
    routeGo: '関越道 → 北陸道 → 砺波IC → 黒部IC → 大町 → 白馬 (430km · 6h)',
    routeReturn: '北陸道 → 関越道 (430km · 5h) — an toàn lái đêm',
    routeOptions: [
      '✅ 関越道→北陸道→砺波(tulip)→黒部→大町→白馬 — Ghé tulip ON ROUTE! (430km · 6h)',
      '中央道→長野道→白馬→砺波(tulip detour) — Đi trước 白馬 rồi vòng qua 砺波. (400km+50km detour)',
      '関越道→上信越道→長野→白馬→糸魚川→砺波 — Dài nhưng cảnh đẹp. (460km · 7h)',
    ],
    gallery: [
      // Thêm ảnh: { src: 'images/plan-d/ten-anh.jpg', caption: 'Mô tả', spot: 'Tên điểm đến' }
    ],
    days: [
      {
        dayNum: 1,
        title: 'Day 1 — Chủ Nhật 3/5',
        subtitle: '向島 → チューリップフェア → 白馬村 → HOTEL R9',
        specialties: [
          { emoji: '🌷', name: 'チューリップソフト', where: '砺波 フェア', desc: 'Kem tulip ngọt dịu — ăn giữa 350万本 hoa' },
          { emoji: '🍖', name: 'Shinshu beef / soba', where: '白馬 village', desc: 'Bò Shinshu mềm thơm & soba kiều mạch Nagano' },
          { emoji: '🍺', name: 'Hakuba Brewing beer', where: '白馬 village', desc: 'Bia craft địa phương Hakuba — uống tối tại village' },
        ],
        segments: [
          { from: '向島', to: 'チューリップフェア (砺波)', km: 400, time: '5h30', mode: 'car' },
          { from: 'チューリップフェア', to: '白馬 (via 黒部→大町)', km: 130, time: '2h', mode: 'car' },
          { from: '白馬村', to: 'HOTEL R9 (via R148→糸魚川)', km: 100, time: '2h', mode: 'car' },
        ],
        stops: [
          {
            id: 'd-d1-depart',
            name: 'Tập kết nhà anh Hà (向島)',
            lat: 35.7180, lng: 139.8130,
            arrivalTime: '06:00',
            duration: 0,
            type: 'minor',
            description: '3 xe tập kết tại 墨田区向島5-35-11. Đổ xăng → 首都高 → 関越道 hướng Toyama.',
            food: null,
            tips: '2 nhà đến trước 5:50. Plan D đi 関越道→北陸道 (cùng hướng Plan B nhưng khác điểm đến).',
            weather: '18-24°C · 🌤️ Tokyo ấm',
          },
          {
            id: 'd-tulip',
            name: 'となみチューリップフェア 2026',
            lat: 36.6477, lng: 136.9635,
            arrivalTime: '10:30',
            duration: 90,
            type: 'major',
            description: '300品種350万本のチューリップ！「花の大谷」高さ4m×30m、水上花壇、チューリップタワー。5/5こどもの日は中学生以下無料！',
            food: 'チューリップソフトクリーム · 軽食各所',
            tips: '砺波ICから車で5分。GW混雑 — 10:30前着推奨。5/5中学生以下無料！Ghé 1h30 rồi đi 白馬.',
            weather: '14-20°C · 🌷 チューリップ満開',
          },
          {
            id: 'd-hakuba-village',
            name: '白馬村 散策 (tối)',
            lat: 36.6984, lng: 137.8617,
            arrivalTime: '14:30',
            duration: 120,
            type: 'major',
            description: 'Tản bộ Hakuba Village — quán cafe, shop đồ outdoor, không khí resort Âu châu giữa Nhật Bản. Dãy Alps tuyết trắng phía sau. Nghỉ chân thoải mái sau ngày đường.',
            food: 'Shinshu soba · thịt bò Shinshu nướng · bia craft Hakuba Brewing',
            tips: 'Nhiều quán có terrace nhìn ra núi Alps. Bữa tối tại izakaya village rất ngon.',
            weather: '10-18°C · 🏔️ Thung lũng Alps, trong lành',
          },
          {
            id: 'd-hotel-r9-d1',
            name: 'HOTEL R9 The Yard Kurobe',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '18:30',
            duration: 0,
            type: 'major',
            description: 'Check-in. Ngày 1 di chuyển nhiều — nghỉ ngơi sớm.',
            food: 'Ăn tối đã có tại 白馬村 hoặc quán gần hotel',
            tips: 'Route 白馬→R148→糸魚川→北陸道→黒部IC. Đường R148 đẹp, trẻ ngủ trên xe.',
            weather: '14-20°C · 🌙 Mát mẻ',
          },
        ],
      },
      {
        dayNum: 2,
        title: 'Day 2 — Thứ Hai 4/5',
        subtitle: '白馬ゴンドラ → トロッコ → 宇奈月温泉 → ほたるいか',
        specialties: [
          { emoji: '🍱', name: 'Gondola top lunch', where: '白馬 山頂', desc: 'Ăn trưa nhà hàng trên đỉnh núi 1,830m — view Alps 360 độ' },
          { emoji: '🍦', name: 'Kem onsen', where: '宇奈月', desc: 'Kem mềm mịn sau Trolley — phần thưởng xứng đáng' },
          { emoji: '🦑', name: 'ほたるいか sashimi', where: 'ほたるいかミュージアム', desc: 'Mực phát sáng Toyama Bay tươi nhất' },
        ],
        segments: [
          { from: 'HOTEL R9', to: '白馬 八方尾根', km: 70, time: '1h30', mode: 'car' },
          { from: '白馬', to: '宇奈月 (via R148)', km: 100, time: '2h', mode: 'car' },
          { from: 'トロッコ往復', to: '笹平', km: 16, time: '2h', mode: 'trolley' },
          { from: '宇奈月', to: 'ほたるいかミュージアム', km: 35, time: '40min', mode: 'car' },
          { from: 'ほたるいか', to: 'HOTEL R9', km: 20, time: '25min', mode: 'car' },
        ],
        stops: [
          {
            id: 'd-gondola',
            name: '白馬 八方尾根ゴンドラ',
            lat: 36.6983, lng: 137.8320,
            arrivalTime: '08:00',
            duration: 120,
            type: 'major',
            description: 'Gondola lên 1,830m — toàn cảnh dãy Alps Bắc phủ tuyết trắng + thung lũng xanh bên dưới. Cảm giác ở giữa tuyết mà không cần leo núi! Trẻ em phấn khích.',
            food: 'Ăn sáng tại hotel trước. Có nhà hàng tại đỉnh gondola.',
            tips: 'Lên gondola sáng sớm — ít người + ánh sáng đẹp. Mang áo gió dày — trên đỉnh lạnh hơn 10°C.',
            weather: '5-15°C · 🏔️ Mát, cần áo gió dày trên đỉnh',
          },
          {
            id: 'd-trolley',
            name: '黒部峡谷トロッコ (宇奈月〜笹平)',
            lat: 36.8150, lng: 137.5860,
            arrivalTime: '13:00',
            duration: 150,
            type: 'major',
            description: 'Hẻm V-shape sâu nhất Nhật Bản — vách đá dựng đứng, sông xanh ngọc bích. 2026: vận hành đến 笹平. Khứ hồi ~2h.',
            food: 'Bento mua tại ga hoặc ăn nhẹ trên tàu',
            tips: '⚠️ Plan D trolley vào ngày 4/5 — cần đặt vé riêng (khác vé ngày 5/5). Chọn toa mở (普通客車). Ngồi bên PHẢI chiều đi.',
            weather: '14-20°C · 🌿 Hẻm núi mát mẻ',
          },
          {
            id: 'd-unazuki',
            name: '宇奈月温泉 散策',
            lat: 36.8173, lng: 137.5841,
            arrivalTime: '15:30',
            duration: 60,
            type: 'minor',
            description: 'Tản bộ phố onsen, ngâm chân ashiyu miễn phí. Mua omiyage.',
            food: 'Kem onsen · 温泉たまご',
            tips: 'Nhiều ashiyu dọc phố. Trẻ em rất thích!',
            weather: '14-20°C · 🌸 Dễ chịu',
          },
          {
            id: 'd-hotaruika',
            name: 'ほたるいかミュージアム',
            lat: 36.7632, lng: 137.3355,
            arrivalTime: '17:00',
            duration: 75,
            type: 'major',
            description: 'Phòng tối xem mực xanh phát sáng — độc nhất vô nhị. Touch pool cho trẻ.',
            food: 'ほたるいか sashimi / tempura tươi',
            tips: 'Live display phòng tối là highlight. Đặt trước nếu được.',
            weather: '15-20°C · 🌙 Mát tối',
          },
          {
            id: 'd-hotel-r9-d2',
            name: 'HOTEL R9 The Yard Kurobe',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '18:45',
            duration: 0,
            type: 'minor',
            description: 'Về hotel. Ngày 2 dày nhất — nghỉ sớm!',
            food: 'Ăn tối đã có tại ほたるいかミュージアム hoặc konbini',
            tips: null,
            weather: '14-20°C · 🌙 Mát mẻ',
          },
        ],
      },
      {
        dayNum: 3,
        title: 'Day 3 — Thứ Ba 5/5',
        subtitle: '称名滝 → 魚津水族館 → ひみ番屋街 → 雨晴海岸 Golden Hour → 富岩運河スタバ夜景 → Tokyo',
        specialties: [
          { emoji: '🍦', name: 'Kem sữa 立山', where: '称名滝 area', desc: 'Kem tươi vùng núi — quầy gần bãi đỗ' },
          { emoji: '🦐', name: '白エビ天丼', where: '魚津', desc: 'Tôm trắng Toyama — ăn trưa tươi ngon' },
          { emoji: '🍣', name: 'ます寿し bento', where: 'SA đường về', desc: 'Sushi cá hồi ép — mua mang trên xe' },
        ],
        segments: [
          { from: 'HOTEL R9', to: '称名滝', km: 45, time: '50min', mode: 'car' },
          { from: '称名滝', to: '魚津水族館', km: 55, time: '55min', mode: 'car' },
          { from: '魚津', to: 'HOTEL R9', km: 20, time: '25min', mode: 'car' },
          { from: 'HOTEL R9', to: '向島 (Tokyo)', km: 430, time: '5h', mode: 'car' },
        ],
        stops: [
          {
            id: 'd-shomyo',
            name: '称名滝 + ハンノキ滝',
            lat: 36.5733, lng: 137.4867,
            arrivalTime: '08:00',
            duration: 90,
            type: 'major',
            description: '2 thác V-shape: 称名滝 (350m) + ハンノキ滝 (500m). Chỉ có mùa tuyết tan! Sáng sớm = cầu vồng tự nhiên ngay trước mặt. Đường paved 30 phút từ bãi đỗ.',
            food: 'Kem sữa tươi tại レストハウス称名',
            tips: 'Đến sớm nhất — tháng 5 nước tuyết tan = thác cực mạnh. Mang áo mưa mỏng!',
            weather: '10-16°C · 🌤️ Mát, nắng sáng → cầu vồng',
          },
          {
            id: 'd-uozu',
            name: '魚津水族館 + ミラージュランド',
            lat: 36.7984, lng: 137.3882,
            arrivalTime: '10:30',
            duration: 90,
            type: 'major',
            description: 'Thủy cung cổ nhất Nhật Bản + rides nhẹ nhìn biển Toyama. Ngày cuối nhẹ nhàng cho trẻ.',
            food: '白エビ天丼 tại quán ven biển — ăn trưa',
            tips: 'Xem show cá (giờ cố định). Rides nhẹ cho bé.',
            weather: '15-22°C · 🌤️ Ấm, ven biển',
          },
          {
            id: 'd-himi',
            name: 'ひみ番屋街 — 氷見漁港場外市場',
            lat: 36.8567, lng: 136.9870,
            arrivalTime: '13:30',
            duration: 75,
            type: 'major',
            description: '氷見漁港直送の海産物マーケット！雰囲気のある漁港エリアで子どもたちが走り回れる。富山みやげの最終調達。雨晴海岸まで車で15分。',
            food: '🍜 氷見うどん · 🦐 白エビ天丼 · Omiyage: 氷見牛・海産物',
            tips: '子連れに最高のスポット。駐車場無料。雨晴海岸まで15分。',
            weather: '15-20°C · 🌊 港の海風',
          },
          {
            id: 'd-ameharashi',
            name: '雨晴海岸 (Ameharashi Coast)',
            lat: 36.7740, lng: 137.0240,
            arrivalTime: '17:00',
            duration: 100,
            type: 'major',
            description: '富山湾 + 立山連峰 + 赤いJR氷見線の聖地！日没18:41の1時間40分前に到着しゴールデンアワーをフルに楽しむ。',
            food: 'ひみ番屋街で買ったおやつ',
            tips: '📸 17:00着でゴールデンアワーをフル確保。JR氷見線の時刻を事前確認 → 列車が来る瞬間にシャッター。駐車場無料。',
            weather: '14-18°C · 🌅 ゴールデンアワー → 日没18:41',
            images: [
              { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Ameharashi_Coast.jpg/640px-Ameharashi_Coast.jpg', alt: '雨晴海岸 富山湾 立山連峰' },
            ],
          },
          {
            id: 'd-kansui',
            name: '富岩運河環水公園 + 世界一美しいスタバ',
            lat: 36.6983, lng: 137.2113,
            arrivalTime: '19:30',
            duration: 75,
            type: 'major',
            description: '夜の富岩運河環水公園！天門橋のライトアップが水面に映り込む幻想的な夜景。「世界一美しいスタバ」で日没後の絶景を楽しむ。',
            food: 'スターバックス コーヒー 富山環水公園店 (22:30まで営業)',
            tips: '📸 撮影ベスト: スタバを横から写す構図 + 天門橋 + 水面リフレクション。ライトアップ22:00まで。駐車場無料。',
            weather: '14-18°C · 🌃 夜景 — ライトアップ22時まで',
          },
          {
            id: 'd-return',
            name: 'Xuất phát về Tokyo',
            lat: 35.7180, lng: 139.8130,
            arrivalTime: '21:00',
            duration: 0,
            type: 'major',
            description: '北陸道 → 関越道で帰路。~5h。向島到着 2:00~2:30 AM。スタバで夜景を楽しんだ後、子どもたちは車内で熟睡。',
            food: '出発前にコンビニで夜食・飲み物 · SAでます寿しbento',
            tips: '21時出発はUターンラッシュ後 — 渋滞なし。SA休憩1〜2回。運転交代を忘れずに。',
            weather: '14°C → 18°C · 🌙 夜の北陸道 — 空いていて走りやすい',
          },
        ],
      },
    ],
  },

  C: {
    name: '五箇山 & 称名滝',
    color: '#5B6ABF',
    subtitle: 'Thác cao nhất Nhật + UNESCO village + Trolley — không cần vé Alpine, tiết kiệm',
    route: '五箇山 → 称名滝 → 魚津水族館 → トロッコ',
    highlights: [
      { icon: '💧', text: '称名滝 — thác cao nhất Nhật Bản (350m)' },
      { icon: '🏘️', text: '五箇山 UNESCO — yên tĩnh, ít đông' },
      { icon: '💰', text: 'Không cần vé Alpine Route — tiết kiệm ~¥55,000' },
    ],
    totalKm: 1210,
    routeGo: '上信越道 + 北陸道 (380km · 5h30) — cảnh núi→biển đẹp',
    routeReturn: '北陸道 → 関越道 (430km · 5h) — an toàn lái đêm, ít cua',
    routeOptions: [
      '✅ 上信越道 + 北陸道 — Ngắn nhất đến 五箇山. Cảnh núi→biển đẹp. (380km · 5h30)',
      '関越道 + 北陸道 via 長岡 — Dễ lái nhất, ít cua. Trẻ ít say. (430km · 6h)',
      '上信越道 xuyên Nagano — Cảnh núi đẹp nhất nhưng cua nhiều, trẻ dễ say. (360km · 5h30)',
    ],
    gallery: [
      // Thêm ảnh: { src: 'images/plan-c/ten-anh.jpg', caption: 'Mô tả', spot: 'Tên điểm đến' }
    ],
    days: [
      {
        dayNum: 1,
        title: 'Day 1 — Chủ Nhật 3/5',
        subtitle: '向島 → 五箇山 → HOTEL R9',
        specialties: [
          { emoji: '🧈', name: '五箇山豆腐', where: '五箇山', desc: 'Đậu hũ cứng nướng than, đậm đà — đặc sản UNESCO village' },
          { emoji: '🐟', name: '岩魚塩焼き', where: '五箇山', desc: 'Cá suối nướng muối thơm giòn, trẻ em thích' },
          { emoji: '🍜', name: '富山ブラックラーメン', where: 'Kurobe', desc: 'Ramen đen xì dầu đậm đặc — ăn tối tại Kurobe' },
        ],
        segments: [
          { from: '向島', to: '五箇山', km: 380, time: '5h30', mode: 'car' },
          { from: '五箇山', to: 'HOTEL R9', km: 110, time: '1h30', mode: 'car' },
        ],
        stops: [
          {
            id: 'e-d1-depart',
            name: 'Tập kết nhà anh Hà (向島)',
            lat: 35.7180, lng: 139.8130,
            arrivalTime: '06:00',
            duration: 0,
            type: 'minor',
            description: '3 xe tập kết tại 墨田区向島5-35-11. Đổ xăng trên Meiji-dori → 向島入口 → 首都高6号 → 関越道.',
            food: null,
            tips: '2 nhà đến trước 5:50. Cùng xuất phát 6:00.',
            weather: '18-24°C · 🌤️ Tokyo ấm',
          },
          {
            id: 'e-gokayama',
            name: '五箇山 相倉集落',
            lat: 36.4260, lng: 136.9355,
            arrivalTime: '12:00',
            duration: 90,
            type: 'major',
            description: 'Làng mái tranh gassho UNESCO yên tĩnh nhất. Trẻ em thích khám phá nhà 3 tầng. Ít đông hơn 白川郷 nhiều.',
            food: '五箇山豆腐 · 岩魚塩焼き',
            tips: 'Exit 北陸道 tại 砺波IC → 東海北陸道 → 五箇山IC. Ghé trên đường, không vòng.',
            weather: '13-18°C · 🌤️ Ấm, có thể mưa nhẹ',
          },
          {
            id: 'e-hotel-r9-d1',
            name: 'HOTEL R9 The Yard Kurobe',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '15:30',
            duration: 0,
            type: 'major',
            description: 'Check-in khách sạn. Nghỉ ngơi sau chặng đường dài.',
            food: 'Ăn tối tại nhà hàng quanh Kurobe',
            tips: 'Gần Kurobe IC, tiện di chuyển ngày hôm sau',
            weather: '14-20°C · 🌸 Mát mẻ buổi tối',
          },
        ],
      },
      {
        dayNum: 2,
        title: 'Day 2 — Thứ Hai 4/5',
        subtitle: '称名滝 → ほたるいかミュージアム → 魚津水族館',
        specialties: [
          { emoji: '🦑', name: 'ほたるいか (Hotaruika)', where: 'ほたるいかミュージアム', desc: 'Mực phát sáng live — sashimi hoặc tempura, chỉ có mùa này' },
          { emoji: '🦐', name: '白エビ天丼', where: '魚津', desc: 'Tôm trắng Toyama chiên giòn — đặc sản #1' },
          { emoji: '🍦', name: 'Kem sữa 立山', where: '称名滝 area', desc: 'Kem sữa tươi vùng núi — bán tại quầy gần bãi đỗ' },
        ],
        segments: [
          { from: 'HOTEL R9', to: '称名滝', km: 45, time: '50min', mode: 'car' },
          { from: '称名滝', to: 'ほたるいかミュージアム', km: 50, time: '50min', mode: 'car' },
          { from: 'ほたるいか', to: '魚津水族館', km: 10, time: '10min', mode: 'car' },
          { from: '魚津', to: 'HOTEL R9', km: 20, time: '25min', mode: 'car' },
        ],
        stops: [
          {
            id: 'e-shomyo',
            name: '称名滝 (Shomyo Falls)',
            lat: 36.5733, lng: 137.4867,
            arrivalTime: '08:00',
            duration: 120,
            type: 'major',
            description: 'Thác cao nhất Nhật Bản (350m)! Tháng 5 tuyết tan → thác ハンノキ bên cạnh (500m) cũng chảy → double waterfall cực kỳ ấn tượng. Nắng sáng chiếu trực tiếp, có cầu vồng.',
            food: null,
            tips: 'Đi sáng sớm = đẹp nhất. Đi bộ 30 phút từ bãi đỗ, đường paved. Mang giày thoải mái.',
            weather: '10-16°C · 🌤️ Mát, nắng sáng đẹp',
          },
          {
            id: 'e-hotaruika',
            name: 'ほたるいかミュージアム',
            lat: 36.7632, lng: 137.3355,
            arrivalTime: '11:00',
            duration: 60,
            type: 'major',
            description: 'Bảo tàng mực phát sáng — xem live hotaruika phát sáng trong phòng tối. Chỉ có mùa 3-5 mới có live display! Touch pool cho trẻ.',
            food: 'Ăn trưa: hotaruika tempura tại quán bên cạnh',
            tips: 'Live display là highlight — đừng bỏ lỡ! Trẻ em rất thích phòng tối xem mực sáng.',
            weather: '15-20°C · 🌤️ Ven biển, gió mát',
          },
          {
            id: 'e-uozu',
            name: '魚津水族館 + ミラージュランド',
            lat: 36.7984, lng: 137.3882,
            arrivalTime: '12:30',
            duration: 120,
            type: 'major',
            description: 'Thủy cung cổ nhất Nhật Bản — nhỏ nhưng ấm cúng. Bên cạnh là ミラージュランド (đu quay, rides nhẹ cho trẻ, view biển).',
            food: '白エビ天丼 tại quán ven biển',
            tips: 'Xem show cá (giờ cố định). ミラージュランド rides ~300-400¥/lượt. Trẻ chơi thoải mái.',
            weather: '15-22°C · 🌤️ Ấm, ven biển gió mát',
          },
          {
            id: 'e-hotel-r9-d2',
            name: 'HOTEL R9 The Yard Kurobe',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '15:30',
            duration: 0,
            type: 'minor',
            description: 'Về hotel sớm, nghỉ ngơi thoải mái.',
            food: 'Ăn tối: hải sản tươi Toyama',
            tips: 'Về sớm — trẻ không mệt, người lớn thư giãn.',
            weather: '14-20°C · 🌙 Mát mẻ',
          },
        ],
      },
      {
        dayNum: 3,
        title: 'Day 3 — Thứ Ba 5/5',
        subtitle: '宇奈月 → トロッコ 11:48 → ひみ番屋街ランチ → 雨晴海岸 Golden Hour → 富岩運河スタバ夜景 → Tokyo',
        specialties: [
          { emoji: '🍦', name: 'Kem onsen', where: '宇奈月', desc: 'Kem mềm mịn bán dọc phố onsen — trẻ em mê' },
          { emoji: '🍡', name: '温泉たまご', where: '宇奈月', desc: 'Trứng luộc suối nóng, vỏ mềm lòng đào — ăn kèm muối' },
          { emoji: '🍣', name: 'ます寿し bento', where: 'SA đường về', desc: 'Sushi cá hồi ép truyền thống Toyama — mua mang đi ăn trên xe' },
        ],
        segments: [
          { from: 'HOTEL R9 (checkout 10:00)', to: '宇奈月駅', km: 20, time: '20min', mode: 'car' },
          { from: '宇奈月 (11:48発)', to: '笹平 往復', km: 16, time: '2h10', mode: 'trolley' },
          { from: '宇奈月 (~14:00)', to: 'ひみ番屋街 (氷見)', km: 60, time: '1h', mode: 'car' },
          { from: 'ひみ番屋街', to: '雨晴海岸', km: 15, time: '15min', mode: 'car' },
          { from: '雨晴海岸', to: '富岩運河環水公園', km: 20, time: '30min', mode: 'car' },
          { from: '富岩運河', to: '向島 (Tokyo)', km: 400, time: '5h', mode: 'car' },
        ],
        stops: [
          {
            id: 'e-unazuki',
            name: '宇奈月温泉 散策',
            lat: 36.8173, lng: 137.5841,
            arrivalTime: '10:20',
            duration: 85,
            type: 'minor',
            description: 'Checkout hotel 10:00 → hành lý để trên xe → lái đến 宇奈月駅 (20 phút). Tản bộ phố onsen trước khi lên tàu. Ngâm chân ashiyu miễn phí. Mua snack ăn trên tàu.',
            food: 'Kem onsen · 温泉たまご · bánh mochi · onigiri cho lên tàu',
            tips: 'Checkout 10:00 → xe đến 宇奈月駅 10:20. Tàu Trolley lên 11:48 — đúng giờ ra ga, không trễ!',
            weather: '14-20°C · 🌸 Dễ chịu',
          },
          {
            id: 'e-trolley',
            name: '黒部峡谷トロッコ (宇奈月〜笹平)',
            lat: 36.8150, lng: 137.5860,
            arrivalTime: '11:48',
            duration: 130,
            type: 'major',
            description: 'Tàu trolley hẻm V-shape Kurobe — hẻm núi sâu nhất Nhật Bản. 2026: đến 笹平 (5/3~5/9). Khứ hồi ~2h10. Về đến 宇奈月 khoảng 14:00.',
            food: 'Mua snack tại 宇奈月駅 trước khi lên tàu',
            tips: '⚠️ Vé 11:48 — ĐÚNG GIỜ, không trễ! Đặt vé từ 1/4 tại torokko-yoyaku.com. Chọn toa mở (普通客車). Ngồi bên PHẢI chiều đi để ngắm sông tốt nhất.',
            weather: '14-20°C · 🌿 Hẻm núi mát mẻ, cảnh xanh',
          },
          {
            id: 'e-himi',
            name: 'ひみ番屋街 — 氷見漁港場外市場',
            lat: 36.8567, lng: 136.9870,
            arrivalTime: '15:00',
            duration: 90,
            type: 'major',
            description: '氷見漁港直送の海産物マーケット！白エビ天丼・氷見うどん・海鮮丼で遅めのランチ。子どもたちは広い港エリアを走り回れる。富山みやげの最終調達にも最適。雨晴海岸まで車で15分。',
            food: '🍜 氷見うどん · 🦐 白エビ天丼 · 🐟 海鮮丼 · Omiyage: 氷見牛・海産物',
            tips: '子連れに最高のスポット — 広い屋外エリアで自由に動ける。駐車場無料。トイレあり。雨晴海岸まで15分。',
            weather: '15-20°C · 🌊 港の海風',
          },
          {
            id: 'e-ameharashi',
            name: '雨晴海岸 (Ameharashi Coast)',
            lat: 36.7740, lng: 137.0240,
            arrivalTime: '17:00',
            duration: 100,
            type: 'major',
            description: '富山湾 + 立山連峰 + 赤いJR氷見線の聖地！日没18:41の1時間40分前に到着しゴールデンアワーをフルに楽しむ。17:00〜18:41まで山の色が刻々と変化する絶景タイム。3家族で記念撮影の絶好チャンス。',
            food: 'ひみ番屋街で買ったおやつ · 近くのカフェ',
            tips: '📸 17:00着でゴールデンアワーをフル確保。JR氷見線の時刻を事前確認 → 列車が来る瞬間にシャッター。北陸道 高岡ICへすぐ。駐車場無料。',
            weather: '14-18°C · 🌅 ゴールデンアワー → 日没18:41 → 山が黄金色に',
            images: [
              { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Ameharashi_Coast.jpg/640px-Ameharashi_Coast.jpg', alt: '雨晴海岸 富山湾 立山連峰' },
            ],
          },
          {
            id: 'e-kansui',
            name: '富岩運河環水公園 + 世界一美しいスタバ',
            lat: 36.6983, lng: 137.2113,
            arrivalTime: '19:30',
            duration: 75,
            type: 'major',
            description: '夜の富岩運河環水公園！天門橋のライトアップが水面に映り込む幻想的な夜景。「世界一美しいスタバ」で日没後の絶景を楽しむ。日没(18:41)から約50分後 — ライトアップが最高潮に。',
            food: 'スターバックス コーヒー 富山環水公園店 (22:30まで営業) · テラス席で夜風を感じながら',
            tips: '📸 撮影ベスト: スタバを横から写す構図 + 天門橋 + 水面リフレクション。ライトアップ22:00まで、天門橋展望塔21:00まで。駐車場無料。',
            weather: '14-18°C · 🌃 夜景 — ライトアップ22時まで',
          },
          {
            id: 'e-return',
            name: 'Xuất phát về Tokyo',
            lat: 35.7180, lng: 139.8130,
            arrivalTime: '21:00',
            duration: 0,
            type: 'major',
            description: '北陸道 → 関越道で帰路。~5h。向島到着 2:00~2:30 AM。スタバで夜景を楽しんだ後、子どもたちは車内で熟睡。GW Uターンラッシュのピーク後なので渋滞ほぼなし。',
            food: '出発前にコンビニで夜食・飲み物 · SAでます寿しbento',
            tips: '21時出発はUターンラッシュ後 — 渋滞なし。SA休憩1〜2回。運転交代を忘れずに。向島着は約2:30 AM。',
            weather: '14°C → 18°C · 🌙 夜の北陸道 — 空いていて走りやすい',
          },
        ]
      },
    ],
  },

  D: {
    name: '白馬 Alps Gondola + Trolley',
    color: '#C0392B',
    subtitle: 'Tulip 350万本 → Gondola đỉnh Alps tuyết trắng → Trolley → ほたるいか → 称名滝',
    route: 'チューリップフェア → 白馬村 → ゴンドラ → トロッコ → 称名滝',
    highlights: [
      { icon: '🌷', text: 'となみチューリップフェア 350万本 — trên đường đến 白馬' },
      { icon: '🏔️', text: '白馬 八方尾根ゴンドラ — lên 1,830m, Alps tuyết trắng' },
      { icon: '🚂', text: 'Trolley hẻm V-shape Kurobe + ほたるいか + 称名滝' },
    ],
    totalKm: 1510,
    routeGo: '関越道 → 北陸道 → 砺波IC → 黒部IC → 大町 → 白馬 (430km · 6h)',
    routeReturn: '北陸道 → 関越道 (430km · 5h) — an toàn lái đêm',
    routeOptions: [
      '✅ 関越道→北陸道→砺波(tulip)→黒部→大町→白馬 — Ghé tulip ON ROUTE! (430km · 6h)',
      '中央道→長野道→白馬→砺波(tulip detour) — Đi trước 白馬 rồi vòng qua 砺波. (400km+50km detour)',
      '関越道→上信越道→長野→白馬→糸魚川→砺波 — Dài nhưng cảnh đẹp. (460km · 7h)',
    ],
    gallery: [
      // Thêm ảnh: { src: 'images/plan-d/ten-anh.jpg', caption: 'Mô tả', spot: 'Tên điểm đến' }
    ],
    days: [
      {
        dayNum: 1,
        title: 'Day 1 — Chủ Nhật 3/5',
        subtitle: '向島 → チューリップフェア → 白馬村 → HOTEL R9',
        specialties: [
          { emoji: '🌷', name: 'チューリップソフト', where: '砺波 フェア', desc: 'Kem tulip ngọt dịu — ăn giữa 350万本 hoa' },
          { emoji: '🍖', name: 'Shinshu beef / soba', where: '白馬 village', desc: 'Bò Shinshu mềm thơm & soba kiều mạch Nagano' },
          { emoji: '🍺', name: 'Hakuba Brewing beer', where: '白馬 village', desc: 'Bia craft địa phương Hakuba — uống tối tại village' },
        ],
        segments: [
          { from: '向島', to: 'チューリップフェア (砺波)', km: 400, time: '5h30', mode: 'car' },
          { from: 'チューリップフェア', to: '白馬 (via 黒部→大町)', km: 130, time: '2h', mode: 'car' },
          { from: '白馬村', to: 'HOTEL R9 (via R148→糸魚川)', km: 100, time: '2h', mode: 'car' },
        ],
        stops: [
          {
            id: 'd-d1-depart',
            name: 'Tập kết nhà anh Hà (向島)',
            lat: 35.7180, lng: 139.8130,
            arrivalTime: '06:00',
            duration: 0,
            type: 'minor',
            description: '3 xe tập kết tại 墨田区向島5-35-11. Đổ xăng → 首都高 → 関越道 hướng Toyama.',
            food: null,
            tips: '2 nhà đến trước 5:50. Plan D đi 関越道→北陸道 (cùng hướng Plan B nhưng khác điểm đến).',
            weather: '18-24°C · 🌤️ Tokyo ấm',
          },
          {
            id: 'd-tulip',
            name: 'となみチューリップフェア 2026',
            lat: 36.6477, lng: 136.9635,
            arrivalTime: '10:30',
            duration: 90,
            type: 'major',
            description: '300品種350万本のチューリップ！「花の大谷」高さ4m×30m、水上花壇、チューリップタワー。5/5こどもの日は中学生以下無料！',
            food: 'チューリップソフトクリーム · 軽食各所',
            tips: '砺波ICから車で5分。GW混雑 — 10:30前着推奨。5/5中学生以下無料！Ghé 1h30 rồi đi 白馬.',
            weather: '14-20°C · 🌷 チューリップ満開',
          },
          {
            id: 'd-hakuba-village',
            name: '白馬村 散策 (tối)',
            lat: 36.6984, lng: 137.8617,
            arrivalTime: '14:30',
            duration: 120,
            type: 'major',
            description: 'Tản bộ Hakuba Village — quán cafe, shop đồ outdoor, không khí resort Âu châu giữa Nhật Bản. Dãy Alps tuyết trắng phía sau. Nghỉ chân thoải mái sau ngày đường.',
            food: 'Shinshu soba · thịt bò Shinshu nướng · bia craft Hakuba Brewing',
            tips: 'Nhiều quán có terrace nhìn ra núi Alps. Bữa tối tại izakaya village rất ngon.',
            weather: '10-18°C · 🏔️ Thung lũng Alps, trong lành',
          },
          {
            id: 'd-hotel-r9-d1',
            name: 'HOTEL R9 The Yard Kurobe',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '18:30',
            duration: 0,
            type: 'major',
            description: 'Check-in. Ngày 1 di chuyển nhiều — nghỉ ngơi sớm.',
            food: 'Ăn tối đã có tại 白馬村 hoặc quán gần hotel',
            tips: 'Route 白馬→R148→糸魚川→北陸道→黒部IC. Đường R148 đẹp, trẻ ngủ trên xe.',
            weather: '14-20°C · 🌙 Mát mẻ',
          },
        ],
      },
      {
        dayNum: 2,
        title: 'Day 2 — Thứ Hai 4/5',
        subtitle: '白馬ゴンドラ → トロッコ → 宇奈月温泉 → ほたるいか',
        specialties: [
          { emoji: '🍱', name: 'Gondola top lunch', where: '白馬 山頂', desc: 'Ăn trưa nhà hàng trên đỉnh núi 1,830m — view Alps 360 độ' },
          { emoji: '🍦', name: 'Kem onsen', where: '宇奈月', desc: 'Kem mềm mịn sau Trolley — phần thưởng xứng đáng' },
          { emoji: '🦑', name: 'ほたるいか sashimi', where: 'ほたるいかミュージアム', desc: 'Mực phát sáng Toyama Bay tươi nhất' },
        ],
        segments: [
          { from: 'HOTEL R9', to: '白馬 八方尾根', km: 70, time: '1h30', mode: 'car' },
          { from: '白馬', to: '宇奈月 (via R148)', km: 100, time: '2h', mode: 'car' },
          { from: 'トロッコ往復', to: '笹平', km: 16, time: '2h', mode: 'trolley' },
          { from: '宇奈月', to: 'ほたるいかミュージアム', km: 35, time: '40min', mode: 'car' },
          { from: 'ほたるいか', to: 'HOTEL R9', km: 20, time: '25min', mode: 'car' },
        ],
        stops: [
          {
            id: 'd-gondola',
            name: '白馬 八方尾根ゴンドラ',
            lat: 36.6983, lng: 137.8320,
            arrivalTime: '08:00',
            duration: 120,
            type: 'major',
            description: 'Gondola lên 1,830m — toàn cảnh dãy Alps Bắc phủ tuyết trắng + thung lũng xanh bên dưới. Cảm giác ở giữa tuyết mà không cần leo núi! Trẻ em phấn khích.',
            food: 'Ăn sáng tại hotel trước. Có nhà hàng tại đỉnh gondola.',
            tips: 'Lên gondola sáng sớm — ít người + ánh sáng đẹp. Mang áo gió dày — trên đỉnh lạnh hơn 10°C.',
            weather: '5-15°C · 🏔️ Mát, cần áo gió dày trên đỉnh',
          },
          {
            id: 'd-trolley',
            name: '黒部峡谷トロッコ (宇奈月〜笹平)',
            lat: 36.8150, lng: 137.5860,
            arrivalTime: '13:00',
            duration: 150,
            type: 'major',
            description: 'Hẻm V-shape sâu nhất Nhật Bản — vách đá dựng đứng, sông xanh ngọc bích. 2026: vận hành đến 笹平. Khứ hồi ~2h.',
            food: 'Bento mua tại ga hoặc ăn nhẹ trên tàu',
            tips: '⚠️ Plan D trolley vào ngày 4/5 — cần đặt vé riêng (khác vé ngày 5/5). Chọn toa mở (普通客車). Ngồi bên PHẢI chiều đi.',
            weather: '14-20°C · 🌿 Hẻm núi mát mẻ',
          },
          {
            id: 'd-unazuki',
            name: '宇奈月温泉 散策',
            lat: 36.8173, lng: 137.5841,
            arrivalTime: '15:30',
            duration: 60,
            type: 'minor',
            description: 'Tản bộ phố onsen, ngâm chân ashiyu miễn phí. Mua omiyage.',
            food: 'Kem onsen · 温泉たまご',
            tips: 'Nhiều ashiyu dọc phố. Trẻ em rất thích!',
            weather: '14-20°C · 🌸 Dễ chịu',
          },
          {
            id: 'd-hotaruika',
            name: 'ほたるいかミュージアム',
            lat: 36.7632, lng: 137.3355,
            arrivalTime: '17:00',
            duration: 75,
            type: 'major',
            description: 'Phòng tối xem mực xanh phát sáng — độc nhất vô nhị. Touch pool cho trẻ.',
            food: 'ほたるいか sashimi / tempura tươi',
            tips: 'Live display phòng tối là highlight. Đặt trước nếu được.',
            weather: '15-20°C · 🌙 Mát tối',
          },
          {
            id: 'd-hotel-r9-d2',
            name: 'HOTEL R9 The Yard Kurobe',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '18:45',
            duration: 0,
            type: 'minor',
            description: 'Về hotel. Ngày 2 dày nhất — nghỉ sớm!',
            food: 'Ăn tối đã có tại ほたるいかミュージアム hoặc konbini',
            tips: null,
            weather: '14-20°C · 🌙 Mát mẻ',
          },
        ],
      },
      {
        dayNum: 3,
        title: 'Day 3 — Thứ Ba 5/5',
        subtitle: '称名滝 → 魚津水族館 → ひみ番屋街 → 雨晴海岸 Golden Hour → 富岩運河スタバ夜景 → Tokyo',
        specialties: [
          { emoji: '🍦', name: 'Kem sữa 立山', where: '称名滝 area', desc: 'Kem tươi vùng núi — quầy gần bãi đỗ' },
          { emoji: '🦐', name: '白エビ天丼', where: '魚津', desc: 'Tôm trắng Toyama — ăn trưa tươi ngon' },
          { emoji: '🍣', name: 'ます寿し bento', where: 'SA đường về', desc: 'Sushi cá hồi ép — mua mang trên xe' },
        ],
        segments: [
          { from: 'HOTEL R9', to: '称名滝', km: 45, time: '50min', mode: 'car' },
          { from: '称名滝', to: '魚津水族館', km: 55, time: '55min', mode: 'car' },
          { from: '魚津', to: 'HOTEL R9', km: 20, time: '25min', mode: 'car' },
          { from: 'HOTEL R9', to: '向島 (Tokyo)', km: 430, time: '5h', mode: 'car' },
        ],
        stops: [
          {
            id: 'd-shomyo',
            name: '称名滝 + ハンノキ滝',
            lat: 36.5733, lng: 137.4867,
            arrivalTime: '08:00',
            duration: 90,
            type: 'major',
            description: '2 thác V-shape: 称名滝 (350m) + ハンノキ滝 (500m). Chỉ có mùa tuyết tan! Sáng sớm = cầu vồng tự nhiên ngay trước mặt. Đường paved 30 phút từ bãi đỗ.',
            food: 'Kem sữa tươi tại レストハウス称名',
            tips: 'Đến sớm nhất — tháng 5 nước tuyết tan = thác cực mạnh. Mang áo mưa mỏng!',
            weather: '10-16°C · 🌤️ Mát, nắng sáng → cầu vồng',
          },
          {
            id: 'd-uozu',
            name: '魚津水族館 + ミラージュランド',
            lat: 36.7984, lng: 137.3882,
            arrivalTime: '10:30',
            duration: 90,
            type: 'major',
            description: 'Thủy cung cổ nhất Nhật Bản + rides nhẹ nhìn biển Toyama. Ngày cuối nhẹ nhàng cho trẻ.',
            food: '白エビ天丼 tại quán ven biển — ăn trưa',
            tips: 'Xem show cá (giờ cố định). Rides nhẹ cho bé.',
            weather: '15-22°C · 🌤️ Ấm, ven biển',
          },
          {
            id: 'd-himi',
            name: 'ひみ番屋街 — 氷見漁港場外市場',
            lat: 36.8567, lng: 136.9870,
            arrivalTime: '13:30',
            duration: 75,
            type: 'major',
            description: '氷見漁港直送の海産物マーケット！雰囲気のある漁港エリアで子どもたちが走り回れる。富山みやげの最終調達。雨晴海岸まで車で15分。',
            food: '🍜 氷見うどん · 🦐 白エビ天丼 · Omiyage: 氷見牛・海産物',
            tips: '子連れに最高のスポット。駐車場無料。雨晴海岸まで15分。',
            weather: '15-20°C · 🌊 港の海風',
          },
          {
            id: 'd-ameharashi',
            name: '雨晴海岸 (Ameharashi Coast)',
            lat: 36.7740, lng: 137.0240,
            arrivalTime: '17:00',
            duration: 100,
            type: 'major',
            description: '富山湾 + 立山連峰 + 赤いJR氷見線の聖地！日没18:41の1時間40分前に到着しゴールデンアワーをフルに楽しむ。',
            food: 'ひみ番屋街で買ったおやつ',
            tips: '📸 17:00着でゴールデンアワーをフル確保。JR氷見線の時刻を事前確認 → 列車が来る瞬間にシャッター。駐車場無料。',
            weather: '14-18°C · 🌅 ゴールデンアワー → 日没18:41',
            images: [
              { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Ameharashi_Coast.jpg/640px-Ameharashi_Coast.jpg', alt: '雨晴海岸 富山湾 立山連峰' },
            ],
          },
          {
            id: 'd-kansui',
            name: '富岩運河環水公園 + 世界一美しいスタバ',
            lat: 36.6983, lng: 137.2113,
            arrivalTime: '19:30',
            duration: 75,
            type: 'major',
            description: '夜の富岩運河環水公園！天門橋のライトアップが水面に映り込む幻想的な夜景。「世界一美しいスタバ」で日没後の絶景を楽しむ。',
            food: 'スターバックス コーヒー 富山環水公園店 (22:30まで営業)',
            tips: '📸 撮影ベスト: スタバを横から写す構図 + 天門橋 + 水面リフレクション。ライトアップ22:00まで。駐車場無料。',
            weather: '14-18°C · 🌃 夜景 — ライトアップ22時まで',
          },
          {
            id: 'd-return',
            name: 'Xuất phát về Tokyo',
            lat: 35.7180, lng: 139.8130,
            arrivalTime: '21:00',
            duration: 0,
            type: 'major',
            description: '北陸道 → 関越道で帰路。~5h。向島到着 2:00~2:30 AM。スタバで夜景を楽しんだ後、子どもたちは車内で熟睡。',
            food: '出発前にコンビニで夜食・飲み物 · SAでます寿しbento',
            tips: '21時出発はUターンラッシュ後 — 渋滞なし。SA休憩1〜2回。運転交代を忘れずに。',
            weather: '14°C → 18°C · 🌙 夜の北陸道 — 空いていて走りやすい',
          },
        ],
      },
    ],
  },

};

// ===== COMPARISON DATA =====
const COMPARISON = [
  { label: 'Tulip 350万本', A: { text: 'Có', type: 'yes' }, B: { text: 'Có', type: 'yes' }, C: { text: 'Có', type: 'yes' }, D: { text: 'Không', type: 'no' } },
  { label: 'Trolley hẻm núi', A: { text: 'Có', type: 'yes' }, B: { text: 'Có', type: 'yes' }, C: { text: 'Có', type: 'yes' }, D: { text: 'Có', type: 'yes' } },
  { label: '称名滝 đôi thác', A: { text: 'Có', type: 'yes' }, B: { text: 'Có', type: 'yes' }, C: { text: 'Có', type: 'yes' }, D: { text: 'Có', type: 'yes' } },
  { label: 'ほたるいか mực sáng', A: { text: 'Có', type: 'yes' }, B: { text: 'Có', type: 'yes' }, C: { text: 'Có', type: 'yes' }, D: { text: 'Có', type: 'yes' } },
  { label: '蓼科高原+ビーナスライン', A: { text: 'Có', type: 'yes' }, B: { text: 'Không', type: 'no' }, C: { text: 'Không', type: 'no' }, D: { text: 'Không', type: 'no' } },
  { label: '白馬 Alps gondola', A: { text: 'Không', type: 'no' }, B: { text: 'Không', type: 'no' }, C: { text: 'Không', type: 'no' }, D: { text: 'Có', type: 'yes' } },
  { label: 'Cần vé Alpine', A: { text: 'Không', type: 'yes' }, B: { text: 'Không', type: 'yes' }, C: { text: 'Không', type: 'yes' }, D: { text: 'Không', type: 'yes' } },
  { label: 'Độ vất vả', A: { text: '🔥🔥', type: 'neutral' }, B: { text: '🔥🔥', type: 'neutral' }, C: { text: '🔥🔥', type: 'neutral' }, D: { text: '🔥🔥', type: 'neutral' } },
  { label: 'Bé < 4 tuổi', A: { text: 'Tốt', type: 'yes' }, B: { text: 'Tốt', type: 'yes' }, C: { text: 'Tốt', type: 'yes' }, D: { text: 'Tốt', type: 'yes' } },
  { label: 'Tổng km', A: { text: '~1,330km', type: 'neutral' }, B: { text: '~1,210km', type: 'neutral' }, C: { text: '~1,210km', type: 'neutral' }, D: { text: '~1,510km', type: 'neutral' } },
  { label: 'Điểm đặc biệt', A: { text: '蓼科+諏訪湖+白馬Alps', type: 'neutral' }, B: { text: '五箇山+tulip', type: 'neutral' }, C: { text: '五箇山+称名滝', type: 'neutral' }, D: { text: '白馬 gondola+tulip', type: 'neutral' } },
];

// ===== CHECKLIST =====
const CHECKLIST = [
  { id: 'trolley-ticket', text: '🚂 Vé Trolley 11:48 ngày 5/5 — ĐẶT TRƯỚC từ 1/4 tại torokko-yoyaku.com! GW bán hết ngay!', critical: true },
  { id: 'suwako-stop', text: '🌊 Plan A: Dừng 諏訪湖 ~08:45 sau 中央道 — bãi đỗ miễn phí, 45 phút duỗi chân + ăn nhẹ', critical: false },
  { id: 'freezing-road', text: '⚠️ Plan A: Hỏi chủ pension về tình trạng đường sáng sớm — ビーナスライン 1,400m có thể đóng băng tháng 5. Xuất phát sau 9:00 khi nắng lên là an toàn nhất.', critical: true },
  { id: 'tulip-ticket', text: '🌷 チューリップフェア — Plan A, B (không cần vé trước). 5/5 trẻ em miễn phí!', critical: false },
  { id: 'himi-line', text: '📸 Xem trước giờ JR氷見線 tại 雨晴海岸 — bắt đúng khoảnh khắc tàu đỏ + núi tuyết = ảnh đỉnh!', critical: false },
  { id: 'windbreaker', text: '🧥 Áo gió dày: Plan A (ロープウェイ 2,237m lạnh hơn 10°C), Plan D (gondola 白馬 1,830m)', critical: true },
  { id: 'rain-gear', text: '🌧️ Áo mưa mỏng (nước bắn từ 称名滝) — Plan A, B, C, D', critical: false },
  { id: 'sunscreen', text: '☀️ Kem chống nắng (UV mạnh trên cao nguyên và ven biển)', critical: false },
  { id: 'snacks', text: '🍡 Đồ ăn nhẹ cho trẻ em — đặc biệt chặng xe dài Tokyo→Toyama', critical: false },
  { id: 'charger', text: '🔋 Sạc dự phòng điện thoại (chụp ảnh cả ngày hao pin nhanh)', critical: false },
  { id: 'cash', text: '💴 Tiền mặt — nhiều nơi không nhận card: SA nông thôn, omiyage nhỏ, bãi đỗ', critical: true },
  { id: 'motion-sick', text: '💊 Thuốc say xe cho trẻ — ビーナスライン và đường núi R148 nhiều cua', critical: false },
  { id: 'layers', text: '👕 Quần áo nhiều lớp — chênh lệch nhiệt độ lớn: 蓼科 8°C → Toyama 22°C trong 1 ngày', critical: true },
  { id: 'blanket', text: '🛏️ Chăn mỏng cho trẻ ngủ xe (về đêm 21:00→2:30 AM)', critical: false },
];

// ===== ESSENTIALS: LINKS =====
const USEFUL_LINKS = [
  { icon: '🚂', name: 'Kurobe Trolley — Đặt vé', desc: 'Cá nhân đặt từ 1/4/2026!', url: 'https://www.torokko-yoyaku.com/' },
  { icon: '🌷', name: 'となみチューリップフェア', desc: '22/4~5/5. 5/5 trẻ em free!', url: 'https://fair.tulipfair.or.jp/' },
  { icon: '🏨', name: 'HOTEL R9 The Yard Kurobe', desc: 'Khách sạn đã chốt — 2 đêm', url: 'https://hotelr9.jp/' },
  { icon: '🌦️', name: 'Dự báo thời tiết Toyama', desc: 'Kiểm tra trước khi đi', url: 'https://weather.yahoo.co.jp/weather/jp/16/' },
  { icon: '📱', name: 'NAVITIME — Navigation', desc: 'App chỉ đường Nhật Bản', url: 'https://www.navitime.co.jp/' },
  { icon: '🚗', name: 'NEXCO — Tắc đường GW', desc: 'Check tắc đường real-time', url: 'https://www.drivetraffic.jp/' },
];

// ===== ESSENTIALS: FOOD GUIDE =====
const FOOD_GUIDE = [
  { emoji: '🦐', name: '白エビ (Shiro Ebi)', desc: 'Tôm trắng Toyama — đặc sản #1. Tempura hoặc sashimi.' },
  { emoji: '🍣', name: 'ます寿し (Masu Sushi)', desc: 'Sushi cá hồi ép truyền thống. Mua bento mang đi tuyệt vời.' },
  { emoji: '🌷', name: 'チューリップソフト', desc: 'Kem tulip ngọt dịu — đặc sản hội chợ となみ. Chụp ảnh cực đẹp!' },
  { emoji: '🍲', name: '五箇山豆腐', desc: 'Đậu hũ Gokayama cứng, nướng than — vị đậm đà.' },
  { emoji: '🐟', name: '岩魚塩焼き', desc: 'Cá suối nướng muối. Thơm, giòn, trẻ em thích.' },
  { emoji: '🍜', name: '富山ブラックラーメン', desc: 'Ramen đen Toyama — nước dùng xì dầu đậm đặc.' },
  { emoji: '🦑', name: 'ほたるいか (Hotaruika)', desc: 'Mực phát sáng Toyama Bay — mùa 3-5月. Sashimi hoặc boiled.' },
];

// ===== WEATHER DATA (static) =====
const WEATHER = [
  { location: '黒部峡谷', temp: '14 ~ 20°C', icon: '🌿', note: 'Hẻm núi mát mẻ' },
  { location: '富山 / 魚津', temp: '15 ~ 22°C', icon: '🌤️', note: 'Ấm, mưa nhẹ' },
  { location: '松本', temp: '10 ~ 20°C', icon: '🌤️', note: 'Mát buổi sáng' },
  { location: '五箇山', temp: '13 ~ 18°C', icon: '🌤️', note: 'Ấm, có thể mưa' },
  { location: '砺波 (チューリップフェア)', temp: '14 ~ 20°C', icon: '🌷', note: 'Ấm áp, thích hợp ngắm hoa' },
  { location: '白馬 Alps', temp: '8 ~ 20°C', icon: '🏔️', note: 'Thung lũng Alps, đêm lạnh' },
  { location: '蓼科高原 (1,400m)', temp: '8 ~ 18°C', icon: '🏔️', note: 'Mát trong lành, tháng 5 sáng sớm lạnh' },
];
