// ===== PLAN DATA =====
const PLANS = {
  A: {
    name: 'Alpine Adventure',
    color: '#2E4A6B',
    subtitle: 'Chinh phục tường tuyết & đập Kurobe',
    route: '五箇山 → 室堂 → 黒部ダム → トロッコ',
    highlights: [
      { icon: '🏔️', text: 'Tường tuyết 15m tại Murodo' },
      { icon: '👨‍👩‍👧', text: 'Phù hợp bé 4+ tuổi' },
      { icon: '💰', text: 'Chi phí: ~¥205,000 (10 người)' },
    ],
    cost: {
      items: [
        { label: 'Alpine Route (vé)', amount: '¥55,000' },
        { label: 'Xăng/cao tốc', amount: '¥30,000' },
        { label: 'HOTEL R9 The Yard Kurobe (2 đêm)', amount: '¥80,000' },
        { label: 'Ăn uống', amount: '¥40,000' },
      ],
      total: '~¥205,000',
      perPerson: '~¥20,500',
    },
    days: [
      {
        dayNum: 1,
        title: 'Day 1 — Chủ Nhật 3/5',
        subtitle: 'Tokyo → 五箇山 → Kurobe',
        stops: [
          {
            id: 'a-d1-depart',
            name: 'Xuất phát Tokyo',
            lat: 35.6762, lng: 139.6503,
            arrivalTime: '06:00',
            duration: 0,
            type: 'minor',
            description: 'Xuất phát sớm để tránh tắc đường Golden Week.',
            food: null,
            tips: 'Chuẩn bị đồ ăn sáng trên xe',
            weather: '18-24°C · 🌤️ Tokyo ấm',
          },
          {
            id: 'gokayama',
            name: '五箇山 相倉集落',
            lat: 36.4260, lng: 136.9355,
            arrivalTime: '12:00',
            duration: 90,
            type: 'major',
            description: 'Làng mái tranh gassho UNESCO yên tĩnh nhất. Trẻ em thích khám phá nhà 3 tầng.',
            food: '五箇山豆腐・岩魚塩焼き',
            tips: 'Đến sớm, ít đông hơn 白川郷',
            weather: '13-18°C · 🌤️ Ấm, có thể mưa nhẹ',
          },
          {
            id: 'hotel-r9-d1',
            name: 'HOTEL R9 The Yard Kurobe',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '16:00',
            duration: 0,
            type: 'major',
            description: 'Check-in khách sạn. Nghỉ ngơi sau chặng đường dài.',
            food: 'Ăn tối tại nhà hàng quanh khu vực Kurobe',
            tips: 'Gần Kurobe IC, tiện di chuyển cho ngày hôm sau',
            weather: '14-20°C · 🌸 Mát mẻ buổi tối',
          },
        ],
      },
      {
        dayNum: 2,
        title: 'Day 2 — Thứ Hai 4/5',
        subtitle: '立山黒部 Alpine Route → トロッコ',
        stops: [
          {
            id: 'tateyama-sta',
            name: '立山駅',
            lat: 36.5835, lng: 137.4459,
            arrivalTime: '07:00',
            duration: 30,
            type: 'minor',
            description: 'Lên cáp treo bắt đầu Alpine Route. Đặt vé trước!',
            food: null,
            tips: 'Đến sớm xếp hàng, GW rất đông',
            weather: '10-15°C · 🌥️ Mát ở chân núi',
          },
          {
            id: 'murodo',
            name: '室堂・雪の大谷',
            lat: 36.5777, lng: 137.5949,
            arrivalTime: '09:00',
            duration: 120,
            type: 'major',
            description: 'Tường tuyết cao đến 15m! Điểm highlight của cả chuyến đi.',
            food: 'Bento mang theo hoặc quán tại Murodo',
            tips: 'Mặc áo ấm dày — nhiệt độ -3 đến 2°C. Tuyết có thể rơi.',
            weather: '-3 ~ 2°C · ❄️ Cần áo ấm dày, tuyết có thể rơi',
          },
          {
            id: 'kurobe-dam',
            name: '黒部ダム',
            lat: 36.5666, lng: 137.6629,
            arrivalTime: '13:00',
            duration: 60,
            type: 'major',
            description: 'Đập nước lớn nhất Nhật Bản giữa núi non hùng vĩ.',
            food: 'Kurobe Dam Curry (cà ri hình đập)',
            tips: 'Chụp ảnh panorama từ đài quan sát',
            weather: '5-10°C · 🌬️ Lạnh, gió mạnh',
          },
          {
            id: 'kurobe-trolley-a2',
            name: '黒部峡谷トロッコ',
            lat: 36.8150, lng: 137.5860,
            arrivalTime: '15:30',
            duration: 90,
            type: 'major',
            description: 'Tàu trolley chạy dọc hẻm núi Kurobe. Đi short trip đến Kanetsuri rồi quay lại.',
            food: null,
            tips: 'Chọn toa mở (open car) để ngắm cảnh. Đặt vé trước!',
            weather: '14-20°C · 🌿 Hẻm núi mát mẻ',
          },
          {
            id: 'hotel-r9-d2',
            name: 'HOTEL R9 The Yard Kurobe',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '17:30',
            duration: 0,
            type: 'minor',
            description: 'Về khách sạn nghỉ ngơi sau ngày dài.',
            food: 'Ăn tối: 富山ブラックラーメン hoặc hải sản địa phương',
            tips: 'Ngày rất dài — nghỉ sớm!',
            weather: '14-20°C · 🌙 Mát mẻ',
          },
        ],
      },
      {
        dayNum: 3,
        title: 'Day 3 — Thứ Ba 5/5',
        subtitle: 'Nghỉ ngơi → Về Tokyo tối',
        stops: [
          {
            id: 'a-d3-kansui',
            name: '富山 環水公園',
            lat: 36.7094, lng: 137.2124,
            arrivalTime: '09:00',
            duration: 90,
            type: 'major',
            description: 'Tản bộ công viên ven kênh, Starbucks đẹp nhất Nhật Bản. Trẻ em chạy chơi thoải mái.',
            food: '白エビバーガー · Cafe Starbucks',
            tips: 'Buổi sáng yên tĩnh, ít khách hơn chiều',
            weather: '15-22°C · 🌤️ Ấm, gió nhẹ',
          },
          {
            id: 'a-d3-rest',
            name: 'Nghỉ ngơi & đóng đồ',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '12:00',
            duration: 0,
            type: 'minor',
            description: 'Về hotel nghỉ trưa, đóng đồ, cho trẻ ngủ. Tránh tắc Uターンラッシュ chiều (13:00-18:00).',
            food: 'Ăn trưa quanh khu vực hotel',
            tips: '⚠️ KHÔNG lái xe 13:00-18:00 — đây là giờ tắc nặng nhất GW',
            weather: '15-22°C · 🌤️',
          },
          {
            id: 'a-d3-return',
            name: 'Xuất phát về Tokyo',
            lat: 35.6762, lng: 139.6503,
            arrivalTime: '19:00',
            duration: 0,
            type: 'major',
            description: 'Rời Kurobe sau 19:00 — tắc đã tan. Đường thông, chạy ~5h. Dự kiến về Tokyo 0:00-1:00 AM.',
            food: 'Mua bento/onigiri tại konbini trước khi lên đường',
            tips: 'Nghỉ ở SA nếu buồn ngủ. Chia ca lái nếu được. Trẻ sẽ ngủ trên xe.',
            weather: '14°C → 18°C · 🌙 Mát, đường vắng',
          },
        ],
      },
    ],
  },

  B: {
    name: 'Family Relax',
    color: '#3D6B4F',
    subtitle: 'Thư giãn onsen & trải nghiệm gia đình',
    route: '白川郷 → 魚津 → 宇奈月 → トロッコ',
    highlights: [
      { icon: '♨️', text: 'Onsen & tản bộ nhẹ nhàng' },
      { icon: '👶', text: 'Phù hợp mọi lứa tuổi, cả bé nhỏ' },
      { icon: '💰', text: 'Chi phí: ~¥150,000 (10 người)' },
    ],
    cost: {
      items: [
        { label: 'Trolley + vé tham quan', amount: '¥25,000' },
        { label: 'Xăng/cao tốc', amount: '¥25,000' },
        { label: 'HOTEL R9 The Yard Kurobe (2 đêm)', amount: '¥60,000' },
        { label: 'Ăn uống', amount: '¥40,000' },
      ],
      total: '~¥150,000',
      perPerson: '~¥15,000',
    },
    days: [
      {
        dayNum: 1,
        title: 'Day 1 — Chủ Nhật 3/5',
        subtitle: 'Tokyo → 白川郷 → Kurobe',
        stops: [
          {
            id: 'b-d1-depart',
            name: 'Xuất phát Tokyo',
            lat: 35.6762, lng: 139.6503,
            arrivalTime: '06:00',
            duration: 0,
            type: 'minor',
            description: 'Xuất phát sớm tránh tắc đường GW.',
            food: null,
            tips: 'Chuẩn bị đồ ăn nhẹ cho trẻ trên xe',
            weather: '18-24°C · 🌤️ Tokyo ấm',
          },
          {
            id: 'shirakawago',
            name: '白川郷',
            lat: 36.2578, lng: 136.9062,
            arrivalTime: '12:00',
            duration: 120,
            type: 'major',
            description: 'Làng gassho UNESCO nổi tiếng nhất. Đông hơn Gokayama nhưng nhiều dịch vụ hơn.',
            food: 'Hida beef croquette · Gohei mochi',
            tips: 'GW rất đông — đỗ xe bãi Seseragi, đi bộ qua cầu treo',
            weather: '13-18°C · 🌤️ Ấm, có thể mưa nhẹ',
          },
          {
            id: 'kansui-park',
            name: '富山 環水公園',
            lat: 36.7094, lng: 137.2124,
            arrivalTime: '16:30',
            duration: 90,
            type: 'major',
            description: 'Công viên ven kênh đẹp, có Starbucks đẹp nhất Nhật Bản. Trẻ em chạy chơi thoải mái.',
            food: '白エビバーガー (burger tôm trắng)',
            tips: 'Ngắm hoàng hôn ở đây tuyệt vời',
            weather: '15-22°C · 🌤️ Ấm, gió nhẹ',
          },
          {
            id: 'hotel-r9-b-d1',
            name: 'HOTEL R9 The Yard Kurobe',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '18:30',
            duration: 0,
            type: 'minor',
            description: 'Check-in khách sạn. Nghỉ ngơi sau ngày dài.',
            food: 'Ăn tối tại nhà hàng quanh Kurobe',
            tips: 'Gần Kurobe IC, tiện cho ngày hôm sau',
            weather: '14-20°C · 🌙 Mát mẻ',
          },
        ],
      },
      {
        dayNum: 2,
        title: 'Day 2 — Thứ Hai 4/5',
        subtitle: '魚津 → 宇奈月 → トロッコ',
        stops: [
          {
            id: 'uozu-aqua',
            name: '魚津水族館',
            lat: 36.7984, lng: 137.3882,
            arrivalTime: '09:00',
            duration: 90,
            type: 'major',
            description: 'Thủy cung cổ nhất Nhật Bản. Nhỏ nhưng ấm cúng, bé nào cũng thích.',
            food: null,
            tips: 'Xem show cá biểu diễn (giờ cố định)',
            weather: '15-22°C · 🌤️ Ấm, ven biển gió mát',
          },
          {
            id: 'kurobe-trolley-b',
            name: '黒部峡谷トロッコ',
            lat: 36.8150, lng: 137.5860,
            arrivalTime: '12:30',
            duration: 120,
            type: 'major',
            description: 'Tàu trolley qua hẻm núi Kurobe — highlight cho trẻ em!',
            food: 'Ăn trưa nhẹ trước khi lên tàu',
            tips: 'Đi đến ga Kanetsuri (40 phút) rồi quay lại. Đặt vé trước!',
            weather: '14-20°C · 🌿 Hẻm núi mát mẻ, cảnh xanh',
          },
          {
            id: 'unazuki-onsen',
            name: '宇奈月温泉街',
            lat: 36.8173, lng: 137.5841,
            arrivalTime: '15:30',
            duration: 90,
            type: 'major',
            description: 'Tản bộ phố onsen, tắm chân (ashiyu) miễn phí. Trẻ em chơi thoải mái.',
            food: 'Kem onsen, bánh mochi địa phương',
            tips: 'Nhiều ashiyu dọc phố — tắm chân miễn phí!',
            weather: '14-20°C · 🌸 Không khí trong lành',
          },
          {
            id: 'hotel-r9-b-d2',
            name: 'HOTEL R9 The Yard Kurobe',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '17:30',
            duration: 0,
            type: 'minor',
            description: 'Về khách sạn nghỉ ngơi.',
            food: 'Ăn tối: hải sản tươi Toyama',
            tips: null,
            weather: '14-20°C · 🌙 Mát',
          },
        ],
      },
      {
        dayNum: 3,
        title: 'Day 3 — Thứ Ba 5/5',
        subtitle: 'Nghỉ ngơi → Về Tokyo tối',
        stops: [
          {
            id: 'toyama-tad',
            name: '富山県美術館 TAD',
            lat: 36.7106, lng: 137.2101,
            arrivalTime: '09:30',
            duration: 90,
            type: 'major',
            description: 'Bảo tàng nghệ thuật hiện đại. Rooftop playground cho trẻ em chơi miễn phí! View Tateyama tuyệt đẹp.',
            food: 'Cafe trong bảo tàng',
            tips: 'Lên rooftop — khu chơi cho bé ngoài trời, miễn phí',
            weather: '15-22°C · 🌤️ Ấm, view núi đẹp',
          },
          {
            id: 'b-d3-rest',
            name: 'Nghỉ ngơi & đóng đồ',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '12:30',
            duration: 0,
            type: 'minor',
            description: 'Về hotel nghỉ trưa, cho trẻ ngủ, đóng đồ. Tránh Uターンラッシュ chiều (13:00-18:00).',
            food: 'Ăn trưa quanh hotel',
            tips: '⚠️ KHÔNG lái xe 13:00-18:00 — giờ tắc nặng nhất GW',
            weather: '15-22°C · 🌤️',
          },
          {
            id: 'b-d3-return',
            name: 'Xuất phát về Tokyo',
            lat: 35.6762, lng: 139.6503,
            arrivalTime: '19:00',
            duration: 0,
            type: 'major',
            description: 'Rời sau 19:00 — tắc đã tan. Về qua Joetsu, ~5h. Dự kiến về Tokyo 0:00-1:00 AM.',
            food: 'Bento/onigiri mua tại konbini',
            tips: 'Nghỉ ở SA nếu buồn ngủ. Trẻ sẽ ngủ trên xe — mang chăn mỏng.',
            weather: '14°C → 18°C · 🌙 Mát, đường vắng',
          },
        ],
      },
    ],
  },

  C: {
    name: 'Nagano Strategy',
    color: '#8B4513',
    subtitle: 'Đi từ phía Nagano, tránh đông thông minh',
    route: '松本城 → 黒部ダム → 室堂 → トロッコ → 五箇山',
    highlights: [
      { icon: '🏯', text: 'Thêm Matsumoto Castle' },
      { icon: '🧠', text: 'Route thông minh tránh đông GW' },
      { icon: '💰', text: 'Chi phí: ~¥180,000 (10 người)' },
    ],
    cost: {
      items: [
        { label: 'Alpine Route (vé)', amount: '¥55,000' },
        { label: 'Xăng/cao tốc', amount: '¥35,000' },
        { label: 'HOTEL R9 The Yard Kurobe (2 đêm)', amount: '¥60,000' },
        { label: 'Ăn uống', amount: '¥30,000' },
      ],
      total: '~¥180,000',
      perPerson: '~¥18,000',
    },
    days: [
      {
        dayNum: 1,
        title: 'Day 1 — Chủ Nhật 3/5',
        subtitle: 'Tokyo → 松本城 → 黒部ダム → Kurobe',
        stops: [
          {
            id: 'c-d1-depart',
            name: 'Xuất phát Tokyo',
            lat: 35.6762, lng: 139.6503,
            arrivalTime: '06:00',
            duration: 0,
            type: 'minor',
            description: 'Đi hướng Nagano thay vì Toyama — tránh tắc hiệu quả hơn.',
            food: null,
            tips: 'Chạy Chuo Expressway → Matsumoto',
            weather: '18-24°C · 🌤️ Tokyo ấm',
          },
          {
            id: 'matsumoto',
            name: '松本城',
            lat: 36.2387, lng: 137.9689,
            arrivalTime: '09:30',
            duration: 90,
            type: 'major',
            description: 'Lâu đài quạ đen — một trong 5 lâu đài quốc bảo. Đến sớm tránh đông.',
            food: 'Soba Matsumoto (mì kiều mạch)',
            tips: 'Đến trước 10h để vào nhanh. Sau đó xếp hàng rất dài GW.',
            weather: '10-20°C · 🌤️ Mát buổi sáng, ấm trưa',
          },
          {
            id: 'ogizawa',
            name: '扇沢駅',
            lat: 36.5587, lng: 137.7208,
            arrivalTime: '12:30',
            duration: 30,
            type: 'minor',
            description: 'Ga xuất phát Alpine Route phía Nagano. Lên xe buýt điện vào đập.',
            food: null,
            tips: 'Đỗ xe tại bãi Ogizawa (có phí)',
            weather: '8-15°C · 🌥️ Mát, độ cao lớn',
          },
          {
            id: 'kurobe-dam-c',
            name: '黒部ダム',
            lat: 36.5666, lng: 137.6629,
            arrivalTime: '13:30',
            duration: 90,
            type: 'major',
            description: 'Đập nước hùng vĩ. Đi từ phía Nagano vào nhanh hơn, ít người hơn.',
            food: 'Kurobe Dam Curry',
            tips: 'Chiều ít đông hơn sáng',
            weather: '5-10°C · 🌬️ Lạnh, gió mạnh ở đập',
          },
          {
            id: 'hotel-r9-c-d1',
            name: 'HOTEL R9 The Yard Kurobe',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '17:00',
            duration: 0,
            type: 'minor',
            description: 'Check-in khách sạn. Nghỉ ngơi.',
            food: 'Ăn tối: hải sản tươi Toyama',
            tips: null,
            weather: '14-20°C · 🌙 Mát mẻ',
          },
        ],
      },
      {
        dayNum: 2,
        title: 'Day 2 — Thứ Hai 4/5',
        subtitle: '立山 → 室堂 → トロッコ',
        stops: [
          {
            id: 'tateyama-sta-c',
            name: '立山駅',
            lat: 36.5835, lng: 137.4459,
            arrivalTime: '07:00',
            duration: 30,
            type: 'minor',
            description: 'Bắt đầu Alpine Route từ phía Toyama.',
            food: null,
            tips: 'Đặt vé trước, GW sold out nhanh',
            weather: '10-15°C · 🌥️ Mát ở chân núi',
          },
          {
            id: 'murodo-c',
            name: '室堂・雪の大谷',
            lat: 36.5777, lng: 137.5949,
            arrivalTime: '09:00',
            duration: 120,
            type: 'major',
            description: 'Tường tuyết khổng lồ! Đỉnh cao của chuyến đi.',
            food: 'Bento hoặc quán Murodo',
            tips: 'Áo ấm dày bắt buộc. -3 đến 2°C, tuyết có thể rơi.',
            weather: '-3 ~ 2°C · ❄️ Rất lạnh, tuyết có thể rơi',
          },
          {
            id: 'kurobe-trolley-c2',
            name: '黒部峡谷トロッコ',
            lat: 36.8150, lng: 137.5860,
            arrivalTime: '14:00',
            duration: 120,
            type: 'major',
            description: 'Tàu trolley hẻm núi Kurobe — cảnh đẹp tuyệt vời buổi chiều.',
            food: null,
            tips: 'Đi đến Kanetsuri rồi quay lại (~2h). Chọn toa mở!',
            weather: '14-20°C · 🌿 Hẻm núi xanh, mát mẻ',
          },
          {
            id: 'hotel-r9-c-d2',
            name: 'HOTEL R9 The Yard Kurobe',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '17:00',
            duration: 0,
            type: 'minor',
            description: 'Về khách sạn nghỉ ngơi.',
            food: 'Dinner tại nhà hàng quanh Kurobe',
            tips: null,
            weather: '14-20°C · 🌙 Mát',
          },
        ],
      },
      {
        dayNum: 3,
        title: 'Day 3 — Thứ Ba 5/5',
        subtitle: '五箇山 → Nghỉ ngơi → Về Tokyo tối',
        stops: [
          {
            id: 'gokayama-c',
            name: '五箇山 相倉集落',
            lat: 36.4260, lng: 136.9355,
            arrivalTime: '08:30',
            duration: 90,
            type: 'major',
            description: 'Ghé làng gassho UNESCO sáng sớm — yên tĩnh, ít khách. Thời gian thong thả hơn.',
            food: '五箇山豆腐 · 岩魚塩焼き',
            tips: 'Sáng sớm rất đẹp, sương và ánh nắng. Khám phá kỹ hơn vì không vội.',
            weather: '13-18°C · 🌤️ Sáng sớm mát, có sương',
          },
          {
            id: 'c-d3-rest',
            name: 'Nghỉ ngơi & đóng đồ',
            lat: 36.8719, lng: 137.4479,
            arrivalTime: '12:00',
            duration: 0,
            type: 'minor',
            description: 'Về hotel nghỉ trưa, đóng đồ, cho trẻ ngủ. Tránh Uターンラッシュ chiều (13:00-18:00).',
            food: 'Ăn trưa quanh hotel',
            tips: '⚠️ KHÔNG lái xe 13:00-18:00 — giờ tắc nặng nhất GW',
            weather: '15-22°C · 🌤️',
          },
          {
            id: 'c-d3-return',
            name: 'Xuất phát về Tokyo',
            lat: 35.6762, lng: 139.6503,
            arrivalTime: '19:00',
            duration: 0,
            type: 'major',
            description: 'Rời sau 19:00 — tắc đã tan. Về qua Hokuriku → Joetsu, ~5h. Dự kiến về Tokyo 0:00-1:00 AM.',
            food: 'Bento/onigiri mua tại konbini',
            tips: 'Route Hokuriku ít tắc hơn Kanetsu. Nghỉ ở SA nếu buồn ngủ.',
            weather: '14°C → 18°C · 🌙 Mát, đường vắng',
          },
        ],
      },
    ],
  },
};

// ===== COMPARISON DATA =====
const COMPARISON = [
  { label: 'Tường tuyết', A: { text: 'Có', type: 'yes' }, B: { text: 'Không', type: 'no' }, C: { text: 'Có', type: 'yes' } },
  { label: 'Trolley hẻm núi', A: { text: 'Có', type: 'yes' }, B: { text: 'Có', type: 'yes' }, C: { text: 'Có', type: 'yes' } },
  { label: 'Độ vất vả', A: { text: '🔥🔥🔥', type: 'neutral' }, B: { text: '🔥', type: 'neutral' }, C: { text: '🔥🔥🔥', type: 'neutral' } },
  { label: 'Bé < 4 tuổi', A: { text: '⚠️ Khó', type: 'warn' }, B: { text: 'Tốt', type: 'yes' }, C: { text: '⚠️ Khó', type: 'warn' } },
  { label: 'Tránh đông', A: { text: '⭐⭐', type: 'neutral' }, B: { text: '⭐⭐', type: 'neutral' }, C: { text: '⭐⭐⭐', type: 'neutral' } },
  { label: 'Chi phí / người', A: { text: '~¥20,500', type: 'neutral' }, B: { text: '~¥15,000', type: 'neutral' }, C: { text: '~¥18,000', type: 'neutral' } },
  { label: 'Điểm nổi bật', A: { text: 'Alpine Route', type: 'neutral' }, B: { text: 'Onsen & relax', type: 'neutral' }, C: { text: 'Matsumoto Castle', type: 'neutral' } },
];

// ===== CHECKLIST =====
const CHECKLIST = [
  { id: 'warm-jacket', text: 'Áo ấm dày (Murodo -5°C)', critical: true },
  { id: 'snow-boots', text: 'Giày không trơn / giày đi tuyết', critical: true },
  { id: 'ticket', text: 'Vé Alpine Route (ĐẶT TRƯỚC!)', critical: true },
  { id: 'trolley-ticket', text: 'Vé Trolley Kurobe (ĐẶT TRƯỚC!)', critical: true },
  { id: 'sunglasses', text: 'Kính râm (tuyết phản chiếu)', critical: false },
  { id: 'sunscreen', text: 'Kem chống nắng (UV mạnh trên núi)', critical: false },
  { id: 'snacks', text: 'Đồ ăn nhẹ cho trẻ em', critical: false },
  { id: 'charger', text: 'Sạc dự phòng điện thoại', critical: false },
  { id: 'cash', text: 'Tiền mặt (nhiều nơi không nhận card)', critical: true },
  { id: 'rain-gear', text: 'Áo mưa nhẹ / ô gấp', critical: false },
  { id: 'motion-sick', text: 'Thuốc say xe cho trẻ', critical: false },
  { id: 'layers', text: 'Quần áo nhiều lớp (chênh lệch nhiệt)', critical: true },
  { id: 'plastic-bags', text: 'Túi nilon (đựng đồ ướt/rác)', critical: false },
];

// ===== ESSENTIALS: LINKS =====
const USEFUL_LINKS = [
  { icon: '🎫', name: 'Alpine Route — Đặt vé', desc: 'Đặt trước bắt buộc mùa GW', url: 'https://www.alpen-route.com/' },
  { icon: '🚂', name: 'Kurobe Trolley — Đặt vé', desc: 'Tàu trolley hẻm núi Kurobe', url: 'https://www.kurotetu.co.jp/' },
  { icon: '🏨', name: 'HOTEL R9 The Yard Kurobe', desc: 'Khách sạn đã chốt — 2 đêm', url: 'https://hotelr9.jp/' },
  { icon: '🌦️', name: 'Dự báo thời tiết Toyama', desc: 'Kiểm tra trước khi đi', url: 'https://weather.yahoo.co.jp/weather/jp/16/' },
  { icon: '🗺️', name: 'Google Maps — Toyama', desc: 'Bản đồ khu vực', url: 'https://maps.google.com/?q=Toyama,Japan' },
  { icon: '📱', name: 'NAVITIME — Navigation', desc: 'App chỉ đường Nhật Bản', url: 'https://www.navitime.co.jp/' },
];

// ===== ESSENTIALS: FOOD GUIDE =====
const FOOD_GUIDE = [
  { emoji: '🦐', name: '白エビ (Shiro Ebi)', desc: 'Tôm trắng Toyama — đặc sản #1. Tempura hoặc sashimi.' },
  { emoji: '🍣', name: 'ます寿し (Masu Sushi)', desc: 'Sushi cá hồi ép truyền thống. Mua bento mang đi tuyệt vời.' },
  { emoji: '🍲', name: '五箇山豆腐', desc: 'Đậu hũ Gokayama cứng, nướng than — vị đậm đà.' },
  { emoji: '🐟', name: '岩魚塩焼き', desc: 'Cá suối nướng muối. Thơm, giòn, trẻ em thích.' },
  { emoji: '🍛', name: 'Kurobe Dam Curry', desc: 'Cà ri hình đập nước — món signature tại Kurobe Dam.' },
  { emoji: '🍜', name: '富山ブラックラーメン', desc: 'Ramen đen Toyama — nước dùng xì dầu đậm đặc.' },
];

// ===== WEATHER DATA (static) =====
const WEATHER = [
  { location: '室堂 (2,450m)', temp: '-3 ~ 2°C', icon: '❄️', note: 'Tuyết có thể rơi' },
  { location: '黒部峡谷', temp: '14 ~ 20°C', icon: '🌿', note: 'Hẻm núi mát mẻ' },
  { location: '富山市内', temp: '15 ~ 22°C', icon: '🌤️', note: 'Ấm, mưa nhẹ' },
  { location: '松本', temp: '10 ~ 20°C', icon: '🌤️', note: 'Mát buổi sáng' },
  { location: '五箇山 / 白川郷', temp: '13 ~ 18°C', icon: '🌤️', note: 'Ấm, có thể mưa' },
];
